### ISSUE TITLE
Using slug as primary keys

### ISSUE THREAD

**Issue by iamjstates** [emberjs/data#1380]
I had slug as pk's working with the pre-beta data. Now what is the process for implementing them now?  Thanks in advance.

Specifically I'm running in the problem at line 2254 in the push function:
Ember.assert("You must include an `id` in a hash passed to `push`", data.id != null);

**Comment by erichonkanen** [comment]
hello,

I am trying to use slug as id instead of id for a content model... I have followed along here and from the docs etc and created a serializer in my ember-cli project (ember 1.13.4, cli-1.13.5).

Problem is that it isn't working and is causing strange behavior.

The first thing I should note is that I am getting zombie (blank) records when I switched to using the slug as dynamic segment. When I click on a content record from list view into detail view, ember creates a new record with the slug as the id.

Here are the pieces:

# routes/content.coffee
```import Ember from 'ember'

ContentRoute = Ember.Route.extend
  model: (params)->
    @store.find 'content', params.content_slug

  serialize: (model)->
    content_slug: model.get('slug')

export default ContentRoute
```

# models/content.coffee
```import DS from 'ember-data'

export default DS.Model.extend
  title: DS.attr 'string'
  slug: DS.attr 'string'
  posterId: DS.attr 'string'
  sourceUrl: DS.attr 'string'
  tags: DS.hasMany 'tag', {async: true, inverse: null}
  isPublished: DS.attr 'boolean'
```

# serializers/content.coffee
```import DS from 'ember-data'

ContentSerializer = DS.RESTSerializer.extend
  primaryKey: 'slug'

export default ContentSerializer
```

I also tried the normalize: method from above in the serializer. Nothing works. In fact even if I set the `primaryKey` to `id`, which should be the default, it breaks the app.

Here is the inspector:  http://i.imgur.com/hCEJFvR.png

This is the main error Im getting when I try to start the app.. the only way to get rid of it is to completely delete `app/serializers/content.coffee`: http://i.imgur.com/VrW8ygs.png

If anyone has advice or knowledge that can help me out Id greatly appreciate it! My goal is to be able to use pretty urls in the app e.g. myapp.com/something-cool

also, I dont know if it could be related but we are using [this](https://github.com/dustinfarris/ember-django-adapter) package to format the data from the backend

thanks!

**Comment by holamendi** [comment]
Hi @erichonkanen 
Did you find a fix for those zombie records? I'm experiencing the same issue
