### ISSUE TITLE
isDirty based on strict comparison

### ISSUE THREAD

**Issue by Herriau** [emberjs/data#1540]
JSFiddle: http://jsfiddle.net/U6Xc3/

It seems like to determine whether a record is dirty Ember Data uses strict comparison between the original (last committed) value and the new value. While this may arguably make sense at first, it ends up posing some challenges.

Indeed, as soon as you start playing with 2-way binding, what used to be an integer or a date may become a string, and even though the intrinsic value has not really changed (e.g. `123` probably has the same meaning as `"123"`) Ember Data will consider that value dirty. 

This becomes even more challenging as you start playing with more advanced form components that are bound to non-primitive values such as arrays (e.g. `([2,3,5] === [2,3,5]) === false`). The strict comparison operator determines whether the two references point to the same object but it certainly isn't of any help when it comes to comparing the actual values conveyed by those objects.

The faulty piece of code in Ember Data:

``` javascript
var didSetProperty = function(record, context) {
  if (context.value === context.originalValue) {
    delete record._attributes[context.name];
    record.send('propertyWasReset', context.name);
  } else if (context.value !== context.oldValue) {
    record.send('becomeDirty');
  }

  record.updateRecordArraysLater();
};
```

At the very least you should consider using a coercive comparison (`==`), or an even more tolerant comparison such as `a.valueOf() == b.valueOf()` when possible. Also, if the operands implement a comparison method with a conventional name such as `equals()` or `isEqual()` it could be used instead.

I don't see how I can properly override this default behavior beside overriding all the substates in `DS.RootState` with a more tolerant `didSetProperty`, which is far from being ideal. Another solution that I considered is to specialize some Ember components (e.g. having a text field for dates, etc...) that would cast the value to one of the primitive types, but that does not really apply to all cases, this is a bit of a pain and it certainly deviates from the way things should be elegantly written using Ember.

**Comment by superlou** [comment]
I think I'm hitting this issue when I'm trying to set a DS.attr('date').  Would be interested in a baked in solution.

**Comment by oriSomething** [comment]
is there is a new about that? `isDirty` is a real pain with `array`s

**Comment by jpaas** [comment]
The ability to manage embedded objects/arrays and track whether they or dependent hasMany are dirty is killing me. Any solutions people have worked out in the past year are all broken on ember-data 1.19. Has anyone found anything that works on 1.19?

**Comment by andrewbranch** [comment]
+1, problem is the same with `hasChangedAttributes`. I think I agree with @igorT about comparing serialized values, because that would make the changed attributes canonically represent whether or not they are out of sync with your database (or whatever persistence layer).

**Comment by fleur** [comment]
+1

Wouldn't comparing serialized values mean there would be a new restriction that serializers would always have to serialize the same way?  I know you can't rely on JSON.stringify() to stringify in the same order all the time, and I would imagine that's a common function to use for serialization.  That said, this is killing me too.  Help.

**Comment by henrymazza** [comment]
+1

**Comment by gustavocabral** [comment]
+1

**Comment by blimmer** [comment]
For me, `null` and `undefined` dirtying the record is the biggest problem. I use [this workaround](https://gist.github.com/blimmer/cb7425d7bef06b5acb858e5f5f6a9e7a) in an intiailizer to work for my needs. You can customize the `checkIsActuallyDirty` function to meet your needs until there's a more supported solution.

**Comment by jameshoward** [comment]
The workaround to use checkIsActually dirty won't update when legitimately changing a value once you've made a change that causes `hasDirtyAttributes` to change. The problem is that changing the number to a string (e.g. 10 to "10") causes the computed `isActuallyDirty` to be recalculated and it (correctly) returns `false`. Trouble is, if you then modify the value again then `hasDirtyAttributes` remains `true` and the computed property does not get recalculated and remains `false` even though you have now made a change.

**Comment by tythewebguy** [comment]
I'm running into the same problem--numbers are getting converted to strings and making things dirty. It would be nice to override the dirty checking at the model level when it makes sense. 

I like the suggestion @decasia had:
```
note: DS.attr('string', {markDirtyWith: "strict"})
// possible options like (strict | loose | isEqual | castToString) 
```
It would also be nice to pass the values to a function to make the comparison. Maybe in the example above, if we use a string naming a primitive type it would use type coercion for the comparison, and without strings it would use a computed property--for comparing more complex data types and objects?

Regardless, it looks like many of us are running into this problem.

**Comment by songoo** [comment]
I hit same problem with "count" (DS.attr('number')) attribute, passed to ember input. Model got dirtied at moment of focus out even when I did not change a thing.

Only easy solution I could think of was computed property with setter, which i used to input instead, so only number will be set and not string ..


```
count: DS.attr('number', {defaultValue: 0}),
countDecimal: Ember.computed('count', {
        get(key) {
            return this.get("count");
        },
        set(key, value) {
            let number = parseFloat(value);
            this.set("count", number);
            return value;
        }
    })
```

`{{input value=task.countDecimal  ...`

Did not expected this kind of trouble, same with detecting relation changes, if they just write in documentation, relationDirtiness is Application layer, use own additional isRelationDirty method based on relation attribute observers, I could spare few days of googlin :(

**Comment by XaserAcheron** [comment]
As this seems to be the closest issue for this: my eyes practically fell out of their sockets today when I discovered during a debugging session that a model's `DS.attr('number')` field got set to a string. If `ember-data` doesn't do any type casting or checking for typed DS.attr's, then what the devil are they even for? o_O

This doesn't solve the object comparison case (as mentioned a while back), but the solution for numbers ought be different. It's liable to be a breaking change for some folks, of course. x:

**Comment by kdomagal** [comment]
Issue from 2013 and still not fixed...

**Comment by cincodenada** [comment]
I ran into this today, and in digging around it was suggested in #5648 that the new RecordData interface would allow customizing the comparison used to determine `hasDirtyAttributes`, which is exactly what I want. `ember-m3` and `ember-data-model-fragments` both seem way overkill for my usecase, which is just to make it so appending to an array property triggers the dirty flag.

But I looked into RecordData's source (since it's not publicly documented) and didn't see a straightforward way to accomplish this - hasChangedAttributes seems to just depend on property changes being set in `__attributes`, which appending to an array won't do. And it seems that the logic for setting a field as dirty or not seems to still be buried in [internalModel](https://github.com/emberjs/data/blob/9b7936a5b1e6adefcdc30e19ec7bd8bec5349e04/packages/store/addon/-private/system/model/internal-model.ts#L935-L955).

Am I missing something here, or did RecordData not end up exposing the surface needed to implement a custom comparison function for dirty checking?

**Comment by runspired** [comment]
I'm going to close this as we have no intention of ever changing the mechanism for dirty tracking the state of @ember-data/model in this way. That said, there are alternatives!

ember-m3 is likely the better way to go currently, and is a proof-of-concept for the direction this project will take with our replacement for @ember-data/model. It is built over fully public APIs and ergo does show this problem is fully solvable in the public API space.

@cincodenada RE using only RecordData to achieve this you would need to either extend or implement your own record-data to change how hasDirtyAttributes is calculated. You would need to clone the value from the server so that you could compare a serialized version between what the remote state you received was and the local state it.

RE RecordData documentation, we will document it as part of landing #5931 or similar.

**Comment by robbytx** [comment]
FWIW I've extended RecordData[Default] as follows to provide equivalence for `Date` objects.  Of course, this leverages internal properties of the parent class, so YMMV especially over time:
```js
class RecordDataWithDateEquivalence extends RecordDataDefault {

  isAttrDirty(key) {
    let dirty = super.isAttrDirty(key);
    if (dirty) {
      const currentValue = this._attributes[key];
      const originalValue = key in this._inFlightAttributes ? this._inFlightAttributes[key] : this._data[key];
      if (currentValue instanceof Date && originalValue instanceof Date) {
        // Compare date objects by milliseconds rather than reference equality
        dirty = currentValue.getTime() !== originalValue.getTime();
      }
    }
    return dirty;
  }

  setDirtyAttribute(key, value) {
    super.setDirtyAttribute(key, value);
    // Double-check that date objects are truly dirty
    if (value instanceof Date && key in this._attributes && !this.isAttrDirty(key)) {
      delete this._attributes[key];
    }
  }

  pushData(data, calculateChange) {
    const changedKeys = super.pushData(data, calculateChange);
    if (calculateChange) {
      for (const [ key, value ] of Object.entries(this._attributes)) {
        // Double-check that date objects are truly dirty
        if (value instanceof Date && !this.isAttrDirty(key)) {
          delete this._attributes[key];
        }
      }
    }
    return changedKeys;
  }
}
```
I'm able to construct and return instances of this type via `Store.createRecordDataFor`.

**Comment by fcofabricio** [comment]
> ```js
> extends RecordDataDefault
> ```

Hi [robbytx](https://github.com/robbytx), can you show the complete solution? How do you import `RecordDataDefault` and instantiate `RecordDataWithDateEquivalence` in `createRecordDataFor`?

**Comment by runspired** [comment]
@fcofabricio fwiw with native class syntax a nicer way of doing this is to write a decorator the serializes and deserializes from cache. That way cache is always serialized string

**Comment by robbytx** [comment]
This works with Ember 3.28:
```js
// In app/services/store.js:
import Store from '@ember-data/store';
import { RecordDataDefault } from '@ember-data/record-data';

export default class MyStore extends Store {

  createRecordDataFor(modelName, id, clientId, storeWrapper) {
    const identifier = this.identifierCache.getOrCreateRecordIdentifier({ type: modelName, id, lid: clientId });
    return new RecordDataWithDateEquivalence(identifier, storeWrapper);
  }
}

class RecordDataWithDateEquivalence extends RecordDataDefault {
  
  // ... implementation as shown in original comment above ...
}
```

In Ember 3.20 (which I was using at the time), I had to cheat and do the following instead (knowing that it was exposed in 3.28):
```js
import { RecordData as RecordDataDefault } from '@ember-data/record-data/-private';
```

It sounds like @runspired has an alternative solution in mind, but I've not looked at this much since then, so I cannot comment on that approach.
