### ISSUE TITLE
Ability to use query string params with store.find()

### ISSUE THREAD

**Issue by adamlc** [emberjs/data#1576]
I've come across an issue where I need to append query string params to a find request.

So basically I need to do something like this:

```javascript
this.store.find('contact', 1, {embed: 'company'});
```

Which should produce a GET request like:

/contacts/1?embed=company

Going through the code I couldn't see a way of doing this. Has anyone got any thoughts or ideas on how I might achieve this?

**Comment by seocahill** [comment]
Thanks for the patches hope the pull request is accepted

**Comment by simo163** [comment]
Awesome, It worked perfect!!!!

**Comment by igorT** [comment]
You will now be able to use `adapterOptions` to pass options to your adapter, using `findRecord`. We will soon have support for `include/embed` like things, but passing query params should also be easy.
Tracking this under https://github.com/emberjs/data/pull/3281

**Comment by jpoiri** [comment]
When are you targeting this feature to be release?

**Comment by abuiles** [comment]
`queryRecord` is now available in the store.

**Comment by jpoiri** [comment]
Is this the right way to use it?

this.store.queryRecord('team', 77, {include_members: true}); Doesn't seem to work for me

**Comment by wecc** [comment]
@jpoiri try `this.store.queryRecord('team', 77, { query: { include_members: true } });`

**Comment by jpoiri** [comment]
@wecc I'm getting this now using the RestAdapter
:
Error: Assertion Failed: You tried to make a query but your adapter does not implement `queryRecord`

**Comment by wecc** [comment]
@jpoiri https://github.com/emberjs/data/issues/3514

**Comment by jpoiri** [comment]
thanks, I guess I'll have to wait

**Comment by tschoartschi** [comment]
I also need this behaviour but I'm not sure how it works, because the following code snipped does not work for me.
```javascript
this.store.queryRecord('team', 77, { query: { include_members: true } });
```
I use ember-data 1.13.7 with the RESTAdapter and ember 1.13.6

What I did to get it working as expected (or as I would expect it):
```javascript
// SOMEWHERE IN A CONTROLLER OR ELSEWHERE 
    this.get('store').queryRecord(this.get('modelname'), {
        __id__: id,
        contentLanguage: newLang
    }).then(function (response) {
        // HANDLE SUCCESS 
    }, function (error) {
        // HANDLE ERROR
    });
````
And then I need to adapt buildURL in the RESTAdapter:

```javascript
import Ember from 'ember';
import DS from 'ember-data';

export default DS.RESTAdapter.extend({
    //...
    buildURL: function (type, id, snapshot, queryType, query) {
        if (queryType === 'queryRecord' && query.__id__) {
            url += '/' + query.__id__;
            query.__id__ = null;
            delete query.__id__;
        }
        return url;
    }
});
```
I think this is a hack and not a nice software design. Is `queryRecord` expected to query for one record AND add query params?

Could someone help me figure out what would be a nice solution? Thanks a lot :-)

If someone is interested; our use case is the following:
In the admin interface the user can enter informations to some product. After the user added all informations in one language he has the possibility to switch the `content language`, which means he can enter the same informations in another language. Because `record.reload` does some merging-magic it is not suitable for us. The form should always be populated with the fresh data from the server. The data is always depending on the `content language`. I implemented the behaviour as follows:
When the user switches the `content language` I unload the record from the store and reload the record with queryRecord from the server. With the outlined solution it works as I need it but I think this is a hacky solution

**Comment by Criten** [comment]
I got @tschoartschi's hack working with ActiveModelAdapter.... (I admit it's even more hacky than his...)

```javascript
// app/adapters/application.js
import DS from "ember-data";

export default DS.ActiveModelAdapter.extend({
  buildURL: function (type, id, snapshot, queryType, query) {
    if (queryType === 'queryRecord' && query.__id__) {
      var url = '/' + type + 's/' + query.__id__;
      query.__id__ = null;
      delete query.__id__;
      console.log(url);
      return url;
    }

    return this._super(type, id, snapshot, queryType, query);
  }
});
```

@wecc if i try using what you suggested i get the following request..

```javascript
    return this.store.queryRecord('menu', 'main', {
      subdomain: params.subdomain
    });
```
```
http://cs.lvh.me:4200/menus?0=m&1=a&2=i&3=n
```

**Comment by bkCDL** [comment]
@wecc 's example is excellent. Thanks!

Incidentally, I was able to call the querystring object in BuildURL itself also:

    buildURL: function buildURL(modelName, id, snapshot, requestType, query) {
      var e, sURL;
      try {
        sURL = [this.get("host"), this.get("namespace"), "reports", id].join("/");
        query = Ember['default'].get(snapshot, "adapterOptions.query");
        if (!Em.isBlank(query)) {
          sURL += "?" + Ember['default'].$.param(query);
        }
        return sURL;
      } catch (_error) {
        e = _error;
        return Em.Logger.error("report.buildURL ERROR", e);
      }
    }

I called the report model from the controller like this:

     this.store.findRecord('report', id, { adapterOptions: { query: qsObj }}).then(...

where `qsObj` is a json object I use filled with various query string parameters my API expects for reports I call.

Bryan

**Comment by allthesignals** [comment]
```

**Comment by allthesignals** [comment]
Struggling a bit with `queryRecord()` as well. The following code builds the url, "profiles?1." I am using the JSONAPI adapter.

```
export default Ember.Route.extend({
  model: function(params) {
    return this.store.queryRecord("profile", params.profile_id, { 'query': { 'include': 'place' } });
  }
```
