### ISSUE TITLE
DS.Errors cannot be used with {{#each}} helper

### ISSUE THREAD

**Issue by slindberg** [emberjs/data#1683]
Even though `DS.Errors` is `Ember.Enumerable`, it does not pass the [array-like test](https://github.com/emberjs/ember.js/blob/v1.4.0-beta.3/packages/ember-handlebars/lib/helpers/each.js#L44) in the `each` handlebars helper. Trying to loop over a model's validation errors in a template results in the error:

    Uncaught Error: Assertion Failed: The value that #each loops over must be an Array. You passed <DS.Errors:emberXXX> 

[jsbin example](http://emberjs.jsbin.com/OtONAFA/1/)

**Comment by bmac** [comment]
I'm going to close this issue. Previously Ember Data allowed you to iterate over the `record.errors` property directly. Since then the API has been changed so now you need to iterate over the `record.errors.messages` or `record.errors.attrName` property instead. I have opened a pr to make this more clear in the model docs https://github.com/emberjs/data/pull/2899.
