### ISSUE TITLE
Deleted records are not accessible

### ISSUE THREAD

**Issue by simonweil** [emberjs/data#1737]
When running `deleteRecord()` the record is removed from the `content` of the controller and therefore can't access the record to run the `save()` command to persist the deletion.

Another issue I came across is that after deleting the record I have no indication that I have records that need persisting if I do now wish to persist them right after I run the `deleteRecord()` command.

Is this really a problem or am I missing something?

**Comment by glagola** [comment]
+1

**Comment by averydev** [comment]
+1

**Comment by fivetanley** [comment]
Please don't add +1s. They disrupt the flow of the conversation and we almost always miss them in our email since it's close to the :+1: emoji.

We'll try to review this as soon as possible, as @bmac and @igorT have added it to the 1.0 criteria. If you would like to try implementing it, we'd be more than happy to point you in the right direction.

**Comment by patternleaf** [comment]
+1

**Comment by dylanmensaert** [comment]
Any use case that does not persist records immediately can benefit from this feature.

**Comment by wojciech-wieronski** [comment]
+1

**Comment by wecc** [comment]
Closing this since #3539 has been merged :tada:

This is going to be available (as a breaking change) in Ember Data 2.0. Details will be explained in the upcoming ED 2.0 blog post.

**Comment by simonweil** [comment]
Great news, thank you :)
