### ISSUE TITLE
Error while loading route: Error: Assertion Failed: You must include an `id` in a hash passed to `push`

### ISSUE THREAD

**Issue by mgenev** [emberjs/data#1757]
I get this nonsensical error and no real indication what is wrong. No documents that I can find.

I'm just trying to get an index of articles:

App.ArticlesIndexRoute = Ember.Route.extend({
    model: function () {
      return this.store.find('article');
    }
});

findAll('article')  doesn't work either.

I have no idea \ where I'm supposed to find the proper usage from and it changes from version to version. Please make the errors make sense and docs.

**Comment by caseyhelbling** [comment]
I have some raw data that does not have primary keys for the records - (consider time sequence data, an enumerated list of options for dropdown, or some other set of non ID data points). Is there a better Adapter to use instead of RESTAdapater that doesn't require a PK? 

Maybe some sort of RESTAdapter that injects pseudo ids in the Serializer or something? 

Thoughts?

**Comment by peter-story** [comment]
Thank you for clarifying that, @mixonic. I've corrected it. And while you're correct about one's ability to write their own adapter, I don't think that's the solution for @mgenev, as fixing his header is probably much simpler.
