### ISSUE TITLE
DS.Model should have an `unhandledEvent` method 

### ISSUE THREAD

**Issue by pixelhandler** [emberjs/data#1805]
DS.Model should have an `unhandledEvent` method that can be used to silence stupid assertions like `didSetProperty` while in state `root.deleted.uncommitted`.

Ember.StateManager has this, see: https://github.com/emberjs/ember-states/blob/8416e5e69c3dc7f51ba21faaf15991a6d99ffd14/packages/ember-states/lib/state_manager.js#L547-L551

    If the StateManager attempts to send an action but does not find an appropriately named method in the current state or while moving upwards through the state hierarchy, it will repeat the process looking for a `unhandledEvent` method. If an `unhandledEvent` method is found, it will be called with the original event name as the second argument. If an  `unhandledEvent` method is not found, the StateManager will throw a new Ember.Error.

**Comment by bmac** [comment]
I believe the thinking on this in the past has been that an `unhandledEvent` is not included because Ember Data wants the errors to be thrown. This is because the unexpected events represent either a bug in the Ember Data state machine (that should be fixed) or a bug in the application code attempting to do something it shouldn't.

**Comment by bmac** [comment]
@pixelhandler. I'm going to close this issue. I think the Ember Data team would prefer to identify and fix individual `unhandledEvent`issues rather then try to hide them all.

**Comment by pixelhandler** [comment]
Thanks @bmac
