### ISSUE TITLE
DS.Errors not working as documented

### ISSUE THREAD

**Issue by wbyoung** [emberjs/data#2028]
I'm [following the documentation](http://emberjs.com/api/data/classes/DS.Errors.html), but it appears error responses are not working as documented.

I'm returning a `401` response for the following model:

``` javascript
App.User = DS.Model.extend({
  email: attr('string')
});
```

The data in the response is:

``` javascript
"user": {
  "errors": {
    "email": "invalid email address"
  }
}
```

And the documentation wasn't all that clear about where the errors should go, so I've also tried:

``` javascript
"errors": {
  "email": "invalid email address"
}
```

When I create a record and save:

``` javascript
user.save().catch(function() {
  console.log(user.get('errors')); // undefined
  console.log(user.get('errors').errorsFor('email')); // doesn't work
});
```

Please let me know if this is inappropriate to submit here and should be asked on Stack Overflow instead. I felt it right to submit here because it doesn't seem to be working as documented, but it could simply be me misunderstanding something.

**Comment by vasilakisfil** [comment]
Hello! I think Docs about DS.Errors are totally out of Sync. First let's take a look at the code: In DS.RESTAdapter the code does not support errors: https://github.com/emberjs/data/blob/v1.0.0-beta.14.1/packages/ember-data/lib/adapters/rest_adapter.js#L746-L757 (that's also correctly documented to the docs).
Only ActiveModelAdapter supports DS.Errors. The code is here:
https://github.com/emberjs/data/blob/v1.0.0-beta.14.1/packages/activemodel-adapter/lib/system/active_model_adapter.js#L144

It creates a DS.InvalidError object which according to the docs: 
"The `DS.InvalidError` must be constructed with a single object whose
  keys are the invalid model properties, and whose values are the
  corresponding error messages. For example:"
  ```javascript
  return new DS.InvalidError({
    length: 'Must be less than 15',
    name: 'Must not be blank'
  });
  ```

So from what I understand, Ember expects the errors in the following form:
```json
{
    "email": ["is too long (maximum is 255 characters)", "is invalid"],
    "password": ["is too short (minimum is 6 characters)"],
    "password_confirmation": ["can't be blank"]
}
```

However the only that semi-worked is the format
```json
{
    "email": [{
        "attribute": "email",
        "message": "is too long (maximum is 255 characters)"
    }, {
        "attribute": "email",
        "message": "is invalid"
    }],
    "password": [{
        "attribute": "password",
        "message": "is too short (minimum is 6 characters)"
    }],
    "password_confirmation": [{
        "attribute": "password_confirmation",
        "message": "can't be blank"
    }]
}
```

And I say semi-worked because I could only print the error messages like that:
```handlebars
{{#each error in errors.messages}}
  <div class="error">
    {{log error}}
    {{error.attribute}} {{error.message}}
  </div>
{{/each}}
```
However according to the (abstract) docs I should also be able to show the errors per attribute like:

```handlebars
{{#each message in errors.email}}
  <div class="error">
    {{message}}
  </div>
{{/each}}
```

Could a senior pick this up and update the docs? It's pity that Ember tries to provide such a nice feature for form errors but lacks documentation.

Some threads that helped me:

http://stackoverflow.com/a/24031233/1291118
https://marcqualie.com/2014/04/model-errors-in-emberjs

**Comment by bmac** [comment]
Hi @vasilakisfil. You bring up some good points our Error docs are defiantly out of sync in some areas.  

I'd like to get some more info about the trouble you are experiencing with the error format. What version of ember and ember data are you using?

I was able to successfully get Ember Data to log errors using the first format you described http://emberjs.jsbin.com/sidarufuco/1
```js
{
    "email": ["is too long (maximum is 255 characters)", "is invalid"],
    "password": ["is too short (minimum is 6 characters)"],
    "password_confirmation": ["can't be blank"]
}
```

**Comment by vasilakisfil** [comment]
I am using Ember 1.8.1 and ember-data 1.0.0-beta.14.1.

**Comment by bmac** [comment]
I suspect the reason why you didn't see any error messages with is the result of a bug in Ember that that would cause unhanded rejected promises to crash the runloop. Its currently fixed on canary https://github.com/emberjs/ember.js/pull/9904 but I'm not sure if the fix is in any of the beta versions. The stackoverflow you linked hints as this by recommending you always supply a reject callback. However another way to fix the issue is to define an `Ember.onerror` function.

**Comment by vasilakisfil** [comment]
I had the reject callback as stackoverflow link suggests. The second link suggests the second format that semi-worked for me.
