### ISSUE TITLE
DRY: Second use of inverse

### ISSUE THREAD

**Issue by sbaverett** [emberjs/data#2058]
I am a student learning JS and Ember. I have created this issue with the encouragement of my instructor. Here is the code in question.
```javascript
App.Employee = DS.Model.extend({
  name: DS.attr(),
  role: DS.attr(),
  boss: DS.belongsTo('employee', { async: true, inverse: 'reportsTo' }),
  reportsTo: DS.hasMany('employee', { async: true, inverse: 'boss' })
});
```
This code worked only after a second "inverse" was added on line 4. Given the relationship between boss and reportsTo, it seems that a single use of inverse should be adequate. Thanks.

**Comment by igorT** [comment]
We probably should refactor inverses into a separate file/package with better unit tests, but this certainly seems doable, it is a bit tricky with inheritance though. If someone want's to tackle it, I am all for it.

**Comment by bmac** [comment]
The problem here is `employee` is an reflexive relationships which makes it harder for Ember Data detect the correct inverse. Reading the with context of `boss` and `reportsTo` makes it obvious that these two relationships should sync up. Unfortunately, Ember Data isn't that smart and often assumes reflexive `belongsTo` relationships should be one-to-one relationships. 

Because this has been a common source of confusion for many users Ember Data now warns if a reflexive relationship does not have an inverse key. https://github.com/emberjs/data/blob/0f06c86b881ffb22e3e3fd8b2ef61726b9c17b22/packages/ember-data/lib/system/relationships/ext.js#L257-L259
