### ISSUE TITLE
ActiveModelAdapter format documentation issue

### ISSUE THREAD

**Issue by exlee** [emberjs/data#2172]
In documentation there is information that:
> The ActiveModelAdapter expects the JSON returned from your server to follow the REST adapter conventions substituting underscored keys for camelcased ones.

However this is not only vague but also misleading, since the format differs and cause confusion:
* http://stackoverflow.com/questions/20954980/ember-data-belongsto-association-json-format
* http://stackoverflow.com/questions/23485883/ember-data-not-loading-nested-hasmany

The lack of documentation also makes adapting non-standard configurations to work (for example Mongoid-based).

My suggestions is improvement to existing documentation by adding examples and (optional) format definition to clear up confusion.

**Comment by igorT** [comment]
cc @bmac

**Comment by mikehollis** [comment]
The current documentation includes an example that has the `_id` extension on it, so I don't know if this issue is relevant anymore.

However, if it is, I've updated the documentation to be even a little more explicit:
https://github.com/mikehollis/data/commit/8b0cc7e1e39ee2def121c7ca543ccc469e5c3f90

If you'd like me to issue a pull request, just let me know!
**side note:** Is that the correct spot to edit the API documentation?

cc @igorT

**Comment by wecc** [comment]
@mikehollis I know this is a bit old but I think your commit looks good. Feel free to open a PR over at https://github.com/ember-data/active-model-adapter

I'm closing this since the ActiveModelAdapter now lives in its own repo.
