### ISSUE TITLE
Use case for transactions in EmberData

### ISSUE THREAD

**Issue by dgtman** [emberjs/data#2267]
We have an interesting use case.  We are creating an Ember front end to a legacy application with a well established data model.

This model includes a "contact" table (/contact/1) and various child tables (/contact/1/addresses, /contact/1/phones, etc)

The user can load a contact on one screen, and optionally visit other screens that will show the phones for that contact, the addresses for that contact, etc (the contact table has maybe a dozen such "child tables").

The problem is, the use case says that they must be able to update the contact and all it's child records all at once.

We could do something like this in a controller action (in pseudocode):
  addresses.save();
  phones.save();
  contact.save();

The problem is when, for example, the saving of the addresses succeeds, but the save on phones fails (business rule violation on the server for example).  We need to roll back all previous saves on other child records.

Given that we are using EmberData talking to RESTful services, how can we roll back a transaction?

**Comment by igorT** [comment]
There really isn't a consistent way to have transactions over http without your server helping you out. You can try to mimick them, but you will usually run into edge cases. We used to support transactions but they proved brittle and never really worked. Sometime in the future it should be possible to create an addon with similar functionality, but again you will run into edge cases. For example, what happens if your frontend goes offline in a non stable state.
