### ISSUE TITLE
[rfcs] - knowing when records are loaded or not

### ISSUE THREAD

**Issue by fivetanley** [emberjs/data#2431]
When people are trying to check for contains/etc. See if the relationship has been loaded without asking the server for the records. There is currently no API for this.

An example: has the post loaded its comments? if not I may want to make a different kind of query

What are the comment IDs? I may have not yet loaded the comments but I want to know their IDs without telling the server to load them.

We would like contributors to use this issue for use cases.

**Comment by igorT** [comment]
https://github.com/emberjs/rfcs/pull/57 is aiming to address this

**Comment by pangratz** [comment]
I think this issue can be closed since an [initial implementation of references](https://github.com/emberjs/data/pull/3303) has been merged into `master`. Having the `ds-references` feature enabled, it can be checked if there is data for a relationship via `model.belongsTo("family").value() !== null` and `model.hasMany("children").value() !== null`.

**Comment by fivetanley** [comment]
@pangratz thank you!
