### ISSUE TITLE
Namespace ignored on modelFor call

### ISSUE THREAD

**Issue by getabetterpic** [emberjs/data#2579]
When namespacing an adapter, modelFor ignores the namespace. Steps to reproduce:

Set up namespace on adapter
Set up PostRoute
Set up CommentsRoute
In CommentsRoute, model returns modelFor('post').get('comments')
The call made is without the namespacing, causing network request to fail.

**Comment by wecc** [comment]
@getabetterpic ping

**Comment by elidupuis** [comment]
I'm seeing this behaviour (`adapter.namespace` being ignored) with a leading slash on my `links` relationships.

We had leading slashes but no `namespace` and everything worked fine:

```js
// Team Model
"id": 1
// ...
"links": {
  "members": "/team/1/members" // request made: HOST/team/1/members
}
```

After adding a `namespace: "NS"`:

```js
HOST/NS/team/1/members // what I expected
HOST/team/1/members // what I got
```

After removing the leading slash from the paths in `links`, the path gets appended to the current model:

```js
"id": 1
// ...
"links": {
  "members": "team/1/members" // request made: HOST/NS/team/1/team/1/members
}
```

To get everything working again I removed the `team/1` from the path in `links`:
```js
"id": 1
// ...
"links": {
  "members": "members" // request made: HOST/NS/team/1/members
}
```

So... Is this all expected behaviour? What is the recommended way to format paths in `links` objects?

**Comment by wecc** [comment]
I'd say this is the intended behavior.

If you want to have full control over your URLs you should use absolute URLs for links, like `https://host/namespace/team/1/members`.

If you want the links to be relative you can provide links without a leading forward slash. By doing so you're telling Ember Data that the link is relative to the currently requested link. That's why `team/1/members` is appended to the currently requested link `https://host/namespace/team/1` to form `https://host/namespace/team/1/team/1/members`.

By providing a leading forward slash you're telling Ember Data that it's a root-relative link. And root in this case is `https://host`, not `https://host/namespace`.

I know that ASP.Net uses `~` as an "application root operator". If we'd have our "API root" at `https://host/namespace` and you provide `~/team/1/members` in your link, that could be translated to `https://host/namespace/team/1/members`. I'm just spitballing here though :)

**Comment by elidupuis** [comment]
Makes sense. Looking at the JSON API spec I've noticed that most of the examples now show absolute URLs starting with `http://...`

Thanks for your response!
