### ISSUE TITLE
Weird `hasMany` behaviour?

### ISSUE THREAD

**Issue by twokul** [emberjs/data#2744]
I might have gone completely crazy but it seems like this [JSBin](http://emberjs.jsbin.com/cuqacu/1/edit?js) doesn't work as I expect it to work.

If you click on `Tonight`, your're supposed to see 2 events. If you click on `Tomorrow`, you’re supposed to see 3 events. Instead you see 0 when you click on `Tonight` and 3 when you click on `Tomorrow`.

As far I can tell, when a `hasMany` relationship starts to share records, all records are associated with the last created one (the last one wins). Try deleting first object from `cardLists.cards` with id `foo-baz`.
Clicking on `Tonight` will show you one record and 2 when you click on `Tomorrow`.

ED versions: v1.0.0-beta.12 - latest canary.

I'll be more than happy to patch but I would like some feedback/thoughts first.

**Comment by bmac** [comment]
@twokul It looks like Ember Data is getting confused by the `cardList: DS.belongsTo('cardList')` relationship on the `Card` model. Ember Data assumes that relationship is the inverse of the `cards` hasMany on the `CardList` Model and is attempting to arrange the cards in such a way that they can only appear in one `CardList` since it appears that each card has a "has one" relationship to the `CardList`. 

One fix could be to remove the `cardList: DS.belongsTo('cardList'),` relationship on `Card` model since it doesn't appear to be in the resulting json.

A second fix would be to tell Ember Data that the `cards` relationship doesn't have an inverse so it won't attempt to keep that relation in sync with the `cardList` relationship.
```js
App.CardList = DS.Model.extend({
  cards: DS.hasMany('card', {inverse: null})
});
```

**Comment by twokul** [comment]
@bmac thanks! closing.
