### ISSUE TITLE
DEPRECATION: has should be called on the registry instead of the container

### ISSUE THREAD

**Issue by twokul** [emberjs/data#2806]
Should this [lookup](https://github.com/emberjs/data/blob/f49c2a7fe5fb5483b72999cc8ccffb87d8cf4c91/packages/ember-data/lib/system/store.js#L1416) be replaced with `this.container._registry.lookupFactory` given the changes in Ember introduced in this [PR](https://github.com/emberjs/ember.js/pull/9981)? Otherwise, a lot of deprecation warnings are shown (`DEPRECATION: has should be called on the registry instead of the container`)

**Comment by bmac** [comment]
@twokul Sounds like a good change to make. Although I'm curious if there is a better way to access the registry then `_registry` Ember Data has been bitten before by relying on private apis like that. Would you be interested in making a pr?

**Comment by igorT** [comment]
ping @dgeb

**Comment by twokul** [comment]
@bmac I can look into it.

**Comment by dgeb** [comment]
So `lookup` and `lookupFactory` are available on the container without deprecation. In fact, they should be accessed from the container. 

I would guess that an instance of the registry is being injected into the store as `this.container`. This would still allow `lookup` and `lookupFactory` to work, but with deprecations, since the registry will proxy them to its default container (the first container created by the registry).

I would look into the initializers because they are now being passed a registry instead of a container.

The end game here is to have an Application initializer, which gets passed an Application instead of a registry. You can call `register` and `inject` directly on this, which will flow through to the Application's internal registry.

Furthermore, we will soon also have ApplicationInstance initializer, which will get passed an ApplicationInstance. You'll be able to call `lookup` and `lookupFactory` directly on this, which will flow through to the instance's internal container.

I believe @tomdale is currently working on this and can probably provide more details / status. Hopefully we can provide some workarounds to avoid these deprecations.

**Comment by bmac** [comment]
ping @twokul Do you have time to work on a pr for this?

**Comment by igorT** [comment]
Seems like we don't need to do anything anything here? Because @dgeb said using it on the container is correct? Or maybe I am very confused

**Comment by bmac** [comment]
@igorT it sounds like many of the places in ember data that use the variable `container` are now actually getting assigned a `registry` instance in Ember 1.11.

**Comment by twokul** [comment]
I'll look into this tonight

**Comment by bmac** [comment]
@twokul any progress?

**Comment by twokul** [comment]
@bmac I replicated the issue in test suite. Problem is that test suite is still configured to get an instance of the `container`, not `registry`. Secondly, I'm still a bit confused on when to use `registry` vs. `container`. It seems like we want to switch to `registry.register` and `container.lookup` but I'm not 100%.

**Comment by toranb** [comment]
Just following along here and wanted to verify the last comment is /is not correct for 1.11+

```js
registry.register
container.lookup
```

In part I ask because both container.lookup and registry.lookup work ... yet for the container.lookup it seems like I need this hacky line that I'd rather do without (as it looks rather private api ish)

```js
    registry = new Ember.Registry();
    container = registry._defaultContainer = registry.container();
```

**Comment by bmac** [comment]
@toranb here is my attempt at solving this issue. https://github.com/emberjs/data/pull/2884

I didn't run into a case where I needed to set `_defaultContainer` because it looks like `registry.container()` method will do that for you. https://github.com/emberjs/ember.js/blob/master/packages/container/lib/registry.js#L153

**Comment by bmac** [comment]
Closed by #2884.

**Comment by melnychuk** [comment]
Hmm... CLI warnings about bad packaging are gone, but I'm still getting these Deprecation warnings on beta.16 with Ember canary.

**Comment by bmac** [comment]
@melnychuk could share a copy of the warnings you are seeing?

**Comment by melnychuk** [comment]
@bmac sorry, false alarm. Cleaned cache and now everything works fine. No more "has should be called..." deprecation warnings in the console.

**Comment by ChrisHonniball** [comment]
This deprecation warning is still present. [JSBin](http://jsbin.com/xeyaki/1/edit?html,js,output)

**Comment by maletor** [comment]
I'm seeing the same issue as @ChrisHonniball.

**Comment by bmac** [comment]
I have opened pr https://github.com/emberjs/data/pull/3070 to address the new issues. Unfortunately, its currently blocked on a bug in Ember.
