### ISSUE TITLE
Reserved JSON attributes: "type"

### ISSUE THREAD

**Issue by jbrown** [emberjs/data#2830]
Are there any restrictions on using `type` as a model attr? 

```json
{
  "widget": {
    "id": "1",
    "type": "foo",
    "label": "bar"
  }
}
```

I think this is issue with ember-data-factory-guy but I just wanted to check here first.

**Comment by bmac** [comment]
Currently, there are some use cases like async polymorphic record and embedded polymorphic records where Ember Data expects the value of the type attribute to match the type of the record. In most other cases you can use `type` without penalty. 

However, I would encourage you not to use `type` unless it matches the name your record ("widget" in given example). This is because in the latest version of the JSON API spec `type` is a reserved key (like `id`). I suspect as Ember Data moves to sync up with JSON API `type` will become a reserved key on the model.

**Comment by fivetanley** [comment]
>  I suspect as Ember Data moves to sync up with JSON API type will become a reserved key on the model.

This seems more like an adapter/serializer concern for figuring out what model is being loaded. This seems unfortunate that we have another popular field name conflicting.

**Comment by wecc** [comment]
Related: https://github.com/emberjs/data/issues/602

**Comment by bmac** [comment]
@fivetanley you make a good point. Now that I think about it more I suspect that since `store.push` takes the type as its first argument Ember Data has no need to check a `type` key on the normalized payload so it could be safe to use as an attribute.

**Comment by bmac** [comment]
@jbrown re-reading your issue I see now that you are asking specifically about "type" in the JSON response from a server. In that case I believe type is reserved because it is reserved by the jsonapi spec.
http://jsonapi.org/format/#document-structure-resource-objects
