### ISSUE TITLE
Docs of DS.Seriazlizer doesn't show it has store has an attribute

### ISSUE THREAD

**Issue by oriSomething** [emberjs/data#2841]
the [Serializer's docs](http://emberjs.com/api/data/classes/DS.Serializer.html#method_normalize) doesn't show that i cat get `store` using `this.get('store')`. I also couldn't get it by the [source](https://github.com/emberjs/data/blob/1.0.0-beta.15/packages/ember-data/lib/system/serializer.js). but i was exposed to this ability for the first time from the [ember-parse-adapter](https://github.com/clintjhill/ember-parse-adapter/blob/master/lib/ember-parse-adapter/serializer.js#L66).

so:
- is it supported?
- the problems are in docs? and if so, where can i find more about those hidden features?

**Comment by wecc** [comment]
The `store` property on serializers gets injected automatically [here](https://github.com/emberjs/data/blob/master/packages/ember-data/lib/initializers/store_injections.js#L11), that's why it's not visible in the source file.

I think in makes sense if we could document this as I believe this _is_ supported. Maybe we could just add a `@property` doc block withing defining the property itself? Thoughts @bmac @fivetanley ?

**Comment by oriSomething** [comment]
maybe also the next service injection API, will make it clearer too

**Comment by bmac** [comment]
I'm :+1: on documenting the store property. @oriSomething would you like to open that pr?

**Comment by oriSomething** [comment]
@bmac don't mind.
but should i also add `@property` doc block as was suggested by @wecc?

**Comment by bmac** [comment]
Yes please.

**Comment by bmac** [comment]
Closed by #2843
