### ISSUE TITLE
should serializerForAdapter take the store as an argument?

### ISSUE THREAD

**Issue by bmac** [emberjs/data#2916]
Before https://github.com/emberjs/data/pull/2617 the helpers in https://github.com/emberjs/data/blob/4205061a1ce72a61a01dab0f34c2df4ac25f6341/packages/ember-data/lib/system/store/serializers.js did not need access to the store. Now they both need to use the store. `serializerFor` got moved back onto the store while `serializerForAdapter` stayed as a helper method. This feels a little bit inconsistent. Should `serializerForAdapter` be moved onto the store or should `serializerFor` be refactored back into a helper that receives `store` as an argument.

**Comment by jmurphyau** [comment]
@bmac I've expanded on the lists that were created in #2617 below to give a clearer overview of the current situation:

## Current preference/order

### Adapters:

1 `adapterFor`: `typeKey`
2 `adapterFor`: `'application'`
3 `defaultAdapter`: `this.adapter` (default to `-rest`)
4 `defaultAdapter`: `'application'`
5 `defaultAdapter`: `'-rest'`

### Serializers:

1 `serializerFor`: `typeKey`
2 `serializerFor`: `'application'`
3 `serializerFor`: `adapterFor(typeKey).defaultSerializer` (this could return either the type specific adapter, the application wide adapter or the -rest adapter)
4 `serializerFor`: `'-default'`

### `serializerForAdapter` function

1 `serializerForAdapter `: `adapter.serializer`
2 `serializerFor`: `typeKey`
3 `serializerFor`: `'application'`
4 `serializerFor`: `adapterFor(typeKey).defaultSerializer` (this could return either the type specific adapter, the application wide adapter or the -rest adapter)
5 `serializerFor`: `'-default'`

So with these lists in mind - serializerForAdapter is only used to access the adapters `serializer` property as a first preference, then goes through the standard `serializerFor` logic.

`serializerForAdapter` is used [here](https://github.com/emberjs/data/blob/174fc94488d7e66ebb8b61e3bef142c0d051edca/packages/ember-data/lib/system/store/finders.js#L17) and [here](https://github.com/emberjs/data/blob/174fc94488d7e66ebb8b61e3bef142c0d051edca/packages/ember-data/lib/system/store.js#L1996). I think the best bet would be to change both of these from:

`var serializer = serializerForAdapter(store, adapter, type);`

to

`var serializer = adapater.serializer || store.serializerFor(type);`

**Comment by jmurphyau** [comment]
I've made some edits to my above comment. I missed item 6 in `serializerForAdapter` list above - but I don't believe this has much (if any) impact on the proposed solution.

**Comment by Chun-Yang** [comment]
Hi @jmurphyau @bmac , I has a use case for serializerForAdapter. I think other people may have the similar use cases.

I am developing an ember-cli addon(https://github.com/Chun-Yang/ember-fryctoria) to handle offline for ember data. The idea is to add a localforage-adapter to handle the local operations. 

The addon need to switch adapters when trying to talk to remote server and localforage. So the adapter.serializer should always take precedence. 

I am confused on why we have a serializerFor and a serializerForAdapter. IMO, there should only be one serializerFor. Can you consider always let adapter.serializer take precedence since different adapters would have different serializers.

**Comment by igorT** [comment]
@stefanpenner thought it's ok to pass store to the helpers

**Comment by jmurphyau** [comment]
So should serializerFor return as a helper? I thought this issue was more about the fact serializerFor is no longer a helper but serializerForAdapter remained as a helper - rather than passing the store to the helper

**Comment by Chun-Yang** [comment]
Can some one explain why we need *adapter.serializer* in * serializerForAdapter*?
It is not documented. And it is not used in rest-adapter(serializer is not defined) or fixture-adapter(serializer is null).

Shouldn't the serializer for typeKey always take precedence?

Why not remove serializerForAdapter and only use serializerFor?

**Comment by jmurphyau** [comment]
@Chun-Yang I sorta wondered the same thing but didn't question it. I've just had a quick look and essentially removing `serializerForAdapter` doesn't appear to fail any tests either..

    export function serializerForAdapter(store, adapter, type) {
      return store.serializerFor(type);
    }

**Comment by Chun-Yang** [comment]
@jmurphyau I think this function is forgotten by someone at some point. Really glad that you documented the behavior of the source code. It would be awesome if you can put your summery into API documentation. :+1:

**Comment by jmurphyau** [comment]
I've found where it originated from..

`adapter.serializer` references first appeared on Sep 01 2013 in [this commit](https://github.com/emberjs/data/commit/c9a1b7552ffaae4cc1212904900d47709477de53?diff=split) - in the `serializerFor` function.. It looks like only on the `FixtureAdapter` ever referenced it (and still does reference it)... In the same commit the `defaultSerializer` property appeared on the `RESTAdapter`.

On Sep 3 2013 in [this commit](https://github.com/emberjs/data/commit/78608005107123d56aa41ff7af88eeb6ae109fff) `serializerFor` and `serializerForAdapter` were split into two functions and we've had `serializerForAdapter` ever since..

Ideally if `adapter.serializer` is only used on the `FixtureAdapter` might be a better idea to implement `defaultSerializer` like the `RESTAdapter` to keep it clearer and a bit more consistent.

**Comment by igorT** [comment]
```
Ideally if adapter.serializer is only used on the FixtureAdapter might be a better idea to implement defaultSerializer like the RESTAdapter to keep it clearer and a bit more consistent.
```
Can somebody check this? Ideally now would be the time to do this change, before 1.0

**Comment by fivetanley** [comment]
> Can somebody check this? Ideally now would be the time to do this change, before 1.0

JSONAPI/REST adapter use this property.

**Comment by fivetanley** [comment]
The method signature seems to have changed to pass the store. https://github.com/emberjs/data/blob/883cf9c/addon/-private/system/store/serializers.js
