### ISSUE TITLE
findAll relationships for nested url structures

### ISSUE THREAD

**Issue by thejameskyle** [emberjs/data#2964]
The [`find()` documentation](http://emberjs.com/api/data/classes/DS.Store.html#method_find) states:

> You can optionally preload specific attributes and relationships that you know of by passing them as the third argument to find.
> 
> For example, if your Ember route looks like `/posts/1/comments/2` and your API route for the comment also looks like `/posts/1/comments/2` if you want to fetch the comment without fetching the post you can pass in the post to the find call:
> 
> ```js
> store.find('comment', 2, {post: 1});
> ```

Because of this I expected `findAll()` to work in a similar fashion:

```js
store.findAll('comment', { post: 1 }); // GET /posts/1/comments
store.find('comment', 2, { post: 1 }); // GET /posts/1/comments/2
```

While this isn't the actual API, I think it makes a lot of sense and helps solve the problem of dealing with nested models.

/cc @wycats

**Comment by beatle** [comment]
Actually findAll is [marked](https://github.com/emberjs/data/blob/v1.0.0-beta.16.1/packages/ember-data/lib/system/store.js#L973) as private method.

So instead of findAll() you should use find() method as described [here](https://github.com/emberjs/data/blob/v1.0.0-beta.16.1/packages/ember-data/lib/system/store.js#L468).

**Comment by igorT** [comment]
If you want to find all comments for a post, you can do a findQuery which store.find('comment', {post:1}) will do. You will just need to make buildUrl pass it inside the url rather than as a query param. Closing this for now, but please do let us know if you run into trouble doing this, this api should be easy to use

**Comment by benoittgt** [comment]
> You will just need to make buildUrl pass it inside the url rather than as a query param

I'm sorry but I've tried since yesterday without success.

**Comment by benoittgt** [comment]
Hey
Finally found the answer. I just have to remove the query params. 

```javascript
export default DS.RESTAdapter.extend({
    host: 'http://www.example.me:3000',
    namespace: 'api/v1/'+store_id,
    buildURL: function (modelName, id, snapshot, requestType, query) {
      var url = [];
      url.push(this.urlPrefix());
      url.push("users/" + query.user);
      delete query.user;  // yep !
      url.push(this.pathForType(modelName));
      if (id) {
        url.push(id);
      }
      return url.join('/') + ".json";
    }
});
```
