### ISSUE TITLE
Store not registered as service for tests

### ISSUE THREAD

**Issue by technomage** [emberjs/data#2994]
Trying to test a component that has the following fails because the service:store is not defined.

moduleForComponent('actor-table', {
  // specify the other units that are required for this test
  needs: ['service:store']
});

**Comment by fivetanley** [comment]
Did this work with `store:main` before?

**Comment by bmac** [comment]
Thanks for reporting this issue @technomage. I've opened a pr at https://github.com/switchfly/ember-test-helpers/pull/39 to try and get the `service:store` automatically registered in tests.

**Comment by bmac** [comment]
Here is a work around I have used while waiting for the above pr to get merged.

```js
import {
  moduleFor,
  test
} from 'ember-qunit';
import { getContext } from 'ember-test-helpers';
import DS from 'ember-data';

moduleFor('service:product', {
  // Specify the other units that are required for this test.
  needs: ['model:product'],
  beforeEach: function() {
    // Register the store as a service. This can go away once
    // https://github.com/switchfly/ember-test-helpers/pull/39 is
    // merged.
    var context = getContext();
    context.container.register('service:store', DS.Store);
  }
});
```

**Comment by bmac** [comment]
@technomage try version `0.3.2` of https://github.com/rwjblue/ember-qunit. It should now automatically register the store as a service when ED is on the page. 

Please note that you should **NOT** include `needs: ['service:store']` because that will override the Ember Data store by attempting to load a module from `app/service/store.js` (or `app/store/service.js` if you are using pods).

**Comment by technomage** [comment]
Thanks.  I will update ASAP.
