### ISSUE TITLE
Inconsistent Model Update on PUT Response

### ISSUE THREAD

**Issue by samcic** [emberjs/data#3005]
Hi guys,

I'm not sure if this is frowned upon, but I'd like to draw your attention to the following...

http://stackoverflow.com/questions/29685653/ember-data-adapter-inconsistent-model-update-on-put-response

I've spent a few hours trying to debug it in the source, but couldn't narrow down exactly where the record's attribute values are concretely updated based on the adapter's resolved object from the PUT. All I can say is that by the time it gets to 'recordDidChange', the record values have the strange behavior described in the SO post (i.e. the string attribute is updated, the boolean one isn't). I've also confirmed that the resolved adapter object has the correct values. Somewhere in between, something "strange" is happening such that the string is set on the record, but the bool isn't.

This behavior is making me think that it might be a bug. If so, I'd hesitantly say that it's a high-priority one.

I'll keep trying to narrow it down. If anybody knows the place in the code where the record values are truly set based on the resolved adapter object (which in this case has both attributes set correctly), please let me know!

**Comment by bmac** [comment]
Thanks @samcic This definatly seems like a bug. I created a jsbin based on you stackoverflow question here: http://emberjs.jsbin.com/jeridusoso/1/edit

@wecc This sounds like a bug you were describing to me recently? Does this look familiar?

**Comment by igorT** [comment]
Yup, this seems like it should be fixed by https://github.com/emberjs/data/pull/2998

**Comment by lindyhopchris** [comment]
I'm seeing something similar - was wondering if it's the same issue?

I have a model on which there's a "status" property that's a string. Only the server can calculate what the status is. To request an update to the status from the client, I set the status string on the model to "refresh" then save to the server. 

I can see in the response from the server that the response contains the newly updated status, but the model in the store isn't updated and the property is left as "refresh".

This has worked fine for me in the past but isn't working now that I'm upgrading to Ember Data 1.0.0-beta.16.1. I was previously on beta 8 (which is why I'm now upgrading!)

To me this sounds like the same bug, but I was wondering if there's a problem with my approach? I have quite a few models where they have computed properties, but the only thing that can compute them is the server - so basically those properties can change each time the server returns the model either directly or in a sideload.

**Comment by wecc** [comment]
Fixed by #3216, closing.
