### ISSUE TITLE
`filter` isn’t making async requests

### ISSUE THREAD

**Issue by henrymazza** [emberjs/data#3049]
That is, the behavior described [here](http://guides.emberjs.com/v1.10.0/models/frequently-asked-questions/) isn’t happening. Instead these two lines of code are equivalent: 

```javascript
// will wait ajax to render template
return this.get('store').filter('post', params, filterFunction);
// will wait ajax to render template
return this.get('store').find('post', params).then(filterFunction);
```
As a workaround the model hook may fire a find and return a filter.

```javascript
// will render template in spite of request
this.get('store').find('post', params);
return this.get('store').filter('post', params, filterFunction);
```

**Comment by bmac** [comment]
This seems like the documentation in the guides is incorrect here. I believe `store.filter` is working correctly here. @igorT can you confirm?

**Comment by wecc** [comment]
I think the official recommendation now that `store.filter()` has been moved into an [addon](https://github.com/ember-data/ember-data-filter) is to use `peekAll` together with a Computed Property as described [here](https://github.com/ember-data/ember-data-filter#i-dont-want-to-enable-this-feature-due-to-its-heavy-churn)

Closing this since it's no longer a bug in ED.
