### ISSUE TITLE
Custom Primary Key attribute never set

### ISSUE THREAD

**Issue by egosapien** [emberjs/data#3114]
I'm not sure if this is just a change to the API, but it worked in previous betas. I have a custom Primary Key "uuid" which is a string attribute on my model objects. Previously this would get automatically set by Ember Data, so I could say

```
model.get("uuid")
```

However, since beta 17, this is never set. I can still access the primary key via "id", but I wasn't sure if this is a bug or just a change in the API. I couldn't see anything in the changelogs, but sorry if I just missed it.

**Comment by fivetanley** [comment]
Can you post a model definition?

**Comment by egosapien** [comment]
Here is a snippet from my serializer
```
export default DS.RESTSerializer.extend(DS.EmbeddedRecordsMixin, {
	primaryKey: "uuid",
...
```
Here is an example model
```var FileNode = DS.Model.extend({
	uuid: DS.attr("string"),
	name: DS.attr("string"),
	contentHash: DS.attr("string"),
	contentLength: DS.attr("number"),
	totalSegments: DS.attr("number"),
	folderUuid: DS.attr("string", {
		transient: true
	}),
	segmentIndex: DS.attr("number", {
		transient: true,
		defaultValue: function () {
			return -1;
		}
	})
});
```

**Comment by egosapien** [comment]
I also tried beta 18 and the behaviour seems to be the same.

**Comment by igorT** [comment]
Hm, so this is kinda tricky, because the desired behavior could change depending on your model definition. 
`primaryKey` usually moves the value of whatever key you had into `id`, and then in your app you can do `.get('id')` consistently even if your api changes. But in this case obviously you would want the `uuid` to work, and we would have to stop you from changing it.  Do you want to submit a test case for this bug? It should be easy to fix, just worried it might be confusing

**Comment by bmac** [comment]
I'm going to close this issue. I don't think this is something Ember Data wants to support going forward. I suspect the old behavior never prevented you from changing `uuid` which could result in the `id` and `uuid` getting out of sync. I would recommend you use a `Ember.computed.alias` if you want this behavior today.
