### ISSUE TITLE
_internalModel is undefined on 'init' of a record.

### ISSUE THREAD

**Issue by martndemus** [emberjs/data#3255]
Testcase: http://jsbin.com/cegapapigo/2/edit?html,css,js,output

```js
DS.Model.extend({
  foo: DS.attr('string'),
  initFoo: Ember.on('init', function() {
    this.get('foo');
  })
})._create();
```

**Comment by sly7-7** [comment]
It's because the model receive it's internalModel after its creation (and obviously after the init method): https://github.com/emberjs/data/blob/master/packages/ember-data/lib/system/model/internal-model.js#L117

setting this internalModel inside the _createCall should do the trick, but I'm almost sure there was a good reason not to do it.

cc/ @wecc @igorT

**Comment by bmac** [comment]
@martndemus what is your use case for creating records using `_create` instead of using the store's apis for creating a record?

**Comment by martndemus** [comment]
@bmac It's just as simple demonstration, I don't actually use `_create`. `_create` is simply used by all the public manners of initializing a record.

**Comment by sly7-7** [comment]
@bmac It seems fair for me as a user to be able to do some things on('init'), like we may be doing in views or controllers.

**Comment by bmac** [comment]
Seems fair. @igorT how do you feel about the idea of passing `_internalModel` in as one of the properties on the object passed into to `_create(...)`?

**Comment by igorT** [comment]
We should have a separate hook as to not to have to guarantee ordering, but @bmac that solution seems ok for now

**Comment by bmac** [comment]
@martndemus We have release Ember Data v1.0.0-beta19.1 with a fix for this issue: http://emberjs.com/blog/2015/06/09/ember-data-1-0-beta-19-1-released.html
