### ISSUE TITLE
Multiple instances of the same model are not isolated

### ISSUE THREAD

**Issue by rhasson** [emberjs/data#3276]
I'm defining a DS.Model object that I then create multiple copies of.  I then attach each of them to different components on the screen.  When the user enters some text into one of the components' input box the same value is updated on all components.  I have a similar issue opened on ember.js side but was told this is related to the prototype chain of the objects created from the same parent.  I made sure that in my component I'm initializing the local variables that I use as the model so that they are not searched for in the prototype.  However, I noticed that the issue is actually with the model created by calling store.createRecord().  If I call createRecord and pass in an object that initializes the attributes everything is fine.  But if I create an empty model (only pass in the model name), then when that model is bound to a component it mirrors the data to all components.

I show this in this jsBin:  http://jsbin.com/mavaxomofi/1/edit?html,js,output
click the create button, type some text in the input box and then click create again.  it will show the same text in both.

Thanks,
Roy

**Comment by bmac** [comment]
Hi @rhasson, Thanks so much for the jsbin. What you are seeing here is a common gotcha with JavaScript prototypes. I'd recommend you checkout this article for some more in depth background then what I will explain below: http://yehudakatz.com/2011/08/12/understanding-prototypes-in-javascript/. 

When Ember creates a class with `.extend` Ember assigns all the properties passed into the extend function onto the object prototype, that gets shared among all instances of the class. This works great for function since they can be created once and shared by every method and it kinda works for values like `1` or `'say'` since they can not be changed. 

However, the gotcha happens when you try to use mutable objects like `{ text: null }` and `{ voice: 'Woman', loop: 1, language: 'en' }`. Then end up appearing to be shared when you modify a property of one of these objects because JavaScript doesn't copy these objects to each record. Instead what it does is notice that the `Ivrsay` record does not have a `verb_attributes` property of its own. So JavaScript checks its parent class and finds  the `verb_attributes` object defined there, it then uses a reference to the `verb_attributes` object on the prototype and updates the shared object. This makes every `Ivrsay` object that is relying on the shared reference to share their state.

One work around for this problem is to assigning complex objects to the `Ivrsay` record in the constructor. 

http://jsbin.com/tubixololi/1/edit

**Comment by rhasson** [comment]
@bmac Thank you.  I did read that article you pointed to and I'm aware of the behavior you described, but I couldn't figure out how to initialize the model objects so that the prototype is not shared.  Thank you for updating the jsBin, I now understand how to initialize the model.  I was not aware this was even possible.

Again, thank you for the detailed and very helpful response.
Roy
