### ISSUE TITLE
Ember Data doesn't respect underscored associationType for polymorphic relationships

### ISSUE THREAD

**Issue by lessless** [emberjs/data#3336]
As ActiveModelAdapter uses snake case as convention, than it must also accept `something_type` for polymorphic associations, along with somethingType, but it doesn't.

Here is an ember-cli project to quickly reproduce this case https://github.com/lessless/test-polymorphic/ 

After cloning change profileType to profile_type in here https://github.com/lessless/test-polymorphic/blob/master/app/mirage/scenarios/default.js and that will cause an error: 

```javascript
Error while processing route: index Cannot read property 'modelName' of undefined TypeError: Cannot read property 'modelName' of undefined
    at ember$data$lib$system$store$$Service.extend.modelFor (http://localhost:4200/assets/vendor.js:126891:22)
    at ember$data$lib$system$store$$Service.extend.recordForId (http://localhost:4200/assets/vendor.js:126285:30)
    at ember$data$lib$system$store$$deserializeRecordId (http://localhost:4200/assets/vendor.js:127407:27)
    at http://localhost:4200/assets/vendor.js:127388:11
    at http://localhost:4200/assets/vendor.js:129298:20
    at Map.forEach.cb (http://localhost:4200/assets/vendor.js:24194:11)
    at OrderedSet.forEach (http://localhost:4200/assets/vendor.js:23987:11)
    at Map.forEach (http://localhost:4200/assets/vendor.js:24198:18)
    at Function.ember$data$lib$system$model$$default.reopenClass.eachRelationship (http://localhost:4200/assets/vendor.js:129297:83)
    at ember$data$lib$system$store$$normalizeRelationships (http://localhost:4200/assets/vendor.js:127384:12)
```

**Comment by igorT** [comment]
@sly7-7 wanna take a look?

**Comment by sly7-7** [comment]
@igorT Sure, will do it tomorrow evening.

**Comment by sly7-7** [comment]
Well, after a quick look, I think I already have encountered this kind of issue. The problem here is that I don't know if we should support this incoming format. Looking at the current test, https://github.com/ember-data/active-model-adapter/blob/master/tests/integration/active-model-serializer-test.js#L267 it seeems like the expected hash is different. 

Also, I think things like `somethingType` is working because [the store explicitely accept it](https://github.com/emberjs/data/blob/master/packages/ember-data/lib/system/store/serializer-response.js#L113)

So, I guess if we want to support `something_type` we should normalize it to `somethingType` here: https://github.com/ember-data/active-model-adapter/blob/master/addon/active-model-serializer.js#L274

@igorT Let me know if this is desired, and in that case if you think my suggestion sounds good.

**Comment by wecc** [comment]
@sly7-7 with the internal format changed to JSON-API, would this be easier to pursue?

This issue should probably be moved to https://github.com/ember-data/active-model-adapter

**Comment by sly7-7** [comment]
@wecc Just let me know if basically the active model serializer should accept `something_type` as a payload, then it could be transformed to `somethingType` that is later normalized here https://github.com/emberjs/data/blob/master/packages/ember-data/lib/system/store/serializer-response.js#L85 
That beeing said, I just wondered if this special case in the store will/should stay.

**Comment by wecc** [comment]
If `something_type` is commonly outputted I think this should be supported TBH. This could be done in several ways though.

The ActiveModelSerializer could normalize `{ something: 1, something_type: 'thing' }` to `{ something: { id: 1, type: 'thing' } }` and it will just work I think.

**Comment by sly7-7** [comment]
@wecc Thanks, I'm closing this, and opening a new one in the active-model-adapter repo. I think I could tackle this tomorrow
