### ISSUE TITLE
Uncaught Error: Cannot re-register: `service:store`, as it has already been resolved.

### ISSUE THREAD

**Issue by MichaelVdheeren** [emberjs/data#3342]
Using 'canary', the following error is displayed:

```Uncaught Error: Cannot re-register: `service:store`, as it has already been resolved.````

I do have a custom store implementation placed under services/store.js

**Comment by igorT** [comment]
cc @bmac

**Comment by MichaelVdheeren** [comment]
This also happens on 1.0.0-beta.19.2 but then it says:

```Uncaught Error: Cannot re-register: `store:main`, as it has already been resolved.```

**Comment by MichaelVdheeren** [comment]
@igorT @bmac, found the issue:

You check if `registry.has("store:main")` and `registry.has("store:application")`, but not if a service:store already exists

**Comment by igorT** [comment]
can you submit a pr with a fix please?

**Comment by MichaelVdheeren** [comment]
https://github.com/emberjs/data/pull/3343

**Comment by bmac** [comment]
Hi @MichaelVdheeren. I want to get a better understanding of what is going on here. 

Defining a custom store in `app/services/store.js` should just work because the resolver favors loading a module from require over manually registered modules.

There are some exceptions to this behavior for example once you've looked up a module it can no longer be re-registered. Do you have any `initializers` or `instanceInitializer` that do `registry.has('service:store')` or `container.lookup('service:store')`?

**Comment by igorT** [comment]
@bmac i believe he is injecting his own store as ('service:store') in an initializer. That shouldnt blow up.

**Comment by MichaelVdheeren** [comment]
@bmac I have an instanceInitializer doing this:

`registry.injection('component', 'store', 'service:store');`

Apart from that I have a file in serves/store extending the default store from ember-data.

**Comment by bmac** [comment]
@MichaelVdheeren I tried to reproduce that setup using a new Ember CLI app and I was unable to reproduce the error.
https://github.com/bmac/service-store-injection-test

I would be surprised if `registry.injection('component', 'store', 'service:store');` is causing the `service:store` to be looked up. Ember Data does a similar inject already with no problems. https://github.com/emberjs/data/blob/master/packages/ember-data/lib/initializers/store-injections.js#L9-L11

**Comment by MichaelVdheeren** [comment]
@bmac I also had an instance initializer which looked up the `controller:application`. I now have added `after: 'ember-data'` to that one. Could that caused the problem (not waiting for ember-data)?

**Comment by bmac** [comment]
Yep that sounds like the issue, looking up `controller:application` causes `service:store` to be looked up because it is injected into all controllers when they are created.

**Comment by bmac** [comment]
I'm not sure what the right solution is here. Returning early if the `service:store` is already resolved like in pr https://github.com/emberjs/data/pull/3343 works when a custom `service:store` is defined in `app/services/store.js` but it will blow up when there is no custom store.

I think the best solution might be for Ember Data to move the registering of `service:store` back into an `initializer` instead of an `instanceInitializer`. This will result in Ember Data using some of the Ember's deprecated APIs in the initializer to support `store:main` and `store:application`. However, the deprecated APIs will not be used with a custom `service:store` and user will not need to worry about having their code run after the `ember-data` instanceInitializer.

@igorT thoughts?
