### ISSUE TITLE
DS.Model eachRelationship descriptors type is a string but should be of type model

### ISSUE THREAD

**Issue by OleRoel** [emberjs/data#3373]
The documentation of [eachRelationship](http://emberjs.com/api/data/classes/DS.Model.html#method_eachRelationship) states that the type attribute in the descriptor is of type DS.Model. With Ember.Data beta 19 the type changed to be a string.

The JS Bin for this issue can be found [here](http://jsbin.com/koyale/edit?html,js,console,output)

**Comment by fivetanley** [comment]
Unfortunately this is a breaking change. Due to some internal refactors, the `eachRelationship` method must return strings because it can be called if it isn't looked up through the store. So docs need to be fixed and you'll have to update your code with something like the following:

```js
function relationshipFor(klass, store) {
  var results = [];
  klass.eachRelationship(function(relationship) {
    results.push(store.modelFor(relationship));
  });
  return results;
}
```

Maybe it's worth adding something to the store that does that? @igorT
