### ISSUE TITLE
Reload linked belongsTo relationship

### ISSUE THREAD

**Issue by jcbvm** [emberjs/data#3426]
This is more a (feature) question than an issue. With all the new changes in 1.13, is there currently a proper way to reload a belongsTo relationship which is defined as link in the parent model? If not, is there any workaround for this?

**Comment by miguelcobain** [comment]
I'm also looking for this.
Previously I could `reload()` a record and its relationships would be updated with what the server returns. Now relationships seem to be ignored.

Any workarounds?

**Comment by wecc** [comment]
I _think_ this should be resolved when #3380 is fixed.

**Comment by pangratz** [comment]
I think this issue can be closed since #3380 has been merged. Also an [initial implementation of references](https://github.com/emberjs/data/pull/3303) has been merged into `master`. Having the `ds-references` feature enabled, a `belongsTo` relationship can be reloaded via `model.belongsTo('family').reload()`.

@jcbvm can you confirm that your use case is handled now?

**Comment by fivetanley** [comment]
I think references is the way to go here.

**Comment by jcbvm** [comment]
Sorry for my late response, this looks really good yes. Will try it soon using the flag to see how it works out in my app. Thanks a lot!
