### ISSUE TITLE
Bad upgrade path from 1.13 to 2.0

### ISSUE THREAD

**Issue by ZebraFlesh** [emberjs/data#3448]
I just upgraded from ember-data beta-19.1 to 1.13.4 and I'm seeing this deprecation:

`The default behavior of shouldReloadAll will change in Ember Data 2.0 to always return false when there is at least one "foo" record in the store. If you would like to preserve the current behavior please override shouldReloadAll in your adapter:application and return true.`

I've figured out that what I want is the 2.0 behavior, so overriding shouldReloadAll to return true is not correct for me. Unfortunately there's no way to achieve the 2.0 behavior in 1.13. So my choice is to either (1) live with a bunch of broken windows or (2) override shouldReloadAll to return true and hope that whoever is working on the code when 2.0 lands will know to undo it. (I won't be working here when 2.0 lands, so I know I'm not the person to make the changes.)

A nice solution would be to call `store.findAll('foo', {reload: false});` and have it invoke the 2.0 path.

**Comment by bmac** [comment]
I think this is a really good point @ZebraFlesh. 

If Ember Data published some a mixins that you could use to opt into the new 2.0 (or old 1.0) behavior by extending your application adapter with the mixin would that be sufficient upgrade path?

**Comment by ZebraFlesh** [comment]
I think that would be fine. A nice way to do that is to have the mixin complain somehow (console, build output?) once the project is upgraded to 2.0. Failing that, maybe some creative naming would work (MimicEmberData2, UpgradePathToEmberData2, etc).

**Comment by adamesque** [comment]
This bit me this morning; I assumed (incorrectly) from the last line of the deprecation notice that doing the opposite of the opt-out path and returning `false` from `shouldReloadAll` would opt me IN to the ED2.0 behavior and allow me to silence the deprecation before upgrading to 2.0.

This kind of deprecation is super problematic, because you can't actually silence it in all cases. It's probably too late to do anything about it now, but I would have preferred to set a flag opting into 2.0 behavior (as opposed to adding a mixin; that solution should be reserved for preserving legacy behavior).

**Comment by bmac** [comment]
I have released 2 plugins to opt into ember data 2.0 behavior from 1.13. Or opt for 1.13 behavior in 2.0 and silence the warnings in 1.13.


https://github.com/bmac/ember-data-1-13-should-reload-behavior

https://github.com/bmac/ember-data-2-x-should-reload-behavior
