### ISSUE TITLE
GraphQL support

### ISSUE THREAD

**Issue by F21** [emberjs/data#3485]
Facebook has released a draft of their graphql specification: https://github.com/facebook/graphql

graphql solves a lot of problems by decoupling the data the client needs from the server side implementation. It would be really awesome if ember-data can support graphql.

**Comment by fivetanley** [comment]
There's nothing stopping this existing it from an addon, and I'd be happy to help anyone who's interested implement it. Here's some reasons we won't be making GraphQL a first-class citizen anytime soon:

* It's a brand new technology. It may be battle-tested at Facebook, but there's no tutorials, guides, conference talks (afaik) about supporting this technology. It currently only has an open-source backend implementation in GraphQL.js for parsing the queries, but no recommendations for creating queries for your database out of the GraphQL queries. It's early days.
* GraphQL is philosophically a bit different than the philosophies driving Ember Data. For example, Ember Data and JSONAPI prefer you to have one representation of a model per id. In GraphQL, you can request the same model in a nested structure multiple times, but each representation may have a different set of fields. GraphQL doesn't currently seem to address whether the record was fully loaded or not (something we're considering introducing a first-class API for, but does not currently exist in Ember Data).
* Nested queries seem great, but can be difficult to fine tune for performance unless you are careful about recursion in your server implementation.
* None of the Ember Data core team works on apps with GraphQL. This makes it difficult for us to support something we don't use and don't have experience with in the real world.

> graphql solves a lot of problems by decoupling the data the client needs from the server side implementation.

I think with some new documentation you will find this is the case with Ember Data as well. One common misconception is that we prescribe what backend technology to use; that's not the case! As long as you are speaking JSON formatted in JSONAPI over the wire, you are free to change the backend stack at any time. JSON isn't Rails or Node specific.

Even if you *don't* follow JSONAPI (many apps don't! that's ok! That's why we have the ActiveModelAdapter and RESTAdapter), which itself is a brand new format, you can munge your incoming request to fit the jsonapi standard.

GraphQL does seem great, but I think the flexibility you're giving your clients you'll end up paying for in operations / backend code until a community comes around it to solve some of these shared problems. 

I'm not trying to knock the GraphQL idea itself; I actually quite like it. I just don't have the expertise or foresight to be able to confidently recommend it to people.

**Comment by tomdale** [comment]
I agree with everything @fivetanley said.

**Comment by stefanpenner** [comment]
> graphql solves a lot of problems by decoupling the data the client needs from the server side implementation. It would be really awesome if ember-data can support graphql.

I was surprised graphql has no support for pagination or ranges of data as part of the initial spec. This is something, we learned the hard way, now JSONApi has it built in by default.

Anyways, It would be cool to see someone implement a GraphQL Adapter.

**Comment by lessless** [comment]
@stefanpenner afaik they look at it from the different point of view. As it is a `query language` so there is no need to add specific pagination recipe in the spec, instead there are pagination-related keywords, such as: `after`, `first`, `before`, `last` which can be applied towards the requested node.

**Comment by QuantumInformation** [comment]
I think its going to be pretty big tech to invest in.

**Comment by jjbohn** [comment]
We just open sourced a beta adapter that we've started putting using in production. Anyone interest d, please try it out and let us know what you think. https://github.com/alphasights/ember-graphql-adapter

**Comment by stefanpenner** [comment]
@jjbohn cool!

**Comment by knownasilya** [comment]
Sweetness @jjbohn, will check it out!

**Comment by buzzware** [comment]
I reckon GraphQL is enough of a leap to replace REST for app development, where client and server are developed together. Later, we'll see GraphQL offered alongside REST for public API's. The main reason is the idea that the front end should determine the response format, as only it knows what fields/records/associations it requires.
Another reason is that I'm tired of seeing each CRUD operation for each resource implemented specifically and inconsistently - very non-DRY. On the backend, having already done something like this, I reckon I can create pundit policy objects for each resource to determine what fields and records are accessible, and have ruby-graphql do the work of responding to queries within the policy constraints. 90% of the backend work would be writing policies, which are highly generic and inheritable.
So I'm pretty confident I'll be using https://github.com/alphasights/ember-graphql-adapter and https://github.com/rmosolgo/graphql-ruby in my next project.

**Comment by jlevycpa** [comment]
@fivetanley I'm thinking about building an Ember integration with the [Apollo](http://dev.apollodata.com/) GrahpQL client. Does your offer above to provide some guidance still stand?

**Comment by jlevycpa** [comment]
Here is a start. I would appreciate any thoughts on the approach.
https://github.com/jlevycpa/ember-apollo

**Comment by helfer** [comment]
@jlevycpa I'm one of the authors of Apollo Client and I'd like to make sure there's a good integration for Ember. 

Are you still maintaining your project? There is also https://github.com/bgentry/ember-apollo-client, and I'm wondering what the differences are between that and your integration. Thanks!

@stefanpenner Is there any interest from the Ember core team to have an official GraphQL integration that could be provided via Apollo Client?

**Comment by jlevycpa** [comment]
@helfer Sorry for the delay. I decided to scrap the project I was building this integration for, so it was never heavily tested or used in production. It looks like the other project you linked is being actively used, so that's probably the better path forward at this point.
