### ISSUE TITLE
DS.EmbeddedRecordsMixin in DS.ActiveModelSerializer duplicates a record

### ISSUE THREAD

**Issue by lessless** [emberjs/data#3501]
So sorry for my english, it's a late evening here and it's broken even more than usual.

App's backend send json that is needed to be transformed before  ember-data can use it, and here how it looks after those transformation: 
```javascript
{  
  "profile":{  
    "first_name":"fsdf",
    "last_name":"sdfsdf",
    "company":null,
    "birthday":null,
    "emails":[  
      {  
        "address":"sdfsdfsdf",
        "id":1,
        "kind":"main",
        "contactable_type":"Profile",
        "contactable_id":1
      }
    ],
    "addresses":[  

    ],
    "id":1
  }
}
```

that is done in the model's serializer extract hook: 
```javascript
export default DS.ActiveModelSerializer.extend(DS.EmbeddedRecordsMixin, {
  attrs: {
    emails: { embedded: 'always' },
    addresses: { embedded: 'always' }
  },
  extract: function(store, typeClass, payload, id, requestType) {
    let profile = normalizeProfile(payload, id),
      profileJSON = requestType == 'findAll' ? { profiles: [profile] } : { profile: profile };
    return this._super(store, typeClass, profileJSON, id, requestType);
  },
});
```
and ```this._super(store, typeClass, profileJSON, id, requestType);```  returns 
```javascript
{
  "company":null,
  "birthday":null,
  "emails":[
    1
  ],
  "addresses":[

  ],
  "id":1,
  "firstName":"fsdf",
  "lastName":"sdfsdf"
}
```
when profile is saved email is duplicated - the second one appears in the store with the exact same properties, but without id.

**Comment by lessless** [comment]
here is reproduce to reproduce https://github.com/lessless/embeddedbug

**Comment by wecc** [comment]
@lessless I think this is due to `serializer:profile` and `serializer:email` (in this case) are using the new and old Serializer API and they doesn't really work together that well (`EmbeddedRecordsMixin` looks up the serializer for the embedded type).

Would you be able to either add `isNewSerializerAPI: true` to your `serializer:profile` or just create an empty `serializer:email`?

If you want to use the new Serializer API in full you can create a `serializer:application` and setting `isNewSerializerAPI: true` in there and have your other serializers extend that one.

Note that the new Serializer API uses `normalizeResponse` instead of `extract`.

**Comment by wecc** [comment]
Additional asserts has been added in #3511 to address this.

**Comment by lessless** [comment]
@wecc that code is pretty messy, because if I tried everything, but the example app is using ember-data 1.0.0-beta.18 and has same issue.
Isn't this because of ember-data doesn't know how to match records in the store with records in reply?

**Comment by wecc** [comment]
Ah, I think you're absolutely right. I didn't read "saved" property. This issue sounds like the one being tracked in #1829.

**Comment by wecc** [comment]
Closing this in favor of #1829.
