### ISSUE TITLE
store.push json:api format does not follow json:api spec

### ISSUE THREAD

**Issue by bfcoder** [emberjs/data#3504]
Here is an example http://jsbin.com/foniho/edit?js,console,output that outputs an error when you try to push a {json:api} formatted payload. It complains that no model is found in the plural.

Ember data is apparently still expecting singular when that clearly is not the format listed on the [json:api](http://jsonapi.org/) site. Nor does https://github.com/rails-api/active_model_serializers send it in the singular as they are following the spec of sending it in the plural.

Thanks!
-bfcoder

**Comment by bmac** [comment]
Hi @bfcoder. As you have discovered the JSON-API format that `store.push` accepts is a little different from the format used by the examples shown on the JSON-API site.

The 2 main differences. The first is the model names must match the model names that are defined on ember (which by convention is singular). The second is the attribute and relationship names must match the attributes and relationship properties defined on the Ember Data model. JSON API recommends these properties be dasherized, however, the Ember convention is for these to be camelCased. 

This is still a valid JSON-API format because the JSON-API spec does not require model names be plural or attributes be dasherized.

Ember Data does think its important that the JSON-API examples work out of the box. The `JSONAPISerializer` that ships with Ember Data is responsible for singularizing the model names and camelCasing the attribute names. 

In theory you should be able to do `store.pushPayload` instead of `store.push` to run the data through the serializer before it gets pushed. Unfortunately, when I tested it in a jsbin http://jsbin.com/zobavo/edit?html,js,console I ran into bug https://github.com/emberjs/data/pull/3506.

**Comment by bfcoder** [comment]
Ahh, I see. Well I had tried tried the 'store.pushPayload' and got that same error and just figured that it didn't accept a JSON-API payload. I'll wait for that fix to be pushed out and continue my upgrade then. :]

So maybe this issue is for the docs to be updated. haha :] Perhaps I'll get a better understanding and submit a PR to update the guides.

Thanks!
-bfcoder

**Comment by iezer** [comment]
:+1:  On this. I've run into the same issue. JSON API should probably take a firm view on whether types should be singular or plural, dasherized or underscored, etc. but people starting with the spec are very like going to match the examples on jsonapi.org, make all their types plural, and then have problems integrating with JSON API.

The [latest blog post](http://emberjs.com/blog/2015/06/18/ember-data-1-13-released.html#toc_internal-format-change-to-json-api) clearly advertises "store.push now accepts JSON API compliant payload." but I don't think it's there yet.

**Comment by bfcoder** [comment]
Most excellent, looks like pushPayload was fixed with 1.13.5. http://jsbin.com/foniho/edit?js,console,output no longer throws an error. Thanks @bmac !
