### ISSUE TITLE
Ember-Data 1.13 application destroy with records in flight

### ISSUE THREAD

**Issue by RyanHirsch** [emberjs/data#3537]
I am having an issue since updating to ember-data 1.13.x from 1.0-beta-18 with my acceptance tests. I have many tests that are testing a route that has a deactivate that sets a flag. This is now causing an issue during applicaiton destory causing a failure with unloading an inFlight record:

```
afterEach failed on visiting valid un-joined poll shows poll: Assertion Failed: You can only unload a record which is not inFlight. `<frontend@model:participation::ember20519:null>`
```

I've also create a SO thread - http://stackoverflow.com/questions/31276312/acceptance-tests-failing-due-to-record-inflight-with-ember-data-1-13-4 with my issue.

**Comment by chrismllr** [comment]
+1

**Comment by RyanHirsch** [comment]
Issue is still present with 1.13.6

**Comment by shicholas** [comment]
I am seeing this issue too after updating to Ember Data v. 1.13.11

**Comment by fivetanley** [comment]
This error means that in your tests something is causing an AJAX request which marks the record as in flight. Usually ember should take care of this, but this is hard to diagnose without looking at the actual app. Usually there are some race conditions the app can cause out of band (using setTimeout, jquery plugin code that doesn't use Ember.run, etc).

**Comment by balinterdi** [comment]
I have the same issue with ED 1.13.13. My code is the following:

```js
// app/controllers/signup/index.js

signup() {
  this.set('displayErrors', false);
  this.validate().then(() => {
    const user = this.store.createRecord('user', this.getProperties('email', 'password'));
    return user.save();
  })
  .then((user) => {
    window.localStorage.setItem(ENV.authTokenName, user.get('authenticationToken'));
    this.transitionToRoute('signup.company');
  })
  .catch((error) => {
    const baseError = error instanceof DS.InvalidError ?
      "Email already taken" : "Couldn't save user";
    this.set('errors.base', baseError);
  })
  .finally(() => {
    this.set('displayErrors', true);
  });
}
```

And the acceptance test that produces the test case is below:

```js
test('Failed signup - Email already taken', function(assert) {
  stubRequest('GET', '/api/v1/session', function() {
    return this.ok({ access_token: 'XXX' });
  });
  stubRequest('POST', '/api/v1/users', function() {
    return this.error(422, { error: "Bad email. Choose another one." });
  });

  visit('/signup');
  fillIn('#user_email', 'wayne@madlibs.com');
  fillIn('#user_password', 'Yawziiop4');
  fillIn('#user_password_confirmation', 'Yawziiop4');
  click('button[type=submit]');

  andThen(function() {
    assert.equal(find('.alert-danger:contains("Email already taken")').length, 1, "Error message is shown");
  });
});
```

In my case, there is no out-of-band XHR, the request to save the record is sent by ED. The error is thrown by the `Ember.run(application, 'destroy');` in the `afterEach` block of the acceptance test module. ED's store tries to unload all records but the user record (the one that was attempted to be saved in the test) is still in the `inFlight` state (more precisely, in the `root.loaded.created.inFlight` state) and that's why the error is thrown. I'd assume ED should push it out of the `inFlight` state when the XHR request comes back (which it does in the above case) so I think this should work properly.

**Comment by kevinyuliawan** [comment]
I'm also experiencing this issue of a record's `currentState.stateName` being `root.loaded.created.inFlight `once a record's `.save()` resolves to its reject function. I did some digging around in the ember-data source code, and it looks like (at least in my situation), when my record's [`errors` object is created](https://github.com/emberjs/data/blob/master/packages/ember-data/lib/system/model/model.js#L357), it doesn't register a handler to respond to a `this.trigger("becameInvalid")` which is [a function that will transition the record to the `root.loaded.created.invalid` state](https://github.com/emberjs/data/blob/master/packages/ember-data/lib/system/model/states.js#L305). The `trigger` is called in [`errors.js`'s `add` function](https://github.com/emberjs/data/blob/master/packages/ember-data/lib/system/model/errors.js#L220). In fact, I believe it doesn't get into the `errors` computed property at all; I set a debugger in my code and it never gets into it. Perhaps something is overriding it and preventing it from being called?

![image](https://cloud.githubusercontent.com/assets/4811553/10250714/87d58438-68fa-11e5-8752-7edd735eb722.png)

If I manually register my own handler by sending the same actions (for example in a `submit` action in a `new` controller): 
```javascript
actions: {
  submit: {
    var self = this;
    this.model.get('errors').registerHandlers(record, function(){
       //responding to this.trigger("becameInvalid") from errors.js
       this.send('becameInvalid');
    }, function(){
        //becameValid
        this.send('becameValid');
    });
    this.model.save().then(function(){
        //success
    }, function(err){
        //will log the correct state of `root.loaded.created.invalid` since we manually registered the handlers above
        console.log(self.model.get('currentState.stateName')); 
    });   
  }
}
```

Since it works when I manually register it, I'm assuming it never gets registered in the first place, and like I said I never hit the debugger in the original call to the `errors` computed property.

**Comment by jcope2013** [comment]
related https://github.com/emberjs/data/issues/3851 https://github.com/emberjs/data/pull/3859

**Comment by sescobb27** [comment]
I'm still having the same issue with ember-data 1.13.14 and ember .1.13.10

**Comment by fivetanley** [comment]
Is this still happening?

**Comment by RyanHirsch** [comment]
We've since changed how our deactivates work and am no longer on that project which originally had the issue. So it is not directly impacting anything I am working on now nor can I easily try to reproduce it.

I don't know about anyone else.

**Comment by backspace** [comment]
I’m laboriously adding acceptance tests to [`travis-web`](https://github.com/travis-ci/travis-web/pull/557) and [getting this error](https://travis-ci.org/travis-ci/travis-web/jobs/135997915) with Ember Data 2.5.2. I’m near the end of my day and can probably figure it out tomorrow, but if you’re looking for an open source instance, there’s one!

**Comment by fiberair** [comment]
+1

**Comment by runspired** [comment]
@backspace you have any more info?

**Comment by backspace** [comment]
Hmm, I should have followed up to my comment, sorry about that.

In my case, it was the result of a failed attempt to save a record in tests. I [updated our mock API](https://github.com/travis-ci/travis-web/pull/557/commits/eb3b2ca30c6ef871046729874faa254997cde049) to return the expected response, including an ID for the newly-created record, and that caused the errors to disappear. I suspect this won’t be generally applicable, but may help a few people.

**Comment by mitchlloyd** [comment]
I ran into this issue today on Ember Data 1.13.4. It was resolved when I upgraded to 1.13.16.

**Comment by runspired** [comment]
@backspace that suggests to me that my suspicion that this is a user-land code bug and not an ember-data bug at this point is correct. However, much like improving the "Backtracking re-render assertion" for glimmer2 has been useful, we could probably do better here to point you to the problem.

cc @wecc

**Comment by backspace** [comment]
Yeah, @runspired, it’s been a while since I debugged this, but IIRC I eventually figured it out by running the test in isolation in Chrome and spotting the true error in the console output. The actual error message was not representing the source of failure. I would think a failure to save would stop a record from being in flight but maybe not…? Anyway, thanks for thinking about improving messaging!

**Comment by WooDzu** [comment]
Same here on recent version
```
Ember | 2.17.0
Ember Data | 2.17.0
jQuery | 3.2.1
```
use case:

```js
actions {
  save() {
    // saving new record fails
    this.get('field').save().catch((e) => this.send('disableDialog'));
  },
  disableDialog() {
    this.get('field').unloadRecord(); // similar result for destroyRecord()
  }
})
```

**Comment by lucacorti** [comment]
I'm experiencing this in FastBoot when attempting a `transitionTo` or `replaceWith` after saving a model in the `redirect` or `beforeModel` hooks.

```
[2018-01-23T13:37:32.633Z][w32759] starting HTTP server
[2018-01-23T13:37:32.640Z][w32759] HTTP server started; url=http://:::3000
DEBUG: -------------------------------
DEBUG: Ember           : 2.18.0
DEBUG: Ember Data      : 2.18.0
DEBUG: Model Fragments : 2.14.0
DEBUG: -------------------------------
```

**Comment by runspired** [comment]
I've added test waiters to help ensure async cleanup is done and async leaks are caught in #5422. Closing this issue because in-flight during destroy is *mostly* a user-land issue. That said, I've noticed it can be very annoying to destroy a test in which some records are still in-flight-by-design (for instance, testing that a save or a destroy fails). We may want to open a new issue for either documenting how to test these scenarios or providing a helper for testing these scenarios.
