### ISSUE TITLE
store.push can't handle top-level JSON API types being plural

### ISSUE THREAD

**Issue by kagemusha** [emberjs/data#3541]
Looking the [jsonapi format](http://jsonapi.org/format/) doc seems top-level types should be plural, yet store.push fails when you pass plurals.

Failure is at the [modelFor call in _pushInternalModel fn in store](https://github.com/emberjs/data/blob/master/packages/ember-data/lib/system/store.js#l1710)

As plurals work fine for store.findRecords, shouldn't they work here too?

**Comment by bmac** [comment]
@kagemusha Try using `store.pushPayload` instead of push. `push` currently expects the top level keys to be singular and the relationship and attribute names to be match the names defined on your record. 

The `JSONAPISerializer` automatically singularizes the type and undasherizes the attribute and relationship names when it runs on the payload returned by `store.findRecord`. 

`store.pushPayload` runs the payload through the serializer before passing it to `store.push`.

**Comment by bmac** [comment]
@wecc Maybe we should assert that ED can lookup the type in `store.push` with a message instructing people to use `store.pushPayload` instead if that fails.

**Comment by kagemusha** [comment]
@bmac thanks, that works.  Thought i read somewhere that pushPayload gonna be deprecated at some point and everything will go thru push in future.  In that the case?

**Comment by wecc** [comment]
@bmac agree, I think we should assert that `type` is found in `_pushInternalModel`

**Comment by kagemusha** [comment]
@bmac @wecc Won't ember data types always be singular?  Why not singularize here instead (or in addition) to the assert?
