### ISSUE TITLE
Non JSONAPI data structure support in Ember 1.13.5 / RESTSerializer no longer working

### ISSUE THREAD

**Issue by zyllorion** [emberjs/data#3572]
My existing RESTAdapter/Serializer API returns data in the structure:
```
{
modelName1{
	id:1,
	something:”something”
}
modelName2{
	id:1,
	somethingElse:”somethingElse”
}
```
and this works fine on 1.0.0-beta.19.2

When updating to 1.13.5 I get deprecation warnings as expected. My understanding is that deprecation warnings should not affect functionality and the code should still work. It doesn’t, it gives this deprecation warning:
```
Error while processing route: my-pod.view.detail Assertion Failed: <boot@serializer:my-model::ember503> is using the old serializer API and expects <boot@serializer:-rest::ember547> it collaborates with to do the same. Make sure to set `isNewSerializerAPI: true` in your custom serializers if you want to use the new Serializer API.
```
Keeping the DS.RESTAdapter seems to work well enough and call the Serializer correctly, the problems seem to be with the serializers, and I have these problem scenarios:

1) When setting isNewSerializerAPI and converting to normalizeResponse the RESTSerializer no longer recognises the format above – it only accepts JSONAPI format (dies with exception looking for a meta property). Writing transforms for the above format to JSONAPI seems laborious and should be unnecessary as it is a common use-case.
2) Leaving the code as is but using JSONSerialiser removes errors, leaving only minor deprecations for normalizePayload and getById, but loads no data into the model.  I can see the data being processed and returned by normalizePayload correctly so I guess the data structure is not recognised.

It is not cost effective to rewrite all API’s as JSONAPI, how can I  keep the old code working but support JSONAPI for future developments?

**Comment by wecc** [comment]
Are you using the `EmbeddedRecordsMixin`? The warning above is due to the fact that serializers collaborates with other serializers when extracting embedded records and they are not both on the same (old/new) Serializer API.

All serializers that are looked up (as in not defined/customized by you) automatically opts into the new Serializer API.

To solve this you can opt into the new Serializer API (`isNewSerializerAPI: true`) or define empty serializers for your other models. I recommend the new Serializer API though.

Both the RESTSerializer and JSONSerializer will handle converting their respective payloads to JSON API format for you, you should not have to do this manually.

```js
export default DS.RESTSerializer.extend({
  isNewSerializerAPI: true,

  normalizeResponse: function(store, primaryModelClass, payload, id, requestType) {

    // TODO: Custom modifications here

    // Calling _super() will convert the payload to JSON API
    return this._super(store, primaryModelClass, payload, id, requestType);
  }
});
```

Do note that `normalizeResponse` is called with both "array" and "single" responses. You can override `normalizeArrayResponse` or `normalizeSingleResponse` if you only want to do modifications to specific scenarios.

Also, if you want to do modifications to the part of your payload representing a single record, you should use `normalize`.

```js
export default DS.RESTSerializer.extend({
  isNewSerializerAPI: true,

  normalize: function(modelClass, resourceHash) {

    // TODO: Custom modifications here

    // Calling _super() will convert the resource's hash to JSON API
    return this._super(modelClass, resourceHash);
  }
});
```

JSON API is only used as the internal representation of your data and all the built-in serializers supports doing all of this work for you.

Let me know if you still encounter issues related to this and feel free to ping me in the Ember Community Slack.

**Comment by zyllorion** [comment]
Hi, thanks for the very detailed response, much appreciated.

I'm using EmbeddedRecordsMixin as you say, which sounds like it is probably the cause of the problems.  My data structures are all multi-level nested, so I'm stuck with it as a requirement.

For the modifications I need to process the whole data payload in one go, so normalizeResponse seems the way to go, which does seem to work up until the EmbeddedRecordsMixin issue when I tried what you suggest above (although there's no examples in the docs/forums with what (if anything) to return/_super call).

Should there be a compatibility version/configuration of the mixin for <1.13 implementations?

**Comment by wecc** [comment]
When you opt into the new Serializer API the Ember Data Store expects to get a JSON API Document back. This means a JSON object with primary data located in `data` (single object or an array of objects) and possible sideloaded resources located in an array in `included` (this is where the `EmbeddedRecordsMixin` puts embedded recods). A full JSON API Document has to be returned from your serializer's `normalize()` and `normalizeResponse()` methods.

When you call `_super()` in these methods the built serializers automatically converts the payload to a JSON API Document. Here's an example of what a JSON API Document might look like: http://jsonapi.org/format/#document-compound-documents

But, remember, **before** you call `_super()` you should treat the format of the payload as the format the serializers expects. **After** you call `_super()`, the payload has been converted to a JSON API Document.

**Comment by zyllorion** [comment]
Thanks for that, it had all the information I need and is now working good on 1.13.6
The following link also helped for RESTAdapter support:
http://emberjs.com/blog/2015/06/18/ember-data-1-13-released.html#toc_json-api-adapter-default
