### ISSUE TITLE
Add a method for normalizing a payload instead of a single resource

### ISSUE THREAD

**Issue by jonkoops** [emberjs/data#3605]
I am building a Service that takes care of authenticating a user in my application. The Service does a request to the API, normalizes the data, pushes and gets the record from the store and resolves with said record of an authenticated user.

The issue I am encountering is that there is no way to normalize the payload without manually stripping the `data` hash from the root of the server response. This is because `store.normalize()` accepts only a single resource and not a payload like JSON API where the type and primary data is known. The Service now needs to know what the format of the payload is because the API response needs to be modified, which means that if the API response changes this code will break.

After some discussion with @wecc and @igorT a suggestion popped up that it might be an idea to add a `normalizePayload` method which should take an optional `modelName` parameter  to determine which serializer will be used and a `inputPayload` argument to pass the payload (much the same as [store.pushPayload](http://emberjs.com/api/data/classes/DS.Store.html#method_pushPayload)).

*Current situation:*
```js
var payload = store.normalize('user', response.data);
var record = store.push(payload);
```

*Proposed solution:*
```js
var payload = store.normalizePayload(response); // Or optionally store.normalizePayload('user', response);
var record = store.push(payload);
```

**Comment by fotinakis** [comment]
I think I just hit the same thing you described—it looks like `store.push` only normalizes the JSON API primary data, not included resources, so relationships included with my user object die, for example: `"No model was found for 'subscriptions'` (because `subscriptions` in the JSON API response does not get normalized to `subscription` in ember-data internals).

I was sort of able to get this to work as a workaround, though with a bunch of deprecation warnings:
```javascript
var userId = payload.data.id;  // Grab now because pushPayload modifies the hash.
store.pushPayload(payload);
var userRecord = store.peekRecord('user', userId);
```

To fix this, shouldn't `store.push(payload)` normalize compound documents by default?

**Comment by wecc** [comment]
> I think I just hit the same thing you described—it looks like store.push only normalizes the JSON API primary data

Just for the record, `store.push` expects fully normalized data, it does no normalization on it's own.

**Comment by fotinakis** [comment]
Ah makes sense—let me reframe then, shouldn't `store.normalize` normalize full compound documents by default?

I'd expect this to work: `store.push(store.normalize('user', payload))` but that also fails with the above `No model was found for 'subscriptions'` error because the compound resources are not normalized.

**Comment by wecc** [comment]
I'd say that's exactly the issue :) `store.normalize` only normalizes a single record/resource but in this scenario we want to normalize a full payload AND return the result when pushing it. There's currently no good way of doing that.

**Comment by fotinakis** [comment]
Hah got it—after that and reading a bunch of the ember-data source, I see now that the OP was asking for exactly that all along. :) A `normalizePayload` would solve all of this.

**Comment by sly7-7** [comment]
Closing, since https://github.com/emberjs/data/pull/3838 was closed too, and if I understand well, store.pushPayload() (with the `ds-pushpayload-return` flag enabled), does exactly what is requested here. Please reopen if I'm missing something

**Comment by jonkoops** [comment]
@sly7-7 Looks good to me. Thanks for checking up on this issue.
