### ISSUE TITLE
EmbeddedRecordsMixin strips links

### ISSUE THREAD

**Issue by davewasmer** [emberjs/data#3637]
It seems that the EmbeddedRecordsMixin strips any `links` information found on the incoming payload. For example, if I have the following payload:

``` js
{
  data: {
    type: "book",
    id: 1,
    relationships: {
      reviews: {
        data: [ { /* embedded review record */ }, { /* embedded review record */ }, ... ],
        links: {
          related: "/books/1/reviews"
        }
      }
    }
  }
}
```

The embedded records found under the `data.relationships.reviews.data` make in into the store just fine, but the relationship link is not saved. This results in individual API calls per record when I attempt to iterate over the array, rather than a single `GET /books/1/reviews`.

It seems like [this method](https://github.com/emberjs/data/blob/v1.13.8/packages/ember-data/lib/serializers/embedded-records-mixin.js#L608) might be the culprit. I've paraphrased the method here to demonstrate:

``` js
function _newExtractEmbeddedHasMany(store, key, hash, relationshipMeta) {
  // hash.data.relationships[key].links exists at this point
  let hasMany = hash.data.relationships[key].data.map((embeddedRecord) => {
    // move the embedded record to hash.included ...
    return { id, type };
  });
  // hash.data.relationships[key].links is blown away
  set(hash, `data.relationships.${key}`, { data: hasMany });
}
```

I think a fix would be something as simple as changing the last line to:

``` js
set(hash, `data.relationships.${key}.data`, hasMany);
```

But I'm not sure if blowing away the links is the intended behavior, and I'm just misunderstanding how to use the mixin. Happy to submit a PR if my above suggestion is on the right track.

**Comment by pixelhandler** [comment]
@davewasmer I've heard some say that the Embedded records mixin may not yet be compatible with the JSON API adapter/serializer. This appears to be one of those cases. Just curious, this issue has been open for awhile. Any chance this is working now?

**Comment by runspired** [comment]
Thanks for the report, I recently fixed tons of `links` issues but missed this one. I suspect it'll be low hanging fruit :)

**Comment by runspired** [comment]
Generally speaking most of the issue here is that EmbeddedRecordsMixin is meant to be used with the RESTAdapter, it was never meant to work with the JSONAPIAdapter, that it happens to somewhat work is a function of the implementation overlap between these adapters, but folks wishing to add this behavior to a JSON:API response would be way better off implementing their own normalization and serialization. We've added great API docs around serializer customization [which you can find here.](https://api.emberjs.com/ember-data/release/modules/@ember-data%2Fserializer)

Not sure why I didn't point this out back in 2018, but I'm going to close this for that reason.
