### ISSUE TITLE
1.13.9 Can't delete hasMany models

### ISSUE THREAD

**Issue by dmagunov** [emberjs/data#3668]
Model

``` coffeescript
deleteData: ->
  #Following code delete model but leaves related (hasMany) records
  @destroyRecord()    

  @get('children_ids').then (childrens)->
       #Following code always leaves one random record
       childrens.invoke('deleteRecord')

       #Following code throws error "Cannot read property 'deleteRecord' of undefined"
       childrens.forEach (child)->
          child.deleteRecord()


```

**Comment by wecc** [comment]
@dmagunov sorry for the late response – are you still having this issue? Would you be able to reproduce it?

**Comment by sly7-7** [comment]
I think I've reproduced: https://ember-twiddle.com/056a1a1c274794821c7a862146e8a06f?openFiles=controllers.application.js%2C

I think the problem is when invoking directly from the relation, the many-array is mutated during the iteration. Calling to array is a workaround. I don't if we can do better...

**Comment by runspired** [comment]
Calling `toArray` in this situation is the right thing to do.
