### ISSUE TITLE
Extending DS.attr getter/setter

### ISSUE THREAD

**Issue by rmachielse** [emberjs/data#3708]
Would it be possible to be able to change the default get/set method for DS.attr?

I would like to be able to modify an attribute before it is being set on the model (and events are fired).
This is comparable to DS.Transform, however transforms are only used during (de)serialization.

I can do this with an observer as well, however that will fire the set event twice since I have to set it again with the modified version.
Also, I could use a second property with get and set methods that use the original attribute, but I think there should be a cleaner approach, like the following:

```
Product = DS.Model.extend({
  price: DS.attr('number', {
    set: function(value) {
      if (typeof(value) === 'string) {
        return value.replace(',', '.');
      } else {
        return value;
      }
    })
  }
});
```

Another maybe even cleaner option would be to extend DS.Transform with get and set methods so I could do:

```
Product = DS.Model.extend({
  price: DS.attr('price')
});

PriceTransform = DS.NumberTransform.extend({
  set: function(value){
    if (typeof(value) === 'string) {
      return value.replace(',', '.');
    } else {
      return value;
    }
  }
});
```

Anyone else interested in this idea?

**Comment by leimig** [comment]
It does look interesting. I'm definitely interested.

**Comment by leimig** [comment]
It does look interesting. I'll try to modify the DS.attr to support that this weekend. I'll update this post once I have news about it.

**Comment by rmachielse** [comment]
Thanks!

**Comment by leimig** [comment]
Hi @rmachielse, sorry about the delay. These last couple weeks were crazy :P About this thread, I just submitted the Pull Request https://github.com/emberjs/data/pull/3789. Hope they will accept :)

**Comment by bmac** [comment]
The Ember Data team does not think it is the right approach for solving the problem of transforming data before assigning it to an attribute because it requires user code to be aware of all the type that may be set on an attribute and requires the user code to handle the correct transformation without knowing where the value is originating from.

A better solution may be to: 
- Transform the data closer to the input source where there is more context. One example of this approach for data bound values is @rwjblue's [one-way-input twiddle](http://ember-twiddle.com/2d7246875098d0dbb4a4) which sanitizes the user input in the component. 

- Or use a computed property to transform the attribute's value and data bind to the computed property instead of the original attribute.
