### ISSUE TITLE
unloadRecord() acts weirdly on subsequent calls

### ISSUE THREAD

**Issue by ghost** [emberjs/data#3738]
I'm having issues with the slight delay caused by unloadRecord() on subsequent calls.

If this issue isn't known already I'm happy to submit a PR with a failing test in order to reproduce first.

Very kind regards,
Manuel

**Comment by fivetanley** [comment]
`unloadRecord` is supposed to just unload the record (remove it from the store's cache) but not talk to the server. So if this is not happening synchronously I would say this is a bug.

**Comment by mkorfmann** [comment]
I will change the title then first things first.

**Comment by mkorfmann** [comment]
Steps to reproduce (not real ember code, just for clarification):

1.) unloadRecord(firstRecordOfLoadedCollection)
2.) transitionTo(firstRecordOfLoadedCollection [this would be the second record though, since actual first is unloaded, works as expected)
3.) repeat 1.)
4.) repeat 2.) => doesn't work, i.e. first records are the same, although actual first should have been unloaded

**Comment by mkorfmann** [comment]
Should I take a stab at writing a reproducing test case?

**Comment by fivetanley** [comment]
Sure! that'd be great. It looks like there are some tests for unload in this file: https://github.com/emberjs/data/blob/79de9316f82445c7e86dd932e880d98daaeb12b6/packages/ember-data/tests/integration/records/unload-test.js

**Comment by mkorfmann** [comment]
Which branch should I be working on? Master?

**Comment by mkorfmann** [comment]
So far no luck with reproducing, maybe it's the bigger picture causing the bug.

The record being unloaded is also the model of the controller in which it's being unloaded. Could that be a probable cause for the issue?

**Comment by mkorfmann** [comment]
Hm, maybe I reproduced the issue now, but I'm not quite sure.

I will make a PR and you decide...

**Comment by mkorfmann** [comment]
Or I'll just post the test-case as a gist first, so you can tell me if you'd expect this to work or if I just misused the testing utilities.

https://gist.github.com/mkorfmann/5a3d64b1a9bbca3f0868

**Comment by mkorfmann** [comment]
BTW: Could improve my hacky solution in the project where the error is occurring by wrapping the `unloadRecord()` call in an `Ember.run` function.

So `unloadRecord()` seems to have asynchronous side-effects.

**Comment by mkorfmann** [comment]
I guess I also found the problem: `unloadRecord` triggers two nested `Ember.run.schedule('actions')` actions.

1.) in `InternalModel#updateRecordArraysLater` (called from `InternalModel`'s `transitionTo` function)
2.) in `Store#recordArrayManager.recordDidChange` (called from `Store`'s `dataWasUpdated`)

Since these functions should probably not be modified to fix this bug I see 2 options:

1.) making `unloadRecord` return a Promise
2.) wrapping `unloadRecord`s `transitionTo` call in an `Ember.run` function

I'd be eager to implement the fix, I'm just unsure which option is right (or if these options are even considered workable).

Most kindest regards,
Manuel

**Comment by wecc** [comment]
@ManuelArno sorry for the late response, do you know if this issue is still present in recent Ember/Ember Data versions? I couldn't access the gist-links :(

**Comment by ManuelArno** [comment]
The updated gist as mentioned in https://github.com/emberjs/data/issues/3738#issuecomment-139015400:
https://gist.github.com/ManuelArno/fbd15a2082d9139b3fc2

**Comment by ManuelArno** [comment]
The updated gist as mentioned in https://github.com/emberjs/data/issues/3738#issuecomment-139030779: 
https://gist.github.com/ManuelArno/fbd15a2082d9139b3fc2

**Comment by runspired** [comment]
I'm not certain how to reproduce the original bug, and we've made so many improvements and simplifications to unloadRecord over the years it is highly unlikely this is still an issue. If it is, please reopen <3
