### ISSUE TITLE
JSONSerializer.serializeHasMany() behaves differently depending on the way the record has been added to the store

### ISSUE THREAD

**Issue by sebweaver** [emberjs/data#3760]
Here is a JSBin highlighting the two behaviors: http://emberjs.jsbin.com/rocano/8/edit?js,console,output

On the first case (post added by `createRecord`) the json is:
```javascript
{ comments: [] }
```
On the 2nd case (post added by `push`) the json is:
```javascript
{ comments: undefined }
```
Shouldn't be the same (i.e. the 1st one)? Or is it by design to have undefined relationships on the 2nd one?

**Comment by wecc** [comment]
Thanks for reporting!

The bug is here: https://github.com/emberjs/data/blob/master/packages/ember-data/lib/serializers/json-serializer.js#L1127

`snapshot.hasMany()` returns `undefined` for "unknown" relationships ([docs](http://emberjs.com/api/data/classes/DS.Snapshot.html#method_hasMany)). That is, you've pushed the record into the store, but the relationship is missing. ED cannot know if there's additional data on the server or not, that's why there's a "unknown" state of a relationship. We wouldn't want to serialize unknown relationships to `[]` because that might overwrite server state.

When you do `store.createRecord()` we consider the record as new and client-side and because of that all the relationships are known (which means `snapshot.hasMany()` returns an empty array instead of `undefined`)

The `JSONAPISerializer` handles this correctly, see https://github.com/emberjs/data/blob/master/packages/ember-data/lib/serializers/json-api-serializer.js#L428-L429

**Comment by sebweaver** [comment]
First of all thank you for your quick and detailed answer. I've noticed the difference between the two serializers, but I didn't know whether it was on purpose or not. With your explanation it's now clear.

Thanks

**Comment by wecc** [comment]
I would still consider this a bug. Unknown relationship should be omitted when serializing records using `JSONSerializer` (and `RESTSerializer`).

**Comment by sebweaver** [comment]
I've created a PR: https://github.com/emberjs/data/pull/3765

**Comment by Kuzirashi** [comment]
Shouldn't this be closed because of #3765 merged?
