### ISSUE TITLE
Ember-Data does not respect queries at all

### ISSUE THREAD

**Issue by elwayman02** [emberjs/data#3761]
Ember-Data literally takes in a query and then immediately throws it away without doing anything with it, causing API calls to be made without any query params. See below:

```
/**
   * @method urlForQuery
   * @param {Object} options
   * @param {String} modelName
   * @return {String} url
   */
  urlForQuery: function(query, modelName) {
    return this._buildURL(modelName);
  },
```

This method needs to pass the query to `_buildURL`, and `_buildURL` needs to know what to do with it.  This is a major regression from 1.13.x, I believe.  I'm also not entirely certain this is the only method that throws away params like that.

**Comment by bmac** [comment]
You are correct. This looks like a regression introduced by this commit https://github.com/emberjs/data/commit/fd3d5dd1a3de415e36051c44ed389339a62c46a7.

**Comment by wecc** [comment]
I don't think this is entirely true. `query` is passed to `ajax()` in the `query` method of the `RESTAdapter` and added to the AJAX call, see [here](https://github.com/emberjs/data/blob/v2.0.0/packages/ember-data/lib/adapters/rest-adapter.js#L416-L424). Same goes for `queryRecord`. I suspect this might have something to do with the `sortQueryParams` feature but I'm not sure.

I'm not saying the current behavior is the preferred one but the title of this issue is a bit misleading.

**Comment by elwayman02** [comment]
@wecc For a `GET` request, the query should be built into path params, which is not happening now. The query does not get added to the URL at all, which means the API will never receive the expect path params. As far as I'm concerned, that's a regression.

**Comment by wecc** [comment]
@elwayman02 if you do `this.store.query('author', { page: 1 })` Ember Data will, by default, request `GET /authors?page=1`. Are you saying this is not the case?

**Comment by elwayman02** [comment]
Aye, that's the issue I was having that led me to dig into how the URL was being built.

**Comment by elwayman02** [comment]
Seems to be working now, not sure why.
