### ISSUE TITLE
Clean up Stale Branches

### ISSUE THREAD

**Issue by sandstrom** [emberjs/data#3797]
50+ branches make the branch-selector noisy (and the repository in general).

Perhaps the stale ones could be removed?
https://github.com/emberjs/data/branches/stale

**Comment by bmac** [comment]
I just went through and cleaned out all the stale branches that have already been merged into master. There are still a lot of other stale branches but I don't feel comfortable deleting them since most were created by someone other then me. Maybe @igorT can review some of the older (1 year +) branches and make a call on their usefulness?

**Comment by btecu** [comment]
Considering the huge refactor at 1.13, probably most old branches are not relevant anymore.

**Comment by wecc** [comment]
@igorT can you have a look at the stale branches and remove the ones you know are not needed anymore? https://github.com/emberjs/data/branches/stale

**Comment by stefanpenner** [comment]
I pruned branches we could obviously delete
