### ISSUE TITLE
Replace hasMany relationships fails

### ISSUE THREAD

**Issue by IsaiahJTurner** [emberjs/data#3833]
Doing something like: 
`ama.set("questions", [Question, Question, Question]);`
does not work.

**Comment by pangratz** [comment]
Can you give a little bit more information? What version are you using? What does the model definition for `ama` look like? Best would be a reproduced example in a JSBin. Here is a starting point: http://emberjs.jsbin.com/lavacavige/edit?html,js,output

**Comment by bmac** [comment]
Relationships are more complex object then an array so its not possible to set the relationship property directly. Instead can use the [setObjects](http://emberjs.com/api/classes/Ember.MutableArray.html#method_setObjects) method on the relationship. 
`ama.get("questions").setObjects([Question, Question, Question]);`

**Comment by bmac** [comment]
My bad @IsaiahJTurner. 

@pangratz reminded me that there is special code to handle the case of setting an array: https://github.com/emberjs/data/blob/fcf54523b4b9f87e403baa5a1c73af0486914936/packages/ember-data/lib/system/relationships/has-many.js#L146-L152

What is the error that you are seeing?

**Comment by IsaiahJTurner** [comment]
I made a JSBin: http://emberjs.jsbin.com/xemunezoki/edit?html,js,console,output

**Comment by pangratz** [comment]
OK, so the problem is that `store.findRecord` returns a `PromiseObject`. This can't be added directly to a hasMany relationship. The `findRecord` resolves with the specific record, which in turn can be added to the relationship.

One way to do this is via `RSVP.all`, which takes an array as argument and resolves when all items in the array are resolved. So the code within your action [would become something like](http://emberjs.jsbin.com/ciyefi/1/edit?html,js,output):

``` js
update: function() {
  var newBooks = [
    this.store.find("book", 4)
  ];

  var model = this.get('model');
  Ember.RSVP.all(newBooks).then(function(newBooks) {
    model.get('books').setObjects(newBooks);

    // or you can use model.set('books', newBooks);
  });
}
```

---

The thrown error message `Uncaught TypeError: Cannot read property 'type' of undefined` when setting a `PromiseObject` is not very helpful. We could add an assertion below [this line](https://github.com/emberjs/data/blob/fcf54523b4b9f87e403baa5a1c73af0486914936/packages/ember-data/lib/system/relationships/has-many.js#L149) and check if the contents of the array are actual instances of `DS.Model`.

@IsaiahJTurner do you want to submit a PR?

**Comment by pangratz** [comment]
I guess this issue can be closed since an assertion for only passing instances of `DS.Model` has been added in #3865.
