### ISSUE TITLE
Making requests through `ember-ajax`

### ISSUE THREAD

**Issue by taras** [emberjs/data#3849]
[ember-ajax](https://github.com/ember-cli/ember-ajax) has been around for a couple of months now and it's now part of ember-cli's app blueprint. 

I'd like to open the discussion about what's necessary to make it possible to use it instead of RESTAdapter's and JSONAdapter's built in `ajax` method.

I imagine that there are probably quiet a few apps out there that've done some unexpected things in the adapter. 

As far as I know, Ember Data is not currently relying on any libraries(other than Ember) that are not packaged with it. 

**Questions**
1. What objections are there to making this change?
2. How do we allow users to opt-in to use the Ajax Service?

**Comment by btecu** [comment]
If I remember correctly, the addon was at least initially based on code from Ember Data so this proposal is probably a good idea.

I think it would be nice to get an `ajax` service for free when Ember Data is present. Most of the time there is a specific request that works better with an ajax call instead of through Ember Data.

**Comment by igorT** [comment]
@tomdale has thoughts on this

**Comment by taras** [comment]
Closing in favour of https://github.com/emberjs/data/issues/4175
