### ISSUE TITLE
Add error code to model.errors

### ISSUE THREAD

**Issue by khomyakov42** [emberjs/data#3992]
I would like to have access to the error code in the error list model. like this
`
   model.get('errors').add('username', {message: 'Username is required', code: 'required' })
   model.get('errors.username').objectAt(0).get('message') // Username is required
   model.get('errors.username').objectAt(0).get('code') // required
`

**Comment by igorT** [comment]
cc @tchak

**Comment by tchak** [comment]
I am :+1: on the principle. Right now `.add()` takes as second argument a string or an array of strings. We need to handle object or array of objects on top of it. Not a breaking change, so fine with me. JSON-API also defines `code` (not to confuse with http `status`) on the error object, so we could expose it.

**Comment by runspired** [comment]
This information is retained in the errors list in the cache if using JSON:API formatted errors and the (default) JSON:API cache. It may be exposed on errors now due to this (not super sure, the logic for the Errors class is complicated), but since we do not intend to make any changes to `@ember-data/model` or its `errors` API anymore I'm closing this.
