### ISSUE TITLE
DS.Model#isNew does not notify observers when saving a new record

### ISSUE THREAD

**Issue by lcoq** [emberjs/data#4020]
The `isNew` value changes but does not notify observers when saving a new record. 
On the other hand the `id` property properly notify its observers.

[See this EmberTwiddle](https://ember-twiddle.com/6ec437cab388294f99ea)

```js
 Ember.Controller.extend({
  newPost: Ember.computed(function() {
    return this.store.createRecord('post', { name: 'foo' });
  }),
  
  newPostIsNewChanged: Ember.observer('newPost.isNew', function() {
    console.log('newPost.isNew changed');
  }),

  newPostIdChanged: Ember.observer('newPost.id', function() {
    console.log('newPost.id changed');
  }),
  
  actions: {
    saveNewPost() {
      let post = this.get('newPost');
      post.save().then(function() {
        console.log('newPost saved');
      });
    }
});
```

Trigger the `saveNewPost` results in this in the console:

> newPost.id changed
> newPost saved

**Comment by fivetanley** [comment]
Hey  there, it looks like there was maybe a copy/paste error from the Ember Twiddle URL. Can you update the first post and then make another comment when it's updated and I'll look at it asap?

**Comment by lcoq** [comment]
@fivetanley hi! The Ember Twiddle link looks correct and works for me in a private browsing session. Do you still experience the issue ?

**Comment by fivetanley** [comment]
I guess Ember Twiddle's redirect isn't working in Safari, but it works in Chrome.

**Comment by stefanpenner** [comment]
This is working as expected, please use computed properties observers are for low level patterns typically for pushing data out of ember into 3rd part systems like jQuery or D3

**Comment by fivetanley** [comment]
This is not working as expected. The state change should still fire after the save call.

**Comment by fivetanley** [comment]
in test form: 

```javascript
test("a new record's isNew property changes to false after a successful save", function(assert) {
  const post = env.store.createRecord('post');
  
  return post.save().then(=> {
    assert.equal(post.get('isNew'), false);
  });
});
```

**Comment by bmac** [comment]
In Ember Data `isNew` is a computed property. Because it is never consumed by an `record.get('isNew')` or interpolated in a template Ember tries to be smart and save some work by never evaluating the `isNew` property. In Ember, observers are lazy so they don't proactively consume the computed property. So as far as Ember is concerned there is nothing to observe because the values of the `isNew` property is unknown. 

I believe this is working as intended. The workaround is to consume the `isNew` property somewhere to force it to get evaluated. You can do this with `record.get('isNew')` a setup method like `init` or if the observer method itself uses performs a `record.get('isNew')`  you can use a `.on('init')` to kick of an initial run of the observer.

Lastly, I would encourage you to checkout [this video](https://www.youtube.com/watch?v=vvZEddrClAQ) by @stefanpenner where he explains some of the hazards of `Ember.observer` and suggests some alternate approaches.
