### ISSUE TITLE
Saving a record removes associations locally

### ISSUE THREAD

**Issue by thejbsmith** [emberjs/data#4067]
I have an Ember app using the jsonapi adapter, with a Rails backend using the jsonapi-resources gem.

In my ember app, I create a record (with an association), then save the record, and then try to interact with the record. At this point, the association is no longer available locally and must be pulled from another request.
Although the association is no longer available locally, the answerId attribute is available locally and has been set correctly since this is just an attribute instead of an association.
```
let answer = ...;

let surveyAnswer = store.createRecord('survey-answer', {
  ...
  answer: answer,
  ...
});

// surveyAnswer.answer is properly set here

surveyAnswer.save()
.then( function(result){
  // result.answer is not available locally and another request must be made to retrieve the answer
}, function(error){
  ...
});
```

This Ember app has a very large dataset, so we are trying to minimize requests as much as possible. We have not set up a backend controller to handle an Answer, since they are expected to be side-loaded wherever they are needed.

In this instance, why does the returned result no longer have a an answer associated with it? Am I missing something here? Does the save call to the server need to somehow specify what to include when the result is returned?

-------------------------------

Ember      : 2.2.0
Ember Data : 2.2.1
jQuery     : 1.8.3

-------------------------------

**Comment by pangratz** [comment]
Hey @thejbsmith, I cannot follow your issue completely. Can you provide an ember-twiddle with your use case? You can use this as a starting point: https://ember-twiddle.com/5817e4de262287286b52?openFiles=models.survey-answer.js%2Capplication.route.js

**Comment by thejbsmith** [comment]
@pangratz, take a look here: https://ember-twiddle.com/80bb122657d2c82101e5?openFiles=initializers.pretender.js%2Capplication.route.js.

The only addition I added was the relationships on the returned json data when creating the survey-answer. This mocks the jsonapi data for this particular request. Since the relationships are returned, but only include `relationships.links` instead of `relationships.data`, another request is made to `/survey-answers/1/answer` in order to try and retrieve the answer. The console logs this as an unhandled request.

In most apps, you could simple have `/survey-answers/1/answer` in place and make the additional call, but in our app that would make a ton of additional requests, when the answer was already known before it was saved. Due to this, we have not set up that endpoint, as we don't want to make the additional requests. Now, **IF** the `relationships.data` attribute is present on the returned json for creating a survey-answer (instead of just the `relationships.links` attribute), then this works as expected. But this creates an issue with the jsonapi specs, where if you want any included items (which would populate `relationships.data`), you have to include the `includes` query string to the request, or else you just get the `relationships.links`. Since `surveyAnswer.save()` does not include the `includes` query string when firing the request, there does not seem to be a way to include the data needed in this situation.

**Comment by fsmanuel** [comment]
@thejbsmith @pangratz I'm not sure if we experience the same thing but I also lose relationships:

I have the situation that when I destroy a child record in a 1:N relation and then save the parent record I lose all the child records I just created. If I create the childs and reload the page they don't get removed but new once do...

You can see it in action: http://www.funkensturm.com/statuspage/#/settings

Check DNSimple and wait for the features to load
Then check Website, API, Sandbox API und uncheck Sandbox API
Only Website remains...

Relavant code: [destroyRecord](https://github.com/funkensturm/statuspage/blob/feature/settings/app/components/feature-select.js#L45) and [save](https://github.com/funkensturm/ember-local-storage/blob/master/addon/adapters/adapter.js#L79-L86)

**Comment by pangratz** [comment]
@thejbsmith the problem is when a `survey-answer` gets saved, the `answer` relationship is returned as a link. And since the link hasn't been requested yet, accessing the `answer` fetches the link. There is currently no way in ember-data to know / to specify that the previously set `answer` is the same as specified with the link... except by additionally providing a `data` for that relationship. See the relevant code [here](https://github.com/emberjs/data/blob/v2.3.3/addon/-private/system/store.js#L2162-L2172).

So the `answer` relationship is considered as loaded, you could return a minimal payload for this relationship:

```js
// POST /survey-answers
{
  data: {
    type: "survey-answer",
    id: 1,
    relationships: {
      answer: {
        links: {
          related: "/survey-answers/1/answer",
          self: "/survey-answers/1/relationships/master-answer" 
        },
        data: {
          type: "answer",
          id: 1
        }
      }
    }
  }
}
```

If this is not possible with your API - also I don't know if this is encouraged at all by the JSON-API spec - you could overwrite `normalize` of your `survey-answer` serializer and manually set the minimal `data` entry for the `answer` relationship.

If you want to go the `includes` approach, you could make use of the `options` hash you can pass to `record.save()`, which are available on the snapshot via `snapshot.adapterOptions`. This allows you to overwrite `Serializer#urlForCreateRecord` so `includes` is added to the url. It looks like this is OK in terms of JSON-API, see http://jsonapi.org/format/#fetching-includes:

> Note: This section applies to any endpoint that responds with primary data, regardless of the request type. For instance, a server could support the inclusion of related resources along with a POST request to create a resource or relationship.

This would look something like this, [see this updated twiddle](https://ember-twiddle.com/7db2eed0eabc99de29f4?openFiles=adapters.survey-answer.js%2Capplication.route.js):

```js
// app/adapters/survey-answer.js
import JSONAPIAdapter from "ember-data/adpaters/json-api";

export default JSONAPIAdapter.extend({
  urlForCreateRecord: function(type, snapshot) {
    let url = this._super(...arguments);
    
    let includes = snapshot.adapterOptions.includes;
    if (includes) {
      url = `${url}?includes=${includes}`;
    }
    
    return url;
  }
});
```

And then this would be used like this:

```js
var surveyAnswer = this.store.createRecord('survey-answer', {
  answer: firstAnswer
});

// POST /survey-answer?includes=answer
surveyAnswer.save({
  adapterOptions: {
    includes: "answer"
  }
})
```

---

@fsmanuel I haven't had time to look at your sample. The problem of the lost relationship described by @thejbsmith is because there is (currently) no way for ember-data to know that the locally available record is the same as specified via a link.

**Comment by fsmanuel** [comment]
@pangratz I changed the example and will remove my comment above. It's no longer relevant.

**Comment by pangratz** [comment]
@fsmanuel did you solve your issue?

**Comment by fsmanuel** [comment]
@pangratz no but it was to hard to track down and I couldn't reproduce it in a twiddle. If I run into it again I'll open a new issue. Anyway thanks for asking.

**Comment by pangratz** [comment]
@fsmanuel :+1:

**Comment by pangratz** [comment]
> There is currently no way in ember-data to know / to specify that the previously set answer is the same as specified with the link...

@thejbsmith you need to take my statement with a grain of salt; I may have misunderstood inverse records here. It looks like this is related to #4099...

**Comment by thejbsmith** [comment]
There seems to be a difference in how relationships are handled in different situations.

For Example:

**Saving a Record**
```
let surveyAnswer = store.createRecord('survey-answer', {
  ...
  answer: answer,
  ...
});

surveyAnswer.save
// Returns only relationship links
```
`surveyAnswer.get('answers')` does not return any answers.
When the data is received from the server, the relationships are wiped out and set to what was returned by the server.

**Fetching Records**
```
let originalSurveyAnswer = store.query('survey-answer', { filter: { id: 1 }, include: 'answers' } );
// Returns relationship links and data

let newSurveyAnswer = store.findRecord('survey-answer', 1);
// Returns only relationship links
```
`newSurveyAnswer.get('answers')` does return answers.
When the data is received from the server for originalSurveyAnswer, the answers are included by links and data, so the answers are available.
When the data is received from the server for newSurveyAnswer, only the relationship links are provided. BUT since the answers were already associated by the call for originalSurveyAnswer, newSurveyAnswer does have answers.

It seems that on save calls, the relationship data is replaced with what is returned by the server, but on fetch calls the relationship data is merged with what is returned from the server.

Why are the relationships handled differently in each of these situations?

**Comment by thejbsmith** [comment]
Also, @pangratz, :+1: for the solution to overwrite the create url. I believe that would work in our situation. 

Depending on the answer to my previous comment, that may be the way for us to go.

**Comment by pangratz** [comment]
> When the data is received from the server for originalSurveyAnswer, the answers are included by links and data, so the answers are available.

> When the data is received from the server for newSurveyAnswer, only the relationship links are provided. BUT since the answers were already associated by the call for originalSurveyAnswer, newSurveyAnswer does have answers.

This is because the link isn't changing, see [this code here](https://git.io/vgQes): if the link doesn't change, then the code which would mark the relationship as "not yet fetched", isn't run.

> Why are the relationships handled differently in each of these situations?

Currently the state returned by the server represents the truth. IMHO this makes sense, but I can see how this is problematic for cases where a relationship is acknowledged by the server as a link (which hasn't been fetched yet) and the record referenced by the link is already loaded locally. The `link <--> loaded record` is difficult to determine.

---

If I understand `JSON:API` correctly, [Resource Linkage](http://jsonapi.org/format/#document-resource-object-linkage) is the thing we are talking about here?

> Resource linkage in a compound document allows a client to link together all of the included resource objects without having to GET any URLs via links.

**Comment by pangratz** [comment]
@thejbsmith It has been a while. I really think that Resource Linkage helps in your case.

Please feel free to reopen if you disagree and think that this is still an issue.

Thanks!
