### ISSUE TITLE
BuildUrlMixin.urlPrefix() regression

### ISSUE THREAD

**Issue by oligriffiths** [emberjs/data#4105]
Noticed a regression on this line: https://github.com/emberjs/data/commit/b5028e617c2f4513b42e88b5ec70649706587f58#diff-391afb21553f5f403d61beaf437459c0R232 

On `2.3` this trims the leading `/` https://github.com/emberjs/data/blob/v2.3.2/addon/-private/adapters/build-url-mixin.js#L234

However the new refactor doesn't. 

Thus:

 ```
path = /path/to/endpoint
host = /
result = //path/to/endpoint
```

previously it would return `/path/to/endpoint`

**Comment by bmac** [comment]
Hmm, I'm surprised a `host` with a value of `/` worked in 2.3 since I assumed it would get pushed into the array and joined with a slash a the end of the function. https://github.com/emberjs/data/blob/v2.3.2/addon/-private/adapters/build-url-mixin.js#L250

```
path = /path/to/endpoint
host = /
result = ['/', '/path/to/endpoint'].join('/') = //path/to/endpoint
```

either way this seems like a bug that should be fixed.

**Comment by oligriffiths** [comment]
A / is stripped off the path, thus making a correct path without the //.

**Comment by oligriffiths** [comment]
awesome! thanks
