### ISSUE TITLE
findRecord always fetches record, even if it is in the store

### ISSUE THREAD

**Issue by jbryson3** [emberjs/data#4109]
I noticed when doing a findRecord(model, id) that my application would make a request for it even if that record was already loaded in the store. I traced it back to the behavior in store.js where it checks to see if the record was cached and if it is, check the adapter to see if it should fetch in the background anyway

https://github.com/emberjs/data/blob/master/addon/-private/system/store.js#L533-L536

    // Trigger the background refetch if all the previous checks fail
    if (adapter.shouldBackgroundReloadRecord(this, snapshot)) {
      this.scheduleFetch(internalModel, options);
    }

The default behavior of the vanilla adapter says, yes, always fetch it in the background.

https://github.com/emberjs/data/blob/master/addon/adapter.js#L515-L517

  shouldBackgroundReloadRecord(store, snapshot) {
    return true;
  },

I don't understand why refetching in the background an already stored record is the default behavior.  I seem to recall back in the 1.13 days, that the default behavior was to 'trust' the cache.  Thanks!

**Comment by bmac** [comment]
Hi @jbryson3. This behavior was changed in Ember Data 2.0. 

The new behavior is if there is a record in the store, a `store.findRecord(model, id)` request will resolve the promise immediately with the cached record. It will then make a request in the background in case the store's cached representation has gone stale.

This behavior was chosen as the default because.
1. Making an ajax request for every `findRecord` is more in line with the mental model for developers coming from server-rendered and jQuery backgrounds.
2. Resolving the cached record and making the request in the background  preserves the speed of client-side navigation. Once data for a record is cached, transitioning to any route that relies on it is nearly instantaneous and has no network bottleneck.

This default may not make sense for every application. For example if you are displaying immutable data (like a tweet) the background request may be wasteful so you can customize the behavior by overriding the `shouldBackgroundReloadRecord` and `shouldBackgroundReloadAll` in your application or model specific adapter.

For more information check out the motivation and discussion sections in this RFC https://github.com/emberjs/rfcs/blob/master/text/0061-ember-data-background-fetch.md#motivation
