### ISSUE TITLE
access ajax content before parsing

### ISSUE THREAD

**Issue by sebyx07** [emberjs/data#4136]
Is there a way to override how the store makes get/post request? i use base64 to compress the json and I need to inflate/deflate the content ?
Now I use plain ajax request and push the payload into the store

**Comment by bmac** [comment]
Hi @sebyx07. You can override the `findAll`, `findRecord`, 'updateRecord', 'createRecord' methods on your [Adapter](http://emberjs.com/api/data/classes/DS.RESTAdapter.html) to change how the ajax request is made. Also be sure to check out the [Customizing Adapters guide](https://guides.emberjs.com/v2.3.0/models/customizing-adapters/) for how to include a custom adapter in your app.

**Comment by sebyx07** [comment]
i just override the ajax(), had to uncompress they payload
https://gist.github.com/sebyx07/306465253092f325337e
now the adapter works for other models too

**Comment by pangratz** [comment]
Hey @sebyx07, I was just looking at your gist and if I am not mistaken, you don't need to overwrite the `ajax` method as a whole. If you overwrite [`handleResponse`](https://github.com/emberjs/data/blob/v2.3.0/addon/adapters/rest.js#L739) of the adapter, your compression should work:

```js
export default DS.RESTAdapter.extend({
  handleResponse(status, headers, payload) {
    payload = uncompressToJSON(payload);

    return this._super(...arguments);
  }
}
```

In the gist you patched the `parseResponseHeaders` function too because of there was a bug when the header value contains a `:`. This has been fixed in #4137 so the patch isn't needed anymore.

---

Can you confirm that this works for you and close this issue if it does?

**Comment by pangratz** [comment]
@sebyx07 can this issue be closed?

**Comment by sebyx07** [comment]
yes, ty

**Comment by pangratz** [comment]
:+1:
