### ISSUE TITLE
Base Serializer#normalizeResponse refers to JSON-API

### ISSUE THREAD

**Issue by JackCA** [emberjs/data#4140]
I'm trying to use the base Serializer class and am attempting to implement a custom `normalizeResponse` function.

However, I'm about confused about [this part of the docs](https://github.com/emberjs/data/blob/883cf9c0ebe18277b1c8fab2381fe46eacfb13d9/addon/-private/system/serializer.js#L40-L54) that indicates that a `JSON-API Document` should be returned from this function.

Is this documentation correct? I would assume a more generic object type could be returned from a serializer that doesn't inherit the JSON-API serializer.

**Comment by fivetanley** [comment]
A JSONAPI document is merely a plain-old JavaScript object that has a format mirroring the JSONAPI specification.

That means it looks like:

```javascript
{
  data: {
    id: 1,
    type: 'blog-post',
    attributes: {
      name: 'Rails is Omakase'
    }
  }
}
```

While technically correct, I agree that the docs are confusing here. If anything, it should be in the description where the markdown is rather than as a YUIDOc return type. The correct YUIDoc return type here is `Object`. It'd be great if the documented return type could see an update. :)

**Comment by wecc** [comment]
@JackCA Ember Data uses JSON API internally so the documentation is correct in that your serializer should return a JSON API Document.

Please note that the internal Ember Data JSON API format differs slightly from the recommendations at jsonapi.org and the format used by Ember Data's `JSONAPIAdapter` / `JSONAPISerializer`.

The internal Ember Data JSON API format:

- uses camelCased attributes and relationship members
- uses singular types instead of plural

**Comment by JackCA** [comment]
@fivetanley @wecc you guys are awesome, thank you. I didn't realize that Ember-data relied internally on the JSON-API document specs, but they are easy enough to emulate.

We can close if you guys think there aren't any actionable changes.

**Comment by wecc** [comment]
:+1:
