### ISSUE TITLE
Adapter not coalescing requests when ids contains ":"

### ISSUE THREAD

**Issue by engwan** [emberjs/data#4190]
We're on ember data 2.3. And our ids are in the format: `USER:1234556789`

When I have `users: [1, 2, 3]` in my model, loading the async relationship correctly coalesces them into one request with the `ids` param.

But when I have `users: ['USER:1234567890', 'USER:686234234']`, the models are requested individually.

Is this a bug? Probably caused by a URL encoded character?

We can't really easily change the id format because this is for a legacy system.

**Comment by pangratz** [comment]
Okay, this is tricky: the problem is that `lastSegment` needs to be `decodeURIComponent`ified [here](https://github.com/emberjs/data/blob/v2.3.3/addon/adapters/rest.js#L666), before it is compared with the `id` of the snapshot. The reason is that `lastSegment` represents the the `encodedURIComponent`ified version of the `id` (this happens [here](https://github.com/emberjs/data/blob/v2.3.3/addon/-private/adapters/build-url-mixin.js#L97)).

So the comparison is `"USER%3A1" === "USER:31"` which lets the condition evaluate to `false` and hereby the URL for coalescing is not correctly "calculated".

I couldn't come up easily with tests which test this and the other case where the URL is something like `/model?id=xxx`. I hope that I will have time soon to fix this.

In the meantime I can't think of another way than to monkey patch your adapters' `_stripIDFromURL` until this is fixed upstream in ember-data:

```js
// adapters/application.js
import RESTAdapter from "ember-data/adapters/rest";

export default RESTAdapter.extend({

  _stripIDFromURL(store, snapshot) {
    var url = this.buildURL(snapshot.modelName, snapshot.id, snapshot);

    var expandedURL = url.split('/');
    //Case when the url is of the format ...something/:id
    var lastSegment = expandedURL[expandedURL.length - 1];
    var id = snapshot.id;

    // monkey patch warning
    if (decodeURIComponent(lastSegment) === id) {
      expandedURL[expandedURL.length - 1] = "";
    } else if (endsWith(lastSegment, '?id=' + id)) {
      //Case when the url is of the format ...something?id=:id
      expandedURL[expandedURL.length - 1] = lastSegment.substring(0, lastSegment.length - id.length - 1);
    }

    return expandedURL.join('/');
  }

};
```
