### ISSUE TITLE
JSONapi - Embedded relationship in sideloaded does not work

### ISSUE THREAD

**Issue by bodinsamuel** [emberjs/data#4212]
Hello,

_DEBUG: Ember      : 1.13.6
DEBUG: Ember Data : 1.13.7
DEBUG: jQuery     : 2.1.0_

I'm trying to use ember data with embedded relationship in sideloaded relation.
But sadly I'm not able to make it works. I wonder if it's not a bug ?
I'm respecting the jsonapi.org schema that allow this kind of behaviour.

To illustrate I want to do this
```js
// quiz
export default DS.Model.extend({
    questions: DS.hasMany('question'),
}):
// question
export default DS.Model.extend({
    answsers: DS.hasMany('answer')
});
// answer
export default DS.Model.extend({
});
```

The data I want to load
https://gist.github.com/bodinsamuel/3fed336ba7d5eaac4ca0

Ember Data, correctly register my models (I can see the answers loaded in the ember extension)
but the answers are not linked to question.
I can display my questions linked to my quiz, but not my answer.
As if ember data ignore the second level of sideloading
Or maybe I did something wrong?

Thanks a lot

**Comment by fivetanley** [comment]
Hi, thanks for opening an issue. A few things:

* Can you try updating to the latest 1.13 release? I think it's 1.13.16 or 1.13.17.
* The question and answer models don't have any relationships. Ember Data won't create the relationships implicitly so you at least have to add `relationshipName: DS.hasMany()` (or `belongsTo`). Can you try adding those relationships to the model definitions?

**Comment by bodinsamuel** [comment]
Hi,

I thought you Will say that so I already upgraded my entire  Project to (it was Time anyway)
The problem is still here.

My quiz and my question has a relation, the same way question and answer has one.
But i putted them in plural, is it wrong ?
If its wrong, why its working on the first level "quiz.questions" but not on the second "question.answers" ?

I hope I'm explaining myself correctly ☺️

**Comment by bodinsamuel** [comment]
Hi again,
I'm uping this. Still trying to achieve this with no succes

thanks

**Comment by bmac** [comment]
Hi @bodinsamuel. Currently the `JSONAPISerializer` and the `EmbeddedRecordsMixin` do not work together. This is because the today the JSON API spec doesn't specify how an embedded record should be formatted so there is no way for Ember Data to implement this now without risking a backwards incompatible change in the future. There is an [active issue](https://github.com/json-api/json-api/issues/795 ) on the JSON API repo that discusses this problem. 


I have also [opened a pr](https://github.com/emberjs/data/pull/4259) against Ember Data to warn when `JSONAPISerializer` and `EmbeddedRecordsMixin` are combined to make this limitation more clear in the future.
