### ISSUE TITLE
json-api serializer not updated to work with pushPayload return

### ISSUE THREAD

**Issue by rwwagner90** [emberjs/data#4323]
Seems like the feature flag `'ds-pushpayload-return'` was enabled for store.js, as `pushPayload` now returns things.

However, the json-api serializer doesn't seem to have picked up on the flag being enabled, so the return does not work. Note missing a return in this output:

```js
 pushPayload: function pushPayload(store, payload) {
      var normalizedPayload = this._normalizeDocumentHelper(payload);

      store.push(normalizedPayload);
    },
```

**Comment by pangratz** [comment]
`ds-pushpayload-return` is not yet enabled in the latest release [v2.5.1](https://github.com/emberjs/data/blob/v2.5.1/config/features.json#L5), since there are some concerns about performance implications which need to be resolved first. You can currently use this feature in `canary` channel, by explicitly enabling it.

**Comment by rwwagner90** [comment]
Oh okay @pangratz. It appeared to be enabled in store.js and not in the serializer, so I thought there was a disconnect somewhere. I will use canary for now.
