### ISSUE TITLE
Normalizing query objects via adapter; viable options

### ISSUE THREAD

**Issue by bttf** [emberjs/data#4326]
We are trying to normalize query params, namely the object keys in the query object, in our adapter. Using ember/ember-data 2.4, JSONAPIAdapter.

It seems like overriding `sortQueryParams` is the best way to do it since 1) it's called by both `query` and `queryRecord` and 2) it is called after `buildURL` so buildURL does not handle already-transformed object keys. [reference](https://github.com/emberjs/data/blob/v2.5.1/addon/adapters/rest.js#L458)

But semantically it doesn't make much sense to override `sortQueryParams` for a normalization operation. Perhaps replace with a `normalizeQueryParams`, or the like, that by default, would sort.

Overriding both `query` and `queryRecord` would semantically make more sense, but then we run into the problem of `buildURL` receiving an already-transformed query object, which may imply handling the transformed version of our query object in our code (for us, this is definite since we are using url templates).

**Comment by grapho** [comment]
I can get behind this
I would volunteer to PR if others feel it is useful

**Comment by runspired** [comment]
After discussion, the issue here is not that you can't but rather that the soup of methods available on RESTAdapter and JSONAPIAdapter prevents clarity around the best way to do so. RFCing yet another method to these adapters would only increase the confusion around what hook to use when and what order they are called in.

Closing with a preference for either introducing a new adapter built over the MinimumAdapterInterface or other design proposals which simplify the request management story.
