### ISSUE TITLE
DS.Store.findAll adapterOptions v2.2

### ISSUE THREAD

**Issue by goofiw** [emberjs/data#4329]
in order to pass adapter options, I have to pass an object with the name adapterOptions.
i.e.

`this.store.findall('my-model', {adapterOptions: {waka: 'waka'}}`

from the api it looks like I should be able to just pass {waka: 'waka'}

**Comment by wecc** [comment]
The second argument to `store.findAll()` is `options`. `adapterOptions` is one available option and needs to be wrapped.

Do you have an example of where in the API it looks like you should be able to just pass the `adapterOptions` without wrapping them? We should definitely improve the docs if this is unclear.

**Comment by pangratz** [comment]
@goofiw just in case you are asking on why it is needed to pass all the options for the adapter into `adapterOptions: { ... }`: the options for the adapter need to be placed into `adapterOptions` because not all properties in the passed hash are intended for the adapter. By specifying `store.findAll('my-model', { reload: true })` for example, you can tell ember data the specific reload behavior. The `reload` option shouldn't be passed to the adapter...

**Comment by bmac** [comment]
I believe this is closed by https://github.com/emberjs/data/pull/4405 where the documentation for adapterOptions has been updated.
