### ISSUE TITLE
null model is stored in cache

### ISSUE THREAD

**Issue by trevorrjohn** [emberjs/data#4346]
So I am encountering this issue when using `DS.RESTAdapter` and getting an empty JSON object response when calling `DS.Model#save()`. The API returns an empty object and as expected nothing is stored in the store. However this happens: 

```javascript
DS.Store#findAll('user').get('length') // => 0 (good)
DS.Store#peekAll('user').get('length') // => 1 (bad)
```
The desired outcome would be for both to evaluate to `0`.

When I inspect on the object stored in the cache, every field is `null`. So even calling `unclearRecord` does not work. Calling `unclearAll('user')` does actually remove the cached object, but I don't think this should ever get into this state. I think `peekAll` should return no objects or there should be an error thrown when the adapter tries to parse a response with no `id`.

I created an example project that shows the behavior: https://github.com/trevorrjohn/bad-cached-data

Thanks!

**Comment by pangratz** [comment]
`store.peekAll` returns is a live updating array with _all_ records in the store, which also includes new records which are not yet saved. So I think `store.peekAll()` is working as expected here.

---

I am wondering though why there is no assertion for `save()` returning no data, because this will result in a record having `isLoaded === true` but `isNew === false` and `id === undefined`, as shown in [this ember-twiddle](https://ember-twiddle.com/93ef68ef1c889a0605c1fb22aec165cd?fileTreeShown=false&numColumns=2&openFiles=routes.application.js%2Ctemplates.application.hbs).

**Comment by trevorrjohn** [comment]
Yes, @pangratz narrows down the issue better than my example.
