### ISSUE TITLE
EmbeddedRecordsMixin embeds the record, not the snapshot

### ISSUE THREAD

**Issue by dnachev** [emberjs/data#4366]
On lines:

https://github.com/emberjs/data/blob/v2.5.2/addon/serializers/embedded-records-mixin.js#L364

and

https://github.com/emberjs/data/blob/v2.5.2/addon/serializers/embedded-records-mixin.js#L228

The serialization of the embedded record is done like this:
```javascript
embeddedSnapshot.record.serialize({ includeId: true });
```

This means that instead of serializing the snapshot, the current record is serialized, which may or may not be the correct state.

**Comment by pangratz** [comment]
`DS.Model#serialize` [uses `store.serialize`](https://github.com/emberjs/data/blob/v2.5.2/addon/-private/system/store.js#L222-L225) which in turn uses a snapshot. So I think this should be fine. Are you running into a specific issue/bug here?

The implementation could be improved, since the snapshot needn't be created again. Thanks for pointing that out!

**Comment by dnachev** [comment]
I was probably going a little off the paved road and used snapshots to capture the state of the model at given time and serialized the snapshot to compare them. However, because the mixin was serializing the record rather than the snapshot, it serialized the current state rather than the snapshot state.
