### ISSUE TITLE
Relationship nested within plain object unsupported

### ISSUE THREAD

**Issue by yads** [emberjs/data#4494]
If I have the following JSON:

```
{
  id: 1,
  name: 'primary',
  nested: {
    someValue: 'value',
    related: {
      id: 2,
      name: 'related'
    }
  }
}
```

There is no way to define this relationship. I've tried:

models/model.js
```
export default DS.Model.extend({
  name: DS.attr(),
  nested: DS.attr(),
  'nested.related': DS.belongsTo('model')
});
```
and
serializers/model.js
```
export default DS.JSONSerializer.extend(DS.EmbeddedRecordsMixin, {
  attrs: {
    'nested.related': { embedded: 'always' }
  }
});
```

`nested.related` always evaluates to null. The issue is partially due to [this](https://github.com/emberjs/data/blob/051590bbf4861f081ec83aa4112dd04390bab549/addon/serializers/json.js#L676) as it uses `resourceHash[relationshipKey]` instead of `Ember.get(resourceHash, relationshipKey)` to get the relationshipHash.

**Comment by fivetanley** [comment]
Hi @yads.

Ember Data does not support the `nested.property` syntax for `attr` or `hasMany` or `belongsTo` since existing APIs use periods for other purposes and this could get confusing for APIs and consumers when we mix and match. So if you say `nested.property`, that's what Ember Data will look for.

As a workaround, you'll need to write a custom serializer that moves the data into a shape that Ember Data can work with. For the JSONSerializer, you can move `nested.related` to the top of the object in your payload.

Our goal is to turn your payload into this:

```javascript
{
  id: 1,
  name: 'primary',
  nested: {
    someValue: 'value',
    // related is gone here!
  }, 
   // now related is here!
   'nested.related': {
      id: 2,
      name: 'related'
    }
  }
}

```

```javascript
export default DS.JSONSerializer.extend({
  normalizeSingleResponse: function(store, primaryModelClass, payload, id, requestType) {
    var related = payload.nested.related;
    delete payload.nested.related;
    payload['nested.related'] = related;
    return this._super(store, primaryModelClass, payload, id, requestType);
  }
});
```

You can switch out `payload['nested.related']` with the actual name of the relationship.

**Comment by yads** [comment]
Thanks for the suggestion, I'll try it out. I wound up just moving it into the top level in the api for the moment.
