### ISSUE TITLE
headers being a CP may be a poor choice

### ISSUE THREAD

**Issue by stefanpenner** [emberjs/data#4496]
https://github.com/emberjs/data/blob/c6d233b2ba1408f76d54f850bbe47bf8b2ae6982/addon/adapters/rest.js#L215-L228

Volatile is strange, specifically in a world of templates it has a complex meaning and for this use-case a function instead of a CP would more then likely be what we want.

Other motivation is attempting roll back the concept of `.volatile` some the public API, as most of the time when it is required, it is the source of something else being funky.

cc @krisselden

**Comment by bmac** [comment]
The [ds-improved-ajax](https://github.com/emberjs/data/pull/3099) feature flag (enabled in the current beta) adds a new [headersForRequest](https://github.com/emberjs/data/blob/master/addon/adapters/rest.js#L1320-L1333) method that will become the recommended way to handle this usecase. Users will be encouraged to override `headersForRequest` instead of declaring a `.volatile` computed property.

**Comment by stefanpenner** [comment]
> The ds-improved-ajax feature flag (enabled in the current beta) adds a new headersForRequest method that will become the recommended way to handle this usecase. Users will be encouraged to override headersForRequest instead of declaring a .volatile computed property.

Very awesome. Should we close this issue when:

1. that is enabled by default
2. the docs are updated to encourage the new flow

Or consider it solved, and close it now?

**Comment by bmac** [comment]
I'm in favor of closing this when the docs have been updated to encourage the new flow.

**Comment by runspired** [comment]
As we never landed DS-improved-Ajax and as headers is no longer a volatile property in going to close this.
