### ISSUE TITLE
Deprecation for Ember.Date.parse is showing in new Ember Apps and add-ons with prototype extensions enabled

### ISSUE THREAD

**Issue by juwara0** [emberjs/data#4501]
In PR [#4396](https://github.com/emberjs/data/pull/4396/files) a deprecation notice was introduced that is now showing in new ember apps and new add-ons with prototype extensions enabled.

`ember new <appName>`
`ember serve`

or

`ember addon <addon Name>`
remove `ember-disable-prototype-extensions` from `package.json` and node_modules directory.
`ember serve`

The deprecation will show in the browser console.

I believe the problem is related to `Ember.EXTEND_PROTOTYPES === true` in 
https://github.com/bmac/data/blob/17b1f1c08cfd00ad03940c5593e25d3581c13ad6/addon/-private/ext/date.js#L60

Platform/Ember/Node version:
ember-cli: 2.5.1
node: 5.10.0
os: darwin x64

**Comment by rwjblue** [comment]
FWIW, I think the correct fix is to have the ember-cli new app blueprint include a `config/environment.js` that disables date prototype extension (as mentioned in the deprecation message). 

There is not much that ember-data itself can do, due to backwards compat concerns.  We need to require the user to opt-in to disabling the old monkey patch so we are issuing a deprecation in the case where users have not explicitly opted to disable the monkey patch.
