### ISSUE TITLE
Included null relationships are converted into Ember data models

### ISSUE THREAD

**Issue by dfalling** [emberjs/data#4502]
I'm calling a JSON API endpoint and using the `?include=parent` parameter to pull down that association.  When the parent is null, Ember is still converting it into an Ember data model with undefined properties, forcing me to test `model.get('parent.id') === undefined` to figure out if the parent exists or not.  Shouldn't the `.parent` relationship just be null?

Here's the payload causing my grief:

```
{
      "type":"organizations",
      "id":"4",
      "attributes":{
        "name”:”ACME”
      },
      "relationships":{
        "parent":{
          "links":{
            "self":"/japi/organizations/4/relationships/parent",
            "related":"/japi/organizations/4/parent"
          },
          "data":null
        }
      },
      "links":{
        "self":"/japi/organizations/4"
      }
    }
```

**Comment by swquinn** [comment]
I've experienced something similar, but using an extension of the standard REST adapter on Ember Data 2.8.0 and Ember CLI 2.8.0. I don't remember having this problem previously, but can't say for certain. I'm using embedded records, and notice that when the JSON data for a property which would normally be embedded returns `null`, the actual value is a record with its content set to `null` rather than simply being a `null` value itself.

This breaks conditionals like `if (!foo)` because foo is not `null` or `undefined` but an object that wraps the `null` value.

**Comment by dfalling** [comment]
That sounds exactly like my issue as well.

**Comment by pangratz** [comment]
I cannot reproduce this behavior, see [this ember-twiddle](https://ember-twiddle.com/ed7775aa15dbe7336b685bc2476bbd60?fileTreeShown=false&numColumns=3&openFiles=routes.application.js%2Cmodels.person.js%2Ctemplates.application.hbs).

Keep in mind that by default relationships in ember-data are async, so you need to check the resolved value of the promise you get:

```js
organization.get("parent").then((parent) => {
  if (parent) {
    // we have a parent
  }
});
```

**Comment by pangratz** [comment]
It seems that this has gone stale, so I am closing. Feel free to reopen ideally with a failing test case / ember twiddle, in case this is still happening. Thanks!
