### ISSUE TITLE
RestAdapter does not allow to set the XHR withCredentials flag

### ISSUE THREAD

**Issue by saerdnaer** [emberjs/data#4563]
The current REST XHR implementation in https://github.com/emberjs/data/blob/16cf35db2aa0ddbe28c043570ef6d725139b0c47/addon/adapters/rest.js#L1332-L1357 does not support APIs which require client certificates. 

The old way was to override the ajax method, and set `hash.xhrFields = { withCredentials: true };` (compare http://stackoverflow.com/a/32864639 ) but overriding the ajax method is now deprecated.

Side node: Acually, in some browsers which do not correctly implement the specification  (e.g. Chrome 53), APIs requiring client certs still work – however this is a bug.
- https://bugzilla.mozilla.org/show_bug.cgi?id=1019603#c9
- https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS#Requests_with_credentials

**Comment by CrshOverride** [comment]
@saerdnaer - I had the same issue. After looking at the source, I was able to override the `_requestToJQueryAjaxHash` private method as a workaround until a proper solution is proposed:

```javascript
  _requestToJQueryAjaxHash(request) {
    let hash = this._super(request);
    hash.xhrFields = hash.xhrFields || {};
    hash.xhrFields.withCredentials = true;
    return hash;
  }
```

**Comment by wecc** [comment]
Until https://github.com/emberjs/rfcs/pull/171 is a reality I think [`jQuery.ajaxSetup`](https://api.jquery.com/jquery.ajaxsetup/) or [`jQuery. ajaxPrefilter`](http://api.jquery.com/jquery.ajaxprefilter/) is the best option.

**Comment by runspired** [comment]
We removed the `ds-improved-ajax` feature that was the focus of RFC 171 because ultimately the RFC failed to address a number of issues around providing enough context to adequately build out requests.  We're currently working on a new request concept to replace both that RFC and the existing adapter API to resolve these limitations.  In the mean time, hooking into either `Adapter.ajax` or `Adapter.ajaxOptions` is usually  the best bet for customization of this nature.
