### ISSUE TITLE
Fastboot

### ISSUE THREAD

**Issue by mxrguspxrt** [emberjs/data#4565]
How Ember Data supports Fastboot, how adapter should be changed to support it and could documentation improve in that sense?

**Comment by bmac** [comment]
Hi @mxrguspxrt. Fastboot has support for Ember Data built in. If you use the `RESTAdapter` or `JSONAPIAdapter` or if the adapter you are using extends one of these 2 adapters its likely you adapter will work out of the box with fastboot. There is also an addon that can be used with ember data and fastboot to serialize the state of the store from the fastboot server down to ember data so record do not need to be re-requested. https://github.com/ember-fastboot/ember-cli-fastboot

@mxrguspxrt Where did you look to find if Ember Data supports Fastboot? I'll admit the documentation could defiantly be improved.

**Comment by mxrguspxrt** [comment]
Thank you for the response!

Got ember-cli-fastboot working.

1. HTML page is rendered correctly, but some actions do not work. (I think that is because only one if-else block is loaded on rendertime - and I should have both them HTML and use CSS for switching what is visible.)

2. When JS resources are loaded, all page is re-rendered.


(I am using active-model-serializers, so I think that might be the issue. Will edit the post if gotten it fully working to share my experience - hopefully it helps someone.)

**Comment by locks** [comment]
> When JS resources are loaded, all page is re-rendered (and resources reloaded from REST), what is kind of disturbing.
There are two solutions being worked on, unrelated to Ember Data. One is that the end goal for FastBoot is to re-hydrate the current page and take it from there instead of re-rendering. The second is shoebox which @bmac mentioned, a library to serialize application state into the DOM so it can then be loaded without network requests.

I am closing this issue as Ember Data itself seems to be functioning properly. Feel free to reach us in Slack and in the FastBoot repositories!
