### ISSUE TITLE
Make `allowNull` default for `DS.attr('boolean')` in 3.0

### ISSUE THREAD

**Issue by sandstrom** [emberjs/data#4571]
@pangratz made a great enhancement here: https://github.com/emberjs/data/pull/4022

I would be happy with either of (1) removing the option (string and number transforms has no option) or (2) flip the default value of the option to `true`.

This would make this transform consistent with string, number etc. where no option is required to allow null. Since it's a breaking change we must wait until 3.0.

**Comment by aars** [comment]
Booleans in DB context are often misused, with people expecting NULL and False to equate, etc. IMHO the `allowNull` default should be `false`. Using ternary booleans should be a conscience decision by the developer.

**Comment by bmac** [comment]
I can understand the desire to have consistency around the default for `allowNull` however I'm concerned about the cost of switching the default will result in more pain then the benefits of increased consistency.

Right now we don't have a good way to switch default other then logging a warning in the 2.x version then switching in 3.0. Some of the feedback from the 2.x release with changing the defaults for async relationships was painful since you couldn't effectively address the change until you were on the next major release (unlike a deprecated method where you could replace a deprecated method with the new api before bumping the major version).

**Comment by sandstrom** [comment]
You could start logging in a 2.x version released at the same time as 3.0, that would present a clear path. Or simply skip logging and mention it as a breaking change.

This is a small change, after all. Async relationships affected basically all models, where as this will affect a smaller amount of models.

**Comment by rwjblue** [comment]
Sorry for letting this sit so long! I think in general, we want to be moving away from transforms conceptually (because they add complexity in general and could easily be replaced directly in the serializer itself).

Again, sorry for the delays, but I don't think we are going to move this direction so I'm going to go ahead and close this issue...
