### ISSUE TITLE
everything on the model in the documentation is defined under -private ..

### ISSUE THREAD

**Issue by spruce** [emberjs/data#4744]
... which for me is the indication that one should not use it. But some methods are definitivly needed. So I assume that is just a problem in the documentation? Is that assumption correct?

**Comment by pangratz** [comment]
Can you give an example of a method which is marked as private but should show up in http://emberjs.com/api/data/classes/DS.Model.html?

**Comment by locks** [comment]
@spruce do you mean that the path of the module contains the `-private` folder?

**Comment by spruce** [comment]
What @locks says. That's a little strange for me.

**Comment by locks** [comment]
Everything you see in the API documentation should be public, except for a bug that shows private modules/namespaces/classes in the table of content.
I'm closing this issue because that's just how the project is organized internally, and I'm not sure how we'd clarify the situation without restructuring the whole project.

@spruce if you have suggestions reach the learning team in the Slack channel, thanks.
