### ISSUE TITLE
PushPayload do not update belongsTo relations

### ISSUE THREAD

**Issue by Exelord** [emberjs/data#4816]
Hey!
Here is a twiddle of the issue with a description: https://ember-twiddle.com/17151235360da0e8b7964fd324fdc299?openFiles=templates.components.push-payload.hbs%2Ctemplates.components.push-payload.hbs

**Comment by hjdivad** [comment]
@Exelord in your twiddle you can `this.get('person.things.length')` in your observer to get the right length.

In your real-world problem is this a solution for you, or is it important that you get the length via `hasMany(relationshipName).ids().length`?

Regarding the observer firing, this is because computed properties are lazy: if you never ask for a computed property, observers won't fire for it.  This is expected (and very much desired) behaviour.

---

Re: Ember-Data peeps, the reason for the above is because the observer is triggered during the `ManyArray`'s `flushCanonical`, which is called before `super.flushCanonical()` within `HasManyRelationship`.

This means that at the time the observer is triggered, `canonicalMembers` is updated, but `members` is not, and it's `members` from which `ids` computes its information.

It's not obvious to me that we actually want to trigger observers before the canonical set is actually flushed.

**Comment by hjdivad** [comment]
cc @igort @runspired

**Comment by Exelord** [comment]
I dont have to. Here is my real case:
I try to call relations `this.get('person.things')` with jsonapi `includes`. So I have sth like

```js
  things: computed('person', function() {
    return this.get('store').query('thing', {
      filter: {
        personId: this.get('person.id')
      },
      include: 'cool-relation'
    });
  }),
```

I have a lot of custom logic to cover the adding and removing from this array through the store. eg there is an observer which observers `person.things.length` and after that, I notify the `things` about change to reload the array.

But I can't cover the case where my custom API action uses `pushPayload` to refresh the state of models.

when `pushPayload` is triggered the `person.things.length` is not. But this happens only if at the  `things` are empty.

It would be nice to have a possibility to load relations with custom `queryParams` but we dont have and I have to cover it somehow. And THIS is is the only one edge case.

**Comment by Exelord** [comment]
I also notied the the observer was working properly on 2.10 and now on 2.11 do not notify belongsTo relation

**Comment by Exelord** [comment]
Here are my new tests that I added to ember data `relationship-changes-test.js`
```js
test('Calling push with new belongsTo relationship does trigger observer', function(assert) {
  assert.expect(1);

  let observerCount = 0;

  run(function() {
    let post = env.store.push({
      data: {
        type: 'post',
        id: '1'
      }
    });

    post.addObserver('author', function() {
      observerCount++;
    });

    env.store.push({
      data: {
        type: 'post',
        id: '1',
        relationships: {
          author: {
            data: { type: 'author', id: '2' }
          }
        }
      }
    });
  });

  assert.equal(observerCount, 1, 'author observer should be triggered');
});

test('Calling push with hasMany relationship does trigger observer', function(assert) {
  assert.expect(1);

  let observerCount = 0;

  run(function() {
    let post = env.store.push({
      data: {
        id: '2',
        type: 'author'
      }
    });

    post.addObserver('author.posts', function() {
      observerCount++;
    });

    env.store.push({
      data: {
        type: 'post',
        id: '1',
        relationships: {
          author: {
            data: { type: 'author', id: '2' }
          }
        }
      }
    });
  });

  assert.equal(observerCount, 1, 'posts observer should be triggered');
});
```

And the last one is failing but in my opinion it should pass.

**Comment by runspired** [comment]
I believe this has since been fixed and we simply forgot to close this, if this is still an issue please re-open.
