### ISSUE TITLE
Proper behavior of `async: false` on JSON API?

### ISSUE THREAD

**Issue by zeiv** [emberjs/data#4834]
For example, I have a model that returns a response like this:

```json
{
  "data": {
    "id": "6",
    "type": "customers",
    "attributes": {
      "name": "Kiehn, Anderson and Leffler"
    },
    "relationships": {
      "locations": {
        "data": [
          {
            "id": "12",
            "type": "locations"
          }
        ],
        "links": {
          "related": "/customers/6/locations"
        }
      }
    },
    "links": {
      "self": "/customers/6",
      "locations": "/customers/6/locations"
    }
  },
  "included": [
    {
      "id": "12",
      "type": "locations",
      "attributes": {
        "name": "West Kansas Institute",
        "customer_id": 6,
        "phone": "794-409-1809"
      },
      "relationships": {
        "customer": {
          "data": {
            "id": "6",
            "type": "customers"
          }
        }
      },
      "links": {
        "self": "/customers/6/locations/12",
        "customer": "/customers/6"
      }
    }
  ],
  "jsonapi": {
    "version": "1.0"
  }
}
```

If I set `locations: DS.hasMany('location', { async: false })` on Customer, I get an error saying that all the related resources have not been loaded.  I think this is a bug because it is expecting the related model to be in the root `data` key.  ..Right?

Error:
```
Assertion Failed: You looked up the 'locations' relationship on a 'customer' with id 6 but some of
the associated records were not loaded. Either make sure they are all loaded together with the
parent record, or specify that the relationship is async (`DS.hasMany({ async: true })`)
```

I'm basically just trying to get the associated and included resources from the original response without making a bunch of new GET requests.  If I set `async: true`, Ember will correctly load the included resources but then also make GET requests for each one.

**Comment by tomoguisuru** [comment]
Hi @zeiv,
I know this is an old issue but I think I can explain what's going on here so that if anyone else chances upon this it will help them.

### The Problem
If you set `{ async: false }` on a relation, then the only way to access that piece of data is to either sideload it via `include` or to make a request for the related data later

So if your setup looks something like this:

_models/customers.js_
```js
import DS from 'ember-data';
const { attr, hasMany, Model } = DS;

export default Model.extend({
  name: attr('string'),

  locations: hasMany('location', { async: false }),
});
```

_templates/customer.hbs_
```hbs
{{customer.name}} has visited the following locations:
<ul class="customer-loctions">
  {{#each customer.locations as |location|}}
    <li class="customer-loctions--visited">{{location.name}}</li>
  {{/each}}
</ul>
```

You will get the error if you haven't manually loaded the additional `locations` records via one of the two methods explained above.

### Potential Solution
I've included two different examples of how you'd go about addressing the issue. (they are by no means the only way to solve the issue)

_routes/customer.js_
```js
model() {
   // load associated records at the same time
  return get(this, 'store').findRecord('customer', customer_id, { include: 'locations' });
}
```

**OR**

_routes/customer.js_
```js
model() {
  // Skip loading the associated `locations` record and lazy-load them later
  return  get(this, 'store').findRecord('customer', customer_id);
},
afterModel(model) {
  // Can be anywhere before you call `customer.locations` and assuming your API support id batching
  return get(this, 'store').findRecords('locations', { ids: model.hasMany('locations').ids() });
}
```

---

I hope this helps you

**Comment by runspired** [comment]
This was most likely an issue with the serializer, and not an ember-data bug.
