### ISSUE TITLE
serializeId confusion

### ISSUE THREAD

**Issue by amk221** [emberjs/data#4888]
I've been using a work-around ([twiddle](https://ember-twiddle.com/d98be215ccddda2e40b4f14f7ea317d6?openFiles=serializers.application.js%2C)) for serializing IDs to integers instead of strings. 

I thought that the new `serializeId` method would mean I could remove my code and use the new hook. However, it isn't working as I'd expect. (_It's quite possible I just have the wrong expectations!)_

In the twiddle, I set up the example provided in the [docs](http://emberjs.com/api/data/classes/DS.RESTSerializer.html#method_serializeId):
```
serializeId(snapshot, json, primaryKey) {
  json[primaryKey] = parseInt(snapshot.id, 10);
},
```

<table>
  <tr>
    <th>
     Output
    </th>
    <th>
     Expecting
    </th>
  </tr>
  <tr>
     <td>
<pre>
{
  "id": "1",
  "name": "Primary model",
  "embeddedHasManys": [{
    "id": 2,
    "name": "An embedded has many"
  }],
  "embeddedBelongsTo": {
    "id": 3,
    "name": "An embedded belongs to"
  },
  "sideloadedHasManys": ["4"],
  "sideloadedBelongsTo": "5",
  "emptyRelationship": null
}
</pre>
</td>
     <td>
<pre>
{
  "id": 1,
  "name": "Primary model",
  "embeddedHasManys": [{
    "id": 2,
    "name": "An embedded has many"
  }],
  "embeddedBelongsTo": {
    "id": 3,
    "name": "An embedded belongs to"
  },
  "sideloadedHasManys": [4],
  "sideloadedBelongsTo": 5,
  "emptyRelationship": null
}
</pre>
</td>
    </tr>
</table>

...as you can see I assumed `serializeId` would allow me to alter all the IDs, but neither the primary model's ID nor the sideloaded models IDs are converted to an integer.

**Comment by bmac** [comment]
The reason why the primary model's id isn't getting serialized is because the `serializers/primary-model.js` serializer completely replaces the `serializers/application.js` serializer when serializing the "Primary model" record. If that serializer also implemented the `serializeId` method defined in `serializers/application.js` the primary model's id would be serialized as a number.

As for `sideloadedHasManys` and `sideloadedBelongsTo` unfortunately the `serializeId` method doesn't support this use case and you will need to continue using your custom `serializeHasMany` and `serializeBelongsTo` methods.

**Comment by amk221** [comment]
Ah yes, silly mistake regarding the Primary ID. Shame about the sideloaded ones.
Thanks for the response though!

**Comment by grayt0r** [comment]
@bmac Is this use case not supported by choice? Or just a limitation of the current `serializeId` implementation? The inconsistent IDs in @amk221's twiddle definitely lead to some confusion.

As `serializeId` was added to provide symmetry with `extractId`, maybe there needs to be another hook that does the opposite of `coerceId`? As number IDs are supported in responses from an API, even for `hasMany` and `belongsTo` relationships, it feels like there should be a way to easily serialize those relationships as number IDs as well.
