### ISSUE TITLE
Class.reopen + Class.eachAttribute

### ISSUE THREAD

**Issue by rwolffgang** [emberjs/data#4902]
Hi guys,

I'm working on a project where the model data from the server has attributes, that are unknown at design time, i.e. attributes that the user can specify. My approach is to write a custom serializer where I check if the class has a property defined and if not, it's being created. For this purpose I started with a simple test, expanding my existing serializer:

```javascript
import DS from 'ember-data';
import NodeSerializerMixin from '../mixins/node-serializer';

export default DS.JSONSerializer.extend(DS.EmbeddedRecordsMixin, NodeSerializerMixin, {
  normalize: function (typeClass, hash, prop) {
    typeClass.reopen({
      Name: DS.attr('string'),
      Test: Ember.computed('id', function () { return "test"; })
    });

    typeClass.eachAttribute((key, meta) => {
      if (key == "Name" || key == "Test")
        console.log("new attribute found", key, meta);
    });

    [...]
```
I'd expect to see two console entries of "new attribute found", but I don't get any.

Can anyone point me in the right direction, or did I encounter a bug?

Thanks
Robert

**Comment by pangratz** [comment]
Reopening a model class and adding attributes works, but not during run time. The reason is that the `attributes` computed property on the model class has no dependencies:

https://github.com/emberjs/data/blob/0d0fbf9d0844292eed9af042dcea688077ab79fb/addon/-private/system/model/model.js#L1670-L1683

So once the `attributes` on a model class are accessed, and this is the case when a serializer normalizes a palyload for example, the `attributes` map is cached and never invalidated.

So I am afraid your use case is not supported out of the box. Feel free to chime in at the [`-ember-data` channel](https://embercommunity.slack.com/messages/-ember-data/) in the [Ember Community Slack](https://ember-community-slackin.herokuapp.com/), maybe somebody has a solution...
