### ISSUE TITLE
MODEL_FACTORY_INJECTIONS + no double extend + polymorphic may have issues

### ISSUE THREAD

**Issue by stefanpenner** [emberjs/data#4966]
With double extend off in new ember `Ember.ENV.MODEL_FACTORY_INJECTIONS` isn't accurate, and most likely is causing issues.

Most likely: https://github.com/emberjs/data/blob/e6cb564bdb33da4b3c15c3c668dc4b1fdafdf190/addon/-debug/index.js#L37-L39

And likely others:
https://github.com/emberjs/data/search?utf8=%E2%9C%93&q=MODEL_FACTORY_INJECTIONS&type=

We should review and audit each occurrence, and address issues that arise.

## Plan

* add tests for `assertPolymorphicType` https://github.com/emberjs/data/blob/e6cb564bdb33da4b3c15c3c668dc4b1fdafdf190/addon/-debug/index.js#L37-L39
* add tests with both double extend and no double extend
* fix funky things discovered

**Comment by stefanpenner** [comment]
I believe ember (when double extend is disabled) needs to force MODEL_FACTORY_INJECTIONS to always be false: https://github.com/emberjs/ember.js/pull/15204

**Comment by runspired** [comment]
There is an open PR for this I should fix at some point soon: (#4886)

**Comment by runspired** [comment]
We were never able to fix this because there isn't a good way to deal with creating an extra extend just-in-time. That said the need for doing so has greatly diminished with time, and the lack of reports indicates that we've mostly eliminated the footguns. Internally I don't believe we use Model.modelName anywhere at this point. Even adapters and serializers are moving away from it as we now provide them a schema wrapper.
