### ISSUE TITLE
Ember data - send only properties that have value in a post request

### ISSUE THREAD

**Issue by g8anusha** [emberjs/data#5103]
I have a model with many attributes and certain associations. Most of them may or may not be null. I am trying to do an Ajax call with this model as a payload, and certain properties can be null.

I want to send only the properties that have values, and not null, including associations in a post request (new record).

Is it possible? Kindly let me know if it is possible. E.g. 

    export default DS.Model.extend({
      name : DS.attr('string'),
      address : DS.hasMany('address')
     });

**Comment by tylerturdenpants** [comment]
To do both you must override the serializer. First, you need to override the serialize method on the serializer of the  model where a simple recursive remove function (you need to write your own or google for it) can be called to remove all null or undefined properties. Second you need to add the embedded records mixin and use the attr property to specify that related models be expanded instead of just their ids.

**Comment by g8anusha** [comment]
I'd want to change only the request. Why should the serializer be modified ?

**Comment by tylerturdenpants** [comment]
I imagine you need to turn your model into json as part of the post/ajax?  If that's the case you need to call model.serialize() which will give you the json of that model.

**Comment by pangratz** [comment]
Take a look at [`serializeAttribute`](https://emberjs.com/api/ember-data/2.16/classes/DS.JSONSerializer/methods/serializeAttribute?anchor=serializeAttribute) and [`serializeHasMany`](https://emberjs.com/api/ember-data/2.16/classes/DS.JSONSerializer/methods/serializeHasMany?anchor=serializeHasMany) for how to customize your serialized record. If you have further questions, please chime in at the #ember-data channel on the https://embercommunity.slack.com/ slack.
