### ISSUE TITLE
`unloadAll` not releasing relationships

### ISSUE THREAD

**Issue by btecu** [emberjs/data#5112]
Using the `RESTAdapter` on ember-data 2.14.9:

In a `model` hook, I have to unload all the records of that type.  
```
this.store.unloadAll('my-type');
```
There are two other models (`document` and `note`) that `belongTo` `my-type`.
For some reason, those are never released and become unusable on subsequent requests.
Workaround for now:
```
let storage = this.store._identityMap._map;
delete storage.document;
delete storage.note;
```

**Comment by acorncom** [comment]
A similar issue where accessing the identity map is needed is written up here: https://github.com/emberjs/data/issues/4972

**Comment by dknutsen** [comment]
This also sounds similar/same as an issue that I opened a little while back: #4938

**Comment by runspired** [comment]
This issue is similar to #4972 and #4938 but has a different intent.  Here, the user wants to "pull the thread", e.g. if A has B and A is unloaded, then B is also unloaded. This is simply not how `unloadRecord` and `unloadAll` has ever worked, and would be a new API entirely.

I'm closing this issue; however, an RFC or an addon for unloading groups of records might be an interesting idea to pursue.
