### ISSUE TITLE
Inherited models no longer serialize

### ISSUE THREAD

**Issue by btecu** [emberjs/data#5113]
Using the RESTAdapter on ember-data 2.14.9:

I have a base model `process` with a custom serializer:
```
import EmbeddedRecordsMixin from 'ember-data/serializers/embedded-records-mixin';
import RESTSerializer from 'ember-data/serializers/rest';

export default RESTSerializer.extend(EmbeddedRecordsMixin, {
  attrs: {
    documents: { serialize: 'ids' },
    notes: { embedded: 'always', serialize: 'ids' }
  }
});
```

I also have another model `status-process` that extends `process`:
```
import attr from 'ember-data/attr';
import Process from './process';

export default Process.extend({
  status: attr('number')
});
```

Up until `2.11.3`, the serialization was implicitly applied as well.
Now it no longer does and so I had to create an empty `status-process`:
```
import Process from './process';

export default Process.extend({ });
```

It seems that the original way was more inline with existing functionality, i.e., `application` adapter.
However, if current approach is correct, it should at least be documented.

**Comment by runspired** [comment]
@btecu your example here is unclear, but I suspect I know what you are hitting (and how you should address officially).  The TL;DR is that you cannot (any longer) re-export a model for use in multiple places without also extending it at the new export site.

**Comment by btecu** [comment]
@runspired Just to be sure, you're saying that how it works now (need to re-export even if empty) it's how it should be?

**Comment by pangratz** [comment]
Ping @runspired

**Comment by bmac** [comment]
I think how it works not (having to re-export an empty serializer) is how it should be. The old behavior was the result of a bug where the `status-process` model class was inheriting some runtime state from the `process` model class which was allowing the `process` serializer lookup for work. We've been slowly working to reduce the amount of state information that gets added to the model class at runtime because it can cause some hard to decipher issues when models are extended in an application or reused in tests.
