### ISSUE TITLE
Globally set all update to use PUT method call

### ISSUE THREAD

**Issue by SaimonL** [emberjs/data#5228]
I am using emberjs 2.16 which does "options" method call for update out of the box (I have never seen options used anywhere else as rest API law). 
I am trying to have emberjs do all update calls to server as method PUT type request.

Unfortunately both of these did not work for me
```javascript
  updateRecord: function (store, type, snapshot) {
    var data = {};
    var serializer = store.serializerFor(type.modelName);

    serializer.serializeIntoHash(data, type, snapshot, { includeId: true });

    var id = snapshot.id;
    var url = this.buildURL(type.modelName, id, snapshot, 'updateRecord');

    return this.ajax(url, 'PUT', { data: data });
  }
```

And
```javascript
methodForRequest({ requestType }) {
    if (requestType === "updateRecord") {
      return "PUT";
    }

    return this._super(...arguments);
  }
```

Now I can not move any further.
I am updating from controller with the following save action code

```javascript
    save() {
      this.get('model').save().then(
        () => this.transitionToRoute('calendars'),
        () => console.log('error saving')
      );
    },
```

**Comment by bmac** [comment]
Hi @SaimonL. It sounds like you are making a request to a origin that is different from the one your app is being served from (For example you access your app by visiting `http://localhost:4200` while your api lives on `http://localhost:8000`). This known as a cross origin request (or [CORS](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS)). As a security measure, whenever you try to make a non `PUT` cross origin request your browser will first automatically make an OPTIONS request. And check for a special `Access-Control-Allow-Origin` header in the response to the options request before deciding if its safe to issue a `PUT` request.

Because of this behavior the `OPTIONS` request you are seeing is originating from the browser and not Ember Data. If you are not seeing the `PUT` request after the `OPTIONS` request its likely your browser isn't satisfied with the response, you may need to add the following headers to your response:
 
```
Access-Control-Allow-Origin: http://localhost:4200
Access-Control-Allow-Methods: PUT
Access-Control-Allow-Headers: X-ANY-NON-STANDARD-HEADERS, Content-Type
```

As for updating Ember Data to use the `PUT` verb for updates your `updateRecord` example should work great. You may also want to try using the `DS.RESTAdapter` as your application adapter because it uses `PUT`s for updates out of the box.

**Comment by SaimonL** [comment]
Hi @bmac . Thanks for taking the time to write this perfect explanation. I understand now. I was using Rails server on port 3000 and was using Postman and curl to test the PUT request which is working fine. I did not know that browser had this extra security check. Going full rest I am going to start using DS.RESTAdapter. Thanks for the help.

**Comment by SaimonL** [comment]
For those who are using Rails 5 as an API server this is what you will need to do.

In Gemfile
`gem 'rack-cors'`

Create a file "config/initializers/cors.rb"
```ruby
Rails.application.config.middleware.insert_before 0, Rack::Cors do
  allow do
    origins 'localhost:4200'
    resource '*',
      headers: :any,
      methods: %i(get post put patch delete options head)
  end
end
```

Credit goes to: https://til.hashrocket.com/posts/4d7f12b213-rails-5-api-and-cors

As for Emberjs
In file: "app/adapters/application.js"
```javascript
import DS from 'ember-data';

export default DS.RESTAdapter.extend({
  host: 'http://localhost:3000',
  namespace: 'api/v1'
});
```
This will have allow ember to do all kinds of requests to Rails.
