### ISSUE TITLE
Why new record type is pluralized as per default?

### ISSUE THREAD

**Issue by beddueimpossibile** [emberjs/data#5421]
```
var rec = this.get("store").createRecord('post', {title: 'New post'});
rec.save();
```

the code above posts the following payload to the server:

> {"data":{"attributes":{"title":"New post"},"type":"posts"}}

shouldn't be the **type** attribute be equal to the model's name?

**Comment by runspired** [comment]
end points in json-api generally follow the convention that resource types are pluralized. If you API does not do so, you can override this pluralization here: https://emberjs.com/api/ember-data/3.0/classes/DS.JSONAPIAdapter/methods/pathForType?anchor=pathForType

**Comment by beddueimpossibile** [comment]
Thanks for the quick reply.
I am not referring to the path for the request, but about the value of the "type" attribute of the json payload posted to the server, to customize that, I had to override the serializer's serialize method.
My question is: an application creates a new record of type 'post' and save it, shouldn't be the value of the newly created json api record attribute "type" be equal to the model's name?
I don't see why it must be always pluralized, according to me, it is not correct, and if it is correct I would like to understand why...
Thank you!

**Comment by sukima** [comment]
I have this problem to. Why has this been ignored?

**Comment by runspired** [comment]
@sukima the json-api spec allows for singular or plural types and asks implementors to choose one [spec](https://jsonapi.org/format/#document-resource-object-identification). Most implementations chose plural types, so that is the assumption that the `JSONAPISerializer` makes for both in-bound normalization and out-bound serialization. However, if you do not require this conversation you may either implement your own serializer (honestly recommend it when using json-api) or override the appropriate hooks to treat `type` as singular.
