### ISSUE TITLE
Why displaying a warning for always embedded record when they are empty ?

### ISSUE THREAD

**Issue by BnitoBzh** [emberjs/data#5552]
Why displaying a warning for always embedded record when they are empty ?

[ data/addon/serializers/embedded-records-mixin.js  at line 422](https://github.com/emberjs/data/blob/master/addon/serializers/embedded-records-mixin.js#L422,L437)

If a hasMany relationship is defined as always embedded, i think if it is empty is normal to serialize it into an empty array without display a warning.

For example an implemention of "cancels and replaces" when send the request to the server.

This could be corrected by adding a check on the serialization type :

```
_serializeEmbeddedHasMany(snapshot, json, relationship) {
    let serializedKey = this._getMappedKey(relationship.key, snapshot.type);
    if (serializedKey === relationship.key && this.keyForRelationship) {
      serializedKey = this.keyForRelationship(relationship.key, relationship.kind, 'serialize');
    }

    let alwaysEmbed = this.hasEmbeddedAlwaysOption(relationship.key);
    warn(
      `The embedded relationship '${serializedKey}' is undefined for '${
        snapshot.modelName
      }' with id '${snapshot.id}'. Please include it in your original payload.`,
      typeOf(snapshot.hasMany(relationship.key)) !== 'undefined' || alwaysEmbed,
      { id: 'ds.serializer.embedded-relationship-undefined' }
    );

    json[serializedKey] = this._generateSerializedHasMany(snapshot, relationship);
},
```

**Comment by Darshan-Chauhan** [comment]
@runspired , any update on this?? I wouldn't mind opening a PR as Hacktoberfest is going on.
Let me know. :)

**Comment by hjdivad** [comment]
embedding the has many as an empty array is communicating to your server that the relationship should be emptied.

If the has many is `undefined` locally this means there's nothing loaded locally, which isn't the same thing as knowing the local value is empty.  Sending a value of `[]` to the server in this case could cause data loss.

In the case where you have an `undefined` value (eg because your API did not include it in the response) the most likely case is that there's a bug and it would be a mistake to serialize the value in a save.
