### ISSUE TITLE
model.hasOwnProperty('id') used to return true, returns false in 3.2+

### ISSUE THREAD

**Issue by mydea** [emberjs/data#5568]
Apparently, from Ember Data 3.1 to 3.2, the following has changed:

```js
let model = store.createRecord('item');
model.hasOwnProperty('id'); // was true, is now false
```

I made a small twiddle to try this out:
https://ember-twiddle.com/7caba6683b713fc8e9e436e35a1de395?openFiles=templates.application.hbs%2C

Setting the ED version to 3.2 results in it being false. (I also tried it locally with ED 3.3, where it behaves like 3.2)

This is maybe a bit of a weird usage anyhow, but it was used in a non-ember library where it used to work and suddenly stopped doing so.

**Comment by runspired** [comment]
Prior to 3.2, `id` was set directly on the record instance via an observer, we eliminated this observer (which was always a bad pattern and had become problematic with newer versions of ember) in place of proxy.  I'll bring it up with the rest of the team as to whether `id` being a property on the `prototype` now instead of an instance property should be considered a bug.

**Comment by runspired** [comment]
@mydea after discussing this with the team, we decided that we do not intent to provide a guarantee around `hasOwnProperty` (or really any of the attributes/relationships on a record instance). We feel this way because these classes are complex proxies, and serialization/deserialization/copying/toJSON of them is typically best handled by very custom implementations.

With the `RecordData` feature approaching a stable release, there will soon be the ability for addons to provide custom `Record` classes instead of `DS.Model`. A custom model could provide additional guarantees if desired.
