### ISSUE TITLE
Cannot read property 'replace' of undefined during Normalize

### ISSUE THREAD

**Issue by zion03** [emberjs/data#5811]
I'm trying to `normalize` related data `Attribute` --> `Values` for this executing:

`this.store.normalize('attribute', my_JSONAPI_Data);`

Then I get error:
string.js:63 Uncaught TypeError: Cannot read property 'replace' of undefined
    at Cache.func (string.js:63)
    at Cache.get (ember-metal.js:2611)
    at decamelize (string.js:100)
    at Cache.func (string.js:11)
    at Cache.get (ember-metal.js:2611)
    at Object.dasherize (string.js:104)
    at normalizeModelName (-private.js:560)
    at Class.modelNameFromPayloadKey (json-api.js:352)
    at Class._extractType (json-api.js:338)
    at Class.normalize (json-api.js:379)

From this log I can't understand what happen here. Simple `codesandbox` show the problem https://codesandbox.io/s/n5l1xw656l

**Comment by runspired** [comment]
The issue here is that you are trying to use `store.normalize` with a format that your serializer does not expect.

Below you can see that I've added a breakpoint for when the `key` provided to `modelNameFromPayloadKey` is `undefined`, and it is paused because this condition has been met.

<img width="948" alt="screen shot 2019-02-15 at 3 51 06 pm" src="https://user-images.githubusercontent.com/650309/52890524-04ce3d80-313a-11e9-8139-6ac4b0238009.png">

Stepping back, we see that we are trying to access the property `type` from an object that looks like a `json-api` document instead of a single `json-api` resource that `Serializer.normalize` expected.

<img width="945" alt="screen shot 2019-02-15 at 3 52 08 pm" src="https://user-images.githubusercontent.com/650309/52890525-04ce3d80-313a-11e9-9d31-d371dba862cf.png">

And finally, we can confirm that in fact that is the data we passed in

<img width="950" alt="screen shot 2019-02-15 at 3 52 42 pm" src="https://user-images.githubusercontent.com/650309/52890526-04ce3d80-313a-11e9-9205-f27db48ad1ed.png">
