### ISSUE TITLE
belongsTo resolves to undefined in 3.6.0

### ISSUE THREAD

**Issue by BryanCrotaz** [emberjs/data#5821]
Comment adapter returns:
```
{
  data: {
    type: 'comment',
    id: 2,
    relationships: {
      post: {
        data: {
          type: 'post',
          id: '1',
        },
      },
    },
  }
}
```

```
store.findRecord('comment', 2)
.then(comment => comment.get('post'));
```
should return a promise resolving to the post.
Instead it returns a promise resolving to `undefined`.

**Comment by BryanCrotaz** [comment]
@runspired this seems like a very serious regression. Is my test in the PR valid? It seems so to me.

**Comment by runspired** [comment]
The test in the PR wasn't correct, though I'd love to see a test for this as I suspect it relates to/duplicates #5506

**Comment by runspired** [comment]
did some more digging and I think the bug here was an issue with proxy and relationship changes made as we converted to RecordData internally. These issues have since been resolved, and since the reported issue and test cases if broken would be breaking basically every app in existence, I suspect this was a transient issue at the time that we fixed but failed to recognize was associated with this PR.
