### ISSUE TITLE
infinite recursion if get relationship in model init()

### ISSUE THREAD

**Issue by BryanCrotaz** [emberjs/data#5836]
This didn't happen in ED 2.x, but certainly happens in ED 3.6

in model:

```
init() {
  this._super(...arguments);
  this.get('children').then(children => this.set('count', children.length));
}

children: DS.hasMany('person', {async: true});
```
This results in infinite recursion with ED trying to construct the model recursively

**Comment by BryanCrotaz** [comment]
I'll create a PR with a test when I get time

**Comment by runspired** [comment]
@BryanCrotaz doing `async` within a constructor is ... a bit bonkers. That said likely the issue is that kicking this request off here is leading to a timing issue with the instantiation of the related records resulting in them having multiples. It's a similar fail scenario to others we have addressed for observers, and while I'm happy to try to fix this given a failing test I'm unsure if we'll be able to truly address it given that these sorts of instantiation issues are at odds with the object model in use currently.

**Comment by BryanCrotaz** [comment]
Example - priming an observer by getting the value of a hasMany

```
// models/post.js
...
init() {
  this._super();
  this.get('comments');
}
...
```

**Comment by BryanCrotaz** [comment]
solution - add the new model to the repository before calling init

**Comment by BryanCrotaz** [comment]
@runspired how would you recommend constructing a test for infinite recursion? I don't want to build something that hangs the tests in a failure case

**Comment by runspired** [comment]
Stub something you expect to be called recursively and forcibly exit after N calls

**Comment by runspired** [comment]
closing as stale and because it doesn't fit the semantics of the object model in use today
