### ISSUE TITLE
Log when a serializer or adapter doesn't match an existing model

### ISSUE THREAD

**Issue by NullVoxPopuli** [emberjs/data#5838]
Was helpin' someone in discord, and they didn't know why their serializer wasn't getting used.

Eveeenttuuualllly, we found that it was because:
- an application serializer is required if you have a model specific serializer
- application (in the serializers folder) was spelled incorrectly

It'd be nice to know when stuff like this happens :)

**Comment by evoactivity** [comment]
That's not quite the problem. He didn't need an application serializer, the serializer name didn't match the model name. His model was `assessor` and his serializer was `assesssor`. So a warning being thrown if a serializer/adapter is found with no corresponding model would be useful.

**Comment by runspired** [comment]
We cannot warn in this scenario because it is 100% valid (and even encouraged in many situations) to have adapters and serializers that are not `1:1` with models and which may not take the name of any model at all.

Best I can offer is that in this scenario users inspecting the code being run should notice when stepping in that they aren't hitting the code they expect, and can use `_debugContainerKey` to see which adapter/serializer was in fact resolved.

**Comment by NullVoxPopuli** [comment]
I can understand having models that don't have serializers, but what's the point of a serializer without a model?
