### ISSUE TITLE
Autodetecting Inverse Relationship on Recursive Relationship

### ISSUE THREAD

**Issue by anlumo** [emberjs/data#5881]
### Reproduction

Demo: https://ember-twiddle.com/bde18fff6b4851d9caef5b4f1d1056f9

### Description

The example creates a simple model `foo` with a single relationship, a belongsTo to its own type. When pushing an entry, this relationship is supplied, but when you look at the record in the store, the relationship is null.

The reason is that the inverse relationship autodetection thinks that the relationship itself is the inverse (since it's the only one with this type), which causes the other record's relationship to overwrite this one. When you supply `{ inverse: null }` to `belongsTo`, it works fine (which is a huge pitfall).

So technically, this is correct behavior, but not what you would expect.

### Versions

* ember-source@3.7.2
* ember-cli@3.7.1
* ember-data@3.7.0

It also occurs on the Twiddle, though.

**Comment by runspired** [comment]
When you do not explicitly provide an `inverse`, the default is not `null`, but rather auto-detection.

`ember-data` supports a number of relationship setups, including self-referential, reflexive, and circular relationships (and their polymorphic siblings).

A brief overview of these terms:

- `self-referential`: a relationship that points at another record of the same-type (often modeled with distinct `parent`/`child` type property names).
- `reflexive`: a self-referential relationship whose propertyName on each record is identical
- `circular`: a self-referential, possibly reflexive relationship in which a record links to itself

In your case, you want a `self-referential` relationship, but because you did not specify an inverse, you ended up with a reflexive relationship via auto-detection, which noted that you had a relationship with no explicit inverse and only one possible inverse (itself).

Specifying `inverse: null` for this sort of "one-directional linked-list" setup is the correct thing to do, as you discovered.

I do think that auto-detection is a magical troll, and I prefer to caution users to use an "always explicit" style for just this reason. I would very much like to see an RFC dropping support for auto-detection.
