### ISSUE TITLE
Record attributes are getter-only properties, so cannot be assigned

### ISSUE THREAD

**Issue by CodingItWrong** [emberjs/data#6001]
### Reproduction

<https://github.com/CodingItWrong/ember-data-modify-sandbox>

### Description

When assigning new values to Ember Data record attributes, I expect to be able to use the native setter, such as `record.myAttribute = `.

The actual behavior I observe is that assigning to an attribute raises the error `TypeError: setting getter-only property "name"`. I need to use `.set()` to set the attributes instead.

### Versions

```cli
ember-data-modify-sandbox@0.0.0 /Users/josh/apps/ember-data-modify-sandbox
└── ember-source@3.9.1

ember-data-modify-sandbox@0.0.0 /Users/josh/apps/ember-data-modify-sandbox
└── ember-cli@3.9.0

ember-data-modify-sandbox@0.0.0 /Users/josh/apps/ember-data-modify-sandbox
└── ember-data@3.9.0
```

**Comment by runspired** [comment]
After discussing with @pzuraq we realized that this was because computed properties still require the use of `set`, and this will work correctly when `set` is used instead of direct assignment.

We're hopeful that the requirement to use `set` might be dropped in the near future. We may do some work in `ember-data` to speed this up.

**Comment by rwjblue** [comment]
I think we can do a nicer thing in Ember though (e.g. define a dev mode setter that throws a helpful error or something like that), will think about it...
