### ISSUE TITLE
Tests throw decorator deprecations

### ISSUE THREAD

**Issue by igorT** [emberjs/data#6002]
Running the test suite, there are deprecations regarding the old decorator syntax

**Comment by runspired** [comment]
I'm not sure we can eliminate these yet because we don't have a way to differentiate when `octane` decorators are available vs not. cc @pzuraq because it's a bit annoying that ember-decorators chose to deprecate prior to there being a path forward for apps and addons.

**Comment by NullVoxPopuli** [comment]
There is an environment variable we can check

https://github.com/ember-cli/ember-octane-blueprint/blob/master/packages/%40ember/octane-app-blueprint/files/.ember-cli.js

**Comment by pzuraq** [comment]
@NullVoxPopuli that environment variable is likely not available here, since they aren't going to be updating the Ember Data addon to use Canary (and it has to test against older versions anyways).

@runspired you should be able to use `ember-compatibility-helpers` to test against `gte('3.10.0')` since we have a target release version now, and it's in beta. I wouldn't add production code using this just yet, maybe when we're closer to launch, but it should be fine for tests.

Alternatively, you should also be able to install the polyfill, which will allow you to use the native APIs with all of the ember versions in your try matrix it looks like.

**Comment by igorT** [comment]
This seems related to our build failing https://travis-ci.org/emberjs/data/jobs/519091240
getting a bunch of  `(0 , _decorator.decorator) is not a function`

**Comment by NullVoxPopuli** [comment]
PR: https://github.com/emberjs/data/pull/6026

**Comment by runspired** [comment]
Closed by #6026
