### ISSUE TITLE
PromiseProxy meta access error message is untested

### ISSUE THREAD

**Issue by igorT** [emberjs/data#6012]
https://github.com/emberjs/data/blob/f94776c761d0c47b17f2a340775689cce1aa582b/packages/store/addon/-private/system/promise-proxies.js#L89

This error message seems to not be tested

**Comment by Mikek2252** [comment]
Hey @igorT i'm looking at adding this test but i'm not 100% sure how i am accessing the object. I presumed it would be `DS.PromiseBelongsTo` but that doesn't seem to work, i guess because there isn't an export function like the other models. I have the test case, but could you point me to how i can create the object in the test.
