### ISSUE TITLE
[INFRA]: Add Safari support to testing pipeline

### ISSUE THREAD

**Issue by snewcomer** [emberjs/data#7170]
Currently, IE11 and Chrome are tested in CI.  By adding Safari support, we will expand our testing coverage beyond IE11 and Chromium based browsers.

https://github.com/testem/testem/blob/master/README.md#launchers

**Comment by runspired** [comment]
I tried to add support for Safari a while back and found its not currently possible due to limitations with safari's security model

- https://github.com/testem/testem/issues/1387
- https://github.com/karma-runner/karma-safari-launcher/issues/29

As far as I can tell there's been no further movement to make it possible.

**Comment by snewcomer** [comment]
ok closing
