### ISSUE TITLE
Re-exporting DS.Store fails in in-repo addon (3.15+)

### ISSUE THREAD

**Issue by wongpeiyi** [emberjs/data#7187]
Re-exporting DS.Store service works in an Ember app but fails in an addon. Instead, the DefaultStore is exported. This used to work in 3.14, but fails after upgrading to 3.15.

### Reproduction

I have a simple repo for an addon here: https://github.com/wongpeiyi/test-data/commit/c9e5f8575f078e3a787b4b4d18775f862f8ec08a

The test passes in 3.14 but fails in 3.15

Is this no longer supported in addons or am I doing something wrong?

**Comment by runspired** [comment]
The issue here is one of namespacing. Both ember-data and your add-on are providing a store service located at `app/services/store.js`. It is indeterminate which will win (whichever is compiled last will win).

The consuming application needs to import the store it desires to use. In this case, the dummy app for your add-on would be responsible for the selection.

**Comment by wongpeiyi** [comment]
Thanks @runspired that makes sense. Guess I assumed it working in the past was intended behaviour rather than coincidence
