### ISSUE TITLE
[FEATURE]: support serializing top level meta hash

### ISSUE THREAD

**Issue by snewcomer** [emberjs/data#7245]
Support currently only exists for relationship members.  However, we currently do not support serializing top level member `meta` hashes.

https://jsonapi.org/format/#document-meta

close #7244

**Comment by runspired** [comment]
We currently don't have a concept of documents internally and because of this it would be *very* hard to add this meta in any meaningful sort of way.

That said, we did accept this RFC which we still haven't implemented for resource-level links and meta https://github.com/emberjs/rfcs/blob/master/text/0332-ember-data-record-links-and-meta.md

**Comment by runspired** [comment]
We have added support for documents in https://github.com/emberjs/rfcs/pull/854 which also specifies how document-meta is handled by the cache.
