### ISSUE TITLE
Sanitise error throw in production builds

### ISSUE THREAD

**Issue by amk221** [emberjs/data#7270]
### Description

Could Ember Data consider sanitising this error message in production builds?

https://github.com/emberjs/data/blob/a3fd90fe3c5c700ee90ef60bc53d2eb1b8f46344/packages/store/addon/-private/system/model/internal-model.ts#L931-L934

There is a potential for third party logging services to capture sensitive data via the `${value}`.

Although this is possibly not Ember Data's concern, and is instead the responsibility of the developer to fix the actual problem (which would be to not perform the `set` if the record is deleted in the first place).

Thanks for any insight

**Comment by igorT** [comment]
@amk221 Thats a very good point. In general having more context in errors is nice, but I completely see the issue here. I think in this case it might be easy to just remove the value part of the message. Do you want to open a PR with the change?  @rwjblue do you know if ember has a flag/mode for removing context from error messages?

**Comment by amk221** [comment]
Would welcome feedback on my PR attempt
