### ISSUE TITLE
Increase the threshold for size increase in PRs, add another check for inbetween releases

### ISSUE THREAD

**Issue by igorT** [emberjs/data#7355]

**Comment by snewcomer** [comment]
500 bytes or 1000 byte threshold for PRs?  What size is acceptable for in between releases?

**Comment by runspired** [comment]
TBH we are in a place where we should only ever be decreasing in size between releases. If we increase that needs to be a very intentional decision. The 15B threshold I originally set had this philosophy in mind at all (15B seemed to be the "jiggle" in the compression algorithms plus a few for letting us make very minor fixes). For release-to-release threshold I'd make it zero. If we are regressing at all I'd want to know.
