### ISSUE TITLE
Сhild attributes are not updated correctly when sideposted record has different attribute than in the response payload with lid provided

### ISSUE THREAD

**Issue by helgablazhkun** [emberjs/data#7781]
### Reproduction

Here is PR linking to this issue with a failing test:
https://github.com/emberjs/data/pull/7780

### Description

The issue appeared in the sideposting scenario:

1. model A has belongs to relationship to model B.
2. instance of model A and instance of model B are created on the client
3. model A is saved along with model B sent in include section of payload; the linking is done through lid;
4. server sent the response payload with different value of attributes for instance of model B
Expected result: 
  after .save() client instance of model B has the same attributes that instance of model B on server
Actual result: 
  after .save() client instance of model B has attributes that were specified before .save() called. 

Please note that the same issue is reproduced during update record.

### Versions

```cli
└─ ember-cli@3.26.1
✨  Done in 1.10s.
yarn list v1.22.4
├─ @ember-data/adapter@4.1.0-alpha.13
├─ @ember-data/canary-features@4.1.0-alpha.13
├─ @ember-data/debug@4.1.0-alpha.13
├─ @ember-data/model@4.1.0-alpha.13
├─ @ember-data/private-build-infra@4.1.0-alpha.13
├─ @ember-data/record-data@4.1.0-alpha.13
├─ @ember-data/rfc395-data@0.0.4
├─ @ember-data/serializer@4.1.0-alpha.13
├─ @ember-data/store@4.1.0-alpha.13
├─ @ember-data/unpublished-test-infra@4.1.0-alpha.13
├─ babel-plugin-ember-data-packages-polyfill@0.1.2
├─ ember-data@4.1.0-alpha.13
└─ eslint-plugin-ember-data@4.1.0-alpha.13

```

**Comment by runspired** [comment]
After reviewing, this is expected behavior and not a bug. However, expected does not necessarily mean desired and I'd recommend trying to start a discussion around what the best update semantics here should be / whether a transactional primitive could be provided that could help applications achieve the desired result in an ergonomic way.

The reason the record is still in the dirty-state after saving via sidepost and why the local state is left unchanged is because when you sidepost the record itself is never transitioned into a saving state. Due to this, nothing has tracked what attributes and values were given to the request. For all we know these attributes and values should be considered stale compared to what we have locally still. In ember-data today, local values are given precedent over the remote values. You will see this same effect when reloading a record that has dirty attributes / receiving an update in the background for a record that has dirty attributes.

In your application, if you know that you are sideposting and that the responses contain altered values you can use rollbackAttributes on the record to move it to a clean state after the save completes. Alternatively, in your adapter you can mark the sideposted records as saving, and resolve their save promises once the primary request has completed.

**Comment by andreyfel** [comment]
@runspired makes sense, thanks for the explanation!

> Alternatively, in your adapter you can mark the sideposted records as saving, and resolve their save promises once the primary request has completed.

Is it possible to achieve using public API? Could you please show an example?

**Comment by runspired** [comment]
@andreyfel yes both of these are public APIs. The first would just entail something like this.

```ts
const address = store.createRecord('address', {});
const user = store.createRecord('user', { address });

await user.save();
address.rollbackAttributes();
```

The second is a bit un-ergonomic unless you write a few helper functions, in which case it becomes pretty trivial to create transactions. An example of this is here: https://ember-twiddle.com/bc93f1c525837420f7b14d8cdcb2d36a

Note: you'd still want to use lid to match the records up, and you'd probably need to do a lot less work in the saves of the sideposted records over what this shows.
