### ISSUE TITLE
Regression: sideposted record id doesn't get updated after save

### ISSUE THREAD

**Issue by andreyfel** [emberjs/data#7783]
If the newly created record id is consumed before save(), the id won't get updated after the record is sideposted through belongsTo or hasMany relationship. The PR with failing test is here: #7782.

Found this issue while upgrading from ember-data@3.26 to 3.28.

It may be related or have the same root cause as #7781

**Comment by runspired** [comment]
@andreyfel does this still happen if `lid` is also reflected for the cake on the included relationship in #7782 ? It ought to be reflected there in retrospect. Also should be reflected on the main payload. The concept is that wherever there is a linkage it needs to be included, and since ingredient can link back to the cake which is also being created at the same time it would be required on both sides.

**Comment by andreyfel** [comment]
@runspired yes, It happens even if I provide cake `lid` in the payload in both main payload and ingredient's relationship.
