### ISSUE TITLE
Store in acceptance tests destroyed before Route#deactivate is run

### ISSUE THREAD

**Issue by luxferresum** [emberjs/data#7821]
### Reproduction

I was able to create a reproduction with ember 4: https://github.com/luxferresum/ember-deactivate-test-err
However I myself basically encountered this error in 3.28, however was not able to reproduce this (yet).

### Description

In acceptance tests the store seems to already be destroyed before the `deactivate` hook of the route runs. This will break a deactivate hook like this:

```js
  deactivate() {
    if (this.controller.model.isNew) {
      this.controller.model.destroyRecord();
    }
  }
```

This breaks tests that end on a route with such a deactivate hook. A Possible workaround is to just `await visit(...)` another route at the end of the test.

The Error with 4.0 is
```
Attempted to call store.deleteRecord(), but the store instance has already been destroyed.
```

The different error I encountered in 3.28 (but can not reproduce) is
```
Attempted to handle event `deleteRecord` on <address:null> while in state root.empty.
```

This definitely worked in 3.24.

### Versions

```cli
ember-source@4.0.1
ember-cli@4.0.1
ember-data@4.0.2
```

### PS: `willDestroy()`
I just encountered basically the same problem when having a similar code in `willDestroy` of a glimmer component.

**Comment by runspired** [comment]
This seems likely due to changes in ember-source vs ember-data. I'd try various ember-data versions against ember-source 3.24 to confirm.

**Comment by runspired** [comment]
@luxferresum to revisit this, while this likely has something to do with upstream changes and/or the changeover to `fetch` by default, the underlying problem is that an async call is being made by the route during deactivation and nothing is setup to wait for it.

```
  deactivate() {
    if (this.controller.model.isNew) {
      this.controller.model.destroyRecord();
    }
  }
  ```
  
  typically tests automatically do an `await settled()` at the end and the default waiters catch most ember-data network behavior if using ajax. The transition to fetch may have borked this; however, ember-data has it's own waiter which is not currently on by default. Activating it would likely solve this bug for you.
  
 Add `services/store.js` to your app or if you already extend the store add the flag bit below to it.
 
 ```ts
 import Store from "@ember-data/store";
 
 export default class extends Store {
   shouldTrackAsyncRequests = true;
 }
 ```

**Comment by runspired** [comment]
labeling this as a bug since we should activate our own tracking now that fetch is default. CC @snewcomer
