### ISSUE TITLE
@attr defaultValue function args no longer passed

### ISSUE THREAD

**Issue by mrloop** [emberjs/data#8221]
### Description

https://github.com/emberjs/data/commit/d606a22be7013c06c630d72f40465e9ec4139582 changed the signature of `defaultValue` function which could be passed as an option to `@attr`. A code comment at https://github.com/emberjs/data/blob/v4.7.3/packages/record-data/addon/-private/record-data.ts#L468 shows this is an intended breaking change.

I'm using the defaultValue functions to get localised default values using [`ember-intl`](https://github.com/ember-intl/ember-intl)  

```js
export default class ItemModel extends Model {
  @service intl; 
  
  @attr({ defaultValue: item => item.intl.t('item.default.title') }) title
}
```
Not sure how to do this without the defaultValue function having some sort of context

**Comment by runspired** [comment]
thanks for the bug report, I was hoping since the context there was undocumented it might be removable as it fixes a serious issue with how various concerns interop to be able to remove it.

the path to bring this back is complicated but doable, but it would also end up being deprecated immediately in favor of context-less defaultValue's. The best ways to refactor this would be to set the default tile during `createRecord` if no title is present, to set it via your API if it is possible you do not have titles on existing records, or to set it in the serializer if the API is not feasible.

If none of these work for you let's discuss on discord, because *a path* for refactoring what you've shown needs to exist even if this former behavior is restored.

**Comment by mrloop** [comment]
Thanks for the refactoring suggestions, my case is covered by setting the default values when calling `createRecord`.

**Comment by seanCodes** [comment]
@runspired I wonder if this could be revisited, because while workarounds like setting values on `createRecord()` exist, it’s no small task in a large app to update every usage of `createRecord()` to first handle default attributes. It’s also error-prone since a dev may not realize they need to handle certain attributes when creating certain records.

I’m confused about why this feature/functionality wasn’t called out as deprecated first (and a migration path with similar ergonomics provided) before it was removed. Was that intentional?

I understand there were good motivations for removing this but is there some other replacement that could be provided to keep things backward-compatible? For example, a Model class hook that runs before the record is actually created and can modify attribute values based on the ones provided? This way the logic could be handled in one place and co-located with the actual model itself. Does something like this already exist somewhere?

**Comment by runspired** [comment]
@seanCodes this only affects default values that were attempting to use instance state. Since to create an instance in this way you have to use `createRecord`, using `createRecord` is the simple approach. This isn't a workaround, its what should have always been the pattern for anything requiring instance state to initialize.

There's some consideration of exposing the cache to the function in Model's replacement. In this situation though, only serialized cache data would be able to be used in the computation, not anything hydrated or instance related.
