### ISSUE TITLE
[Request] Make fetch a bit less basic

### ISSUE THREAD

**Issue by Jopie01** [emberjs/data#8514]
The comment in https://github.com/emberjs/data/blob/15049beed153f1375b3eb2bfd9ba31da744b7e14/packages/request/src/fetch.ts says that this `fetch` is very basic and that the response is always `json`.

When everything goes right that will be the case, but sometimes the backend returns a `500` of `401` or `405` without any payload, or some text like `UNAUTHORIZED` or `Internal Server Error`. The current `fetch` will error out on not able to convert the response into a `json`.

So I propose to check for a set of status codes (https://developer.mozilla.org/en-US/docs/Web/HTTP/Status#client_error_responses) and based on that convert the response into `json`. Otherwise just keep the response as-is.
Another option can be to use the `response.ok` of `fetch` which indicates if the request was successful https://developer.mozilla.org/en-US/docs/Web/API/Response/ok

Alternatively everybody can implement their own `fetch` but `fetch` in it's current state is not that useful.

**Comment by runspired** [comment]
I do think we should do more but want to balance it with trying not to do everything, most apps will *want* their own handler implementation for exactly these sorts of decisions.

- I think we should read the headers and only do the parse if the content-type is json, which allows for errors to be json as well. I suspect we either return `text` or nothing at all in other cases.

- We also want to make sure we carry-forward the API error so some basic handling around that (anything 400+) would also be good to add.

- We should probably consider only handling if the headers specify json / url ends in .json, and throw an error otherwise.

**Comment by Jopie01** [comment]
> I do think we should do more but want to balance it with trying not to do everything, most apps will want their own handler implementation for exactly these sorts of decisions.

I totally agree with you, but to get started it would be nice not to bother with `fetch`. To me the most important thing was to not error on the JSON serialization but get the response back to the user.
