### ISSUE TITLE
Model attrs not accessible after destroying

### ISSUE THREAD

**Issue by amk221** [emberjs/data#8635]
### Description
In ED 3x, after deleting a model, it was possible to flash a message on screen, referring to that attributes on that model e.g.  `Model ${this.model.name} was deleted`

In 4x, this is possible in HBS land, like `Model {{@model.name}} was deleted`, but not in JS land.

Unless the model's attribute has been accessed _at least once_ in JS land, _or_ it is used in HBS land, then the value will be `undefined`

### Reproduction

Here is a reproduction / failing test: https://github.com/amk221/-ember-data-destroy-record-attrs/commit/e5b51f02800cf3bbf9332b0f29d455763484112c#diff-5fdf940d3833a427d5a68966cee01fe9e6fc093e5a0a19c0f4086a5023972f08R11

### Versions

Run the following command and paste the output below: `pnpm list ember-source && pnpm list ember-cli && pnpm list --pattern ember-data`.

```cli
example@0.0.0 
├─┬ @ember/test-helpers@2.9.3
│ ├─┬ @embroider/util@1.11.1
│ │ └── ember-source@4.12.0 deduped
│ └── ember-source@4.12.0 deduped
├─┬ ember-cli-app-version@6.0.0
│ └── ember-source@4.12.0 deduped
├─┬ ember-data@4.11.3
│ └─┬ @ember-data/model@4.11.3
│   └─┬ ember-cached-decorator-polyfill@1.0.1
│     └── ember-source@4.12.0 deduped
├─┬ ember-modifier@4.1.0
│ └── ember-source@4.12.0 deduped
├─┬ ember-qunit@6.2.0
│ └── ember-source@4.12.0 deduped
├─┬ ember-resolver@10.1.0
│ └── ember-source@4.12.0 deduped
└── ember-source@4.12.0

example@0.0.0 
├─┬ ember-cli-dependency-checker@3.3.1
│ └── ember-cli@4.12.1 deduped
└── ember-cli@4.12.1

example@0.0.0 
└── ember-data@4.11.3

```

**Comment by runspired** [comment]
broad strokes this is expected. As we shift more and more away from classic computeds some of the less-well spec'd classic computed behaviors may silently vanish, and computeds retaining state and never recalculating once their owner object is destroyed is a pretty unique quirk (and also dangerous, as it often lead to memory leaks).

If you use a more manual control flow though you will be able to do this.

`destroyRecord` is a "macro" that does 3 things

- synchronously tells the record it is deleted (`record.deleteRecord()` or `store.deleteRecord(record)`
- synchronously initiates a save of the record (`record.save()` or `store.saveRecord(record)`
- awaits the save promise and then unloads the record (`record.unloadRecord()` or `store.unloadRecord(record)`

The attributes and relationships will only be cleared once the `unloadRecord` bit occurs.

However, based on what you posted in slack there is another bit here to also be aware of. If a record is in the `new` state (e.g. `record.isNew === true`) which is true when a record has been created on the client and never persisted via a save, then calling `rollbackAttributes` or `deleteRecord` will *immediately* also unload the record. Not saying this behavior is great, but this has been a codified behavior since the earliest days of EmberData and I suspect it was done mostly to prevent memory leaks since too often folks wouldn't remember to fully clean up new records when bailing out on the create flow in their ux.

That means that if your form or what not may be displaying attributes for a `new` record, then you will want to perform a check of `isNew` and adjust teardown logic appropriately if you need to display information off of the record for a bit of time.

**Comment by amk221** [comment]
Thanks, I as a long time user, I'm aware of the isNew/rollbackAttributes quirk.

In terms of _this_ issue though, I fully appreciate that if I've deleted a model, I can't expect to be able to access its attributes after the fact. That makes sense. And I understand how an old-school computed property could have accidently cached that state.

But what's frustraiting is:
a) as far as I can tell nobody mentioned this was going to change and suddely break 
b) that it still feels broken - in sense that it's possbile to have code working by accident 
c) that the js behaves differently to hbs

It's possible we have loads of places in our codebase where we 'just so happen' to access a property before a deletion. And therefore, loads of places which are liable to just stop working whenever Ember Data decides to tighten down on these "less well speced" areas.

Should I assume that once delete/destroy record is called, that I should never be accessing a model's attributes? Shouldn't it just throw? If it's just a footgun?

Anyway, in terms of getting from v3 on to v4 and fixing the failing test in the above repo (with least effort) is the simplest thing to capture the attributes I want to use in the UI _before_ doing the deletion? It seems so

**Comment by runspired** [comment]
> Should I assume that once delete/destroy record is called, that I should never be accessing a model's attributes? Shouldn't it just throw? If it's just a footgun? Why make it half work?

delete is safe, destroy is not. Once the instance has been destroyed you should not assume accessing is safe. This honestly should have always been self-evident but the nature of Ember's object model and classic computeds has hidden this and you probably are right that yours isn't the only app that is using this without giving it proper consideration.

Unfortunately, attr/belongsTo/hasMany are *still* computeds because until we cut support for classic syntax they have to be, which is why if you've previously accessed you might be able to get away with re-access unexpectedly.

Note there is something else going on that allows the template to not recompute that EmberData has nothing to do with:  templates have their own memoization.

> In terms of getting from v3 on to v4 and fixing the failing test in the above repo (with least effort) is the simplest thing to capture the attributes I want to use in the UI before doing the deletion? It seems so...

This can work, or doing the unload only after you've shown what you want to show.

**Comment by amk221** [comment]
Thank you
