### ISSUE TITLE
Can multiple apps on the same page share the same store instance? 

### ISSUE THREAD

**Issue by lougreenwood** [emberjs/data#8668]
### Description

If a given webpage has multiple instances of different apps (think multiple Ember apps, or an Ember & Vue app when ED 6 makes ED possible in Vue etc) and all of those apps are using Ember Data, is it possible for them to all use the same "backend" or "database" (or however ED stores the contents of the `store`...) so that accessing data from the `store` in any of the apps returns the same data?

**Comment by runspired** [comment]
yes. You'd need to implement multiple reactivity integrations but that shouldn't be hard. Especially easy I think if (as we suspect) we end up implementing the default via starbeam so that we can quickly work with anything out of the box.

**Comment by lougreenwood** [comment]
That's good news, thanks! How would one setup multiple discrete instances of ED in each of the apps to use the same "backend", or is this default behaviour when there are multiple instances on a page?

**Comment by runspired** [comment]
@lougreenwood you'd want to expose a singleton in a shareable way just like you'd do with any other JS you wanted to share across. E.g. something along the lines of 

```ts
import Store from '@ember-data/store';

// ... do Store configuration

export const singletonStore = new Store();
```

You'd then want this either as its own JS bundle that all the various things could access independently (`await import('./ember-data-store.js')` or you'd reach for something that put the store on the global.

A very nice thing about this is that once we ship the background worker for EmberData they'd all be sharing that background worker as well :D

**Comment by lougreenwood** [comment]
Thanks @runspired, I really appreciate the guidance!

I have another question,  assuming that the app where we do the re-export of the initialised singleton is already an Ember app, and the other apps can import from it’s bundle, does that mean this is possible today without waiting for V6 and Ember-independence?

**Comment by runspired** [comment]
@lougreenwood if you already have the Ember dependencies and don't mind the extra weight, I'd say 90% you could and if you were willing to contribute a little work to EmberData we could make this 100% possible in a release cycle or two.

However, you'd be on a path no one has yet trodden, and as always with such take "this should work" with caveats.

Possible Approaches:

1.) Easier, would work today: Global Invalidation

- subscribe to the NotificationManager from each non-Ember app invalidating something at root causing a broader re-render.

2.) Slightly Harder: per-resource and per-collection invalidation

- subscribe to the NotificationManager from each non-Ember app. Invalidate collection or resource at point it was consumed by the app. For React this would probably mean a resource or collection provider component that re-renders whenever the resource or collection it subscribes to is notified. Dragons are mostly around changes to fields on relationships. You might not re-render without rigorously maintaining what is subscribed to..

3.) Harder, could probably be done in 1 release cycle of effort: Granular field-level invalidation via Pluggable `Tag` implementation. 

- This is where we see Starbeam fitting long-term. `Tag` is our wrapper around `tracked`. There's fairly minimal usage but anything making use of it (or cached since they interplay) would need to be abstracted to allow plugging in any signals implementation. Ideally We plug in Starbeam so that EmberData doesn't have to care too much and to add support to X framework simply means add the appropriate Starbeam config to Starbeam. (cc @wycats, not sure if he's thought about there being multiple Starbeam consumers on one page before ... )

4.) Hardest, would take several releases of effort and is in addition to (2): Implement a custom Model (or help us implement SchemaModel)

- The reason to do this is that you would want your models to be not using EmberObject under the hood. There's a lot of pitfalls around notification cycles with computed/observers/chains that getting into a signals-only world eliminates.

**Comment by runspired** [comment]
Closing as the question has been asnwered
