### ISSUE TITLE
[5.3.7] `ember-inflector` must be a installed, otherwise production build is broken

### ISSUE THREAD

**Issue by mkszepp** [emberjs/data#9501]
While updating packages in `ember-power-select` docs i'm running into this error in production build.

![grafik](https://github.com/emberjs/data/assets/19845290/bda0d938-9ae7-4fb9-a866-8d02ca39962e)

When running `ember test` or `ember s` the error is not present, but `ember s -prod` or also `ember build -prod` are generating a broken build (error in browser).

We don't use any `inflector` rule, for this reason we also don't get deprecation warning while `ember s`.

### Steps

1. Clone [ember-power-select](https://github.com/cibernox/ember-power-select)
2. Remove package `ember-inflector` from `docs/package.json`
3. `pnpm i`
4. `cd docs`
5. `ember s -prod`

### Workaround
Add `ember-inflector` to `package.json`

**Comment by runspired** [comment]
you'll want to run `pnpm why -r ember-inflector` to figure out why it was available even when not ostensibly installed. It's likely another dependency is bringing it in a way that makes it visible to node resolution but not included in the app assets

**Comment by runspired** [comment]
I looked at the pnpm lockfile in power-select for the commit prior to you adding ember-inflector in as a dependency. The problem is that ember-inflector is installed by `mirage`, but then the addon deactivates itself in production. Deactivated addons won't have their dependent addons included in the build; however, they are still installed and so still visible to embroider/macros (cc @mansona @NullVoxPopuli and @ef4 who probably already know this nuance but just to surface an odd edge case with classic+macros)

I'd argue that the correct thing here is for power-select to do exactly as it did and put ember-inflector in its dev-deps.

You can see mirage is what brings the library here: https://github.com/cibernox/ember-power-select/blob/734c21825204f45dc7f7aca776d3e4abfcffaba3/pnpm-lock.yaml#L7452
