### ISSUE TITLE
How to actually use the new RequestManager architecture

### ISSUE THREAD

**Issue by paddor** [emberjs/data#9544]
So after upgrading to Octane and the current latest Ember LTS version of 5.4 and ember-data 5.3, the only thing left is replacing our application adapter. So far, we've used a stub implementation because the store itself never had to actually create/update/delete records itself. In our message-passing architecture that's handled separately via messages.

This stub implementation has been running well for years:

```js
import { service } from '@ember/service';
import JSONAPIAdapter from '@ember-data/adapter/json-api';
import { Promise } from 'rsvp';

export default class Application extends JSONAPIAdapter {
  @service logger;
  @service('messaging/messaging') messaging;
  @service engine;

  coalesceFindRequests = true;

  findRecord(store, type, id, _snapshot) {
    return new Promise((resolve, reject) => {
      this.messaging.CSP.getObjectsDialog([id]).then(
        model => {
          model.data = model.data[0];
          this.logger.info(`Loaded ${type} record ${id} on demand`);

          resolve(model);
        },
        reason => {
          this.logger.error(`Loading of ${type} record ${id} failed. Reason:`, reason);
          reject(reason);
        }
      );
    });
  }

  findMany(store, type, ids, _snapshots) {
    return new Promise((resolve, reject) => {
      this.messaging.CSP.getObjectsDialog(ids).then(
        (model) => {
          this.logger.info(`Loaded ${model.data.length} ${type} records on demand`);

          resolve(model);
        },
        reason => {
          this.logger.error(`Loading of records failed. Record IDs:`, ids);
          reject(`requesting objects failed: ${reason}`);
        }
      );
    });
  }

  findAll(store, type) {
    return new Promise((resolve, reject) => {
      this.messaging.CSP.findObjectsDialog(type.modelName).then(
        (model) => {
          this.logger.info(`Found ${model.data.length} ${type} records`);

          resolve(model);
        },
        reason => {
          this.logger.error(`Finding records of type ${type} failed.`);
          reject(`requesting objects failed: ${reason}`);
        }
      );
    });
  }

  shouldReloadRecord(store, snapshot) {
    console.debug("shouldReloadRecord", snapshot, snapshot.attr('id'));
    return !snapshot.record.isLoaded;
  }

  shouldReloadAll(store, snapshotArray) {
    console.debug("shouldReloadAll", snapshotArray);
    return snapshotArray.snapshots().any(snapshot => !snapshot.record.isLoaded)
  }

  updateRecord() {
    return undefined; // NOTE: make ember assume record was stored on backend
  }
}
```

How would this be ported into a custom Handler for the new RequestManager?

**Comment by runspired** [comment]
probably easier to work through this question in the discord, but I'll reframe the question here to state better what it is *I Think* you're asking:

Given data-source (typically a backend API) that does not use HTTP transport (websockets) and thus does not use urls, how should builders go about constructing requests and handlers go about fulfilling those requests in a way that is (1) cacheable and (2) follows best-practices.

For this: the first part of my talk from EmberFest this year which breaks down what the various parts of the request interface do might be helpful. [Recording](https://www.youtube.com/watch?v=BCv8OgcG5vM&list=PLN4SpDLOSVkQ6nMGEQMt4xABHPaWCPnuL&index=9)

Generally speaking: you will want to build requests that do one of two things to ensure cache compatibility:

- use the url to set the cache-key for the request (url doesn't necessarily need to follow url guidelines in this case, just needs to be an accurate key for the given request) AND set `method` appropriately still

- OR set url to some preferably non-empty (but also generic) string like `/csp-request` and use `cacheOptions.key` to set the cache key. You should still set `method` appropriately, though it becomes less required to do so in this approach.

As far as best-practices go: a lot about the builder/handler relationship is intentionally opaque to WarpDrive/EmberData so that applications can design whatever relationship between the two they feel best suites their needs. E.g. we define the structure of what a request looks like, but what you put into that structure is left to you. The main things you will want to consider are (1) using `op` codes and `cacheOptions.types` to opt-in to more advanced behaviors / help your handler(s) more quickly differentiate types of requests and (2) setup any data normalization required to convert to/from the cache format if your API does not speak the same flavor of JSON:API as the default cache does (you could also write a non-JSON:API cache but that is a much bigger undertaking)

**Comment by paddor** [comment]
So I'm back at this issue. I want to get rid of `@ember-data/legacy-compat`, because it seems to be the reason `ember-cli-babel` 7.26.11 is installed, which is ancient and depends on core-js@2.

I appreciate your answer but I absolutely don't understand it.

What we need should be really simple. The store is fed/updated continually by the backend (with JSONAPI and Ember Store's `push` method) and NEVER has to make network requests itself. It always contains all records. We only use the `peek*` methods, never the `find*` methods.

The above code that defines a `class Application extends JSONAPIAdapter` literally just stubs all methods that would cause network requests. It's been running for about a decade with no problems. How can that be done with the new WarpDrive/RequestManager infrastructure?

**Comment by runspired** [comment]
> So I'm back at this issue. I want to get rid of @ember-data/legacy-compat, because it seems to be the reason ember-cli-babel 7.26.11 is installed, which is ancient and depends on core-js@2.

This doesn't seem right? 5.x versions of things are V2 addons, there is no ember-cli-babel at all. 4.12 does specify `"ember-cli-babel": "^7.26.11",` but it'll accept an 7.x OOB and you can always use a resolution to force it to latest, its compatible with any ember-cli-babel.

In terms of your app architecture: its not one we intend to support going forward. While the decision to deprecate `peekAll` hasn't been made yet, I'd say I'm personally about 99% sure we should deprecate it. It's theoretically possible for an addon to provide continued support for the feature, but it's no longer part of the happy path.

We're very focused on apps using a request-centric architecture, and that includes for apps like yours that wish to try to maintain a full picture of state locally. Am happy to dive into how you might evolve your app to fit into those paradigms (or what some good alternatives for you other than EmberData might be if you find you don't like the way that looks).

**Comment by paddor** [comment]
Honestly, I don't know what makes an addon a "V2" addon. Some of our addons are about a decade old and we've continually updated them. From Classic to Octane, from Ember 3 to 4 to 5.

I've just created another Ember addon and can't see a difference in the `package.json` file that would suggest anything "V2". It even includes a dependency to `ember-cli-babel`. If you tell me that `ember-cli-babel` is not needed anymore, I'm happy to kick it out of the dependencies.

Sad to hear that `peekAll` might be deprecated soon. How do you suggest implementing a reactive information model for SCADA applications, where things need to be displayed in a live and reactive manner? We often need to navigate to a page with a set of entities from the store, which is where `peekAll` usually comes in. That works because the information model is mostly a fixed size, only the values get continually updated.

Yes, we'd appreciate if you could suggest a way forward that fits the future of EmberData. We have tons of EmberData models that we like to keep.

**Comment by runspired** [comment]
> Honestly, I don't know what makes an addon a "V2" addon. Some of our addons are about a decade old and we've continually updated them. From Classic to Octane, from Ember 3 to 4 to 5.

The `addon-main` field specifies it as v2, there's a spec for v2 addons. Specifically I meant that EmberData's packages are v2 addons when using the 5.x series, only 4.12.x is still a V1 addon. 4.13 (coming shortly) will be V2 addons.

> Yes, we'd appreciate if you could suggest a way forward that fits the future of EmberData. We have tons of EmberData models that we like to keep.

lets setup some time soon, ping me in discord and we'll find a calendar slot that works for both of us.
